// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventTsNavigationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventTsNavigation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string cid = 19;</code>
   * @return Whether the cid field is set.
   */
  boolean hasCid();
  /**
   * <code>optional string cid = 19;</code>
   * @return The cid.
   */
  java.lang.String getCid();
  /**
   * <code>optional string cid = 19;</code>
   * @return The bytes for cid.
   */
  com.google.protobuf.ByteString
      getCidBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 entry_point_conversation_initiated_number = 23;</code>
   * @return Whether the entryPointConversationInitiatedNumber field is set.
   */
  boolean hasEntryPointConversationInitiatedNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 entry_point_conversation_initiated_number = 23;</code>
   * @return The entryPointConversationInitiatedNumber.
   */
  long getEntryPointConversationInitiatedNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 group_size = 1;</code>
   * @return Whether the groupSize field is set.
   */
  boolean hasGroupSize();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 group_size = 1;</code>
   * @return The groupSize.
   */
  long getGroupSize();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_catalog_visible = 29;</code>
   * @return Whether the isCatalogVisible field is set.
   */
  boolean hasIsCatalogVisible();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_catalog_visible = 29;</code>
   * @return The isCatalogVisible.
   */
  long getIsCatalogVisible();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_cloudapi = 26;</code>
   * @return Whether the isCloudapi field is set.
   */
  boolean hasIsCloudapi();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_cloudapi = 26;</code>
   * @return The isCloudapi.
   */
  long getIsCloudapi();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_onpremises = 27;</code>
   * @return Whether the isOnpremises field is set.
   */
  boolean hasIsOnpremises();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_onpremises = 27;</code>
   * @return The isOnpremises.
   */
  long getIsOnpremises();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_smb = 28;</code>
   * @return Whether the isSmb field is set.
   */
  boolean hasIsSmb();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_smb = 28;</code>
   * @return The isSmb.
   */
  long getIsSmb();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 navigation_destination_number = 2;</code>
   * @return Whether the navigationDestinationNumber field is set.
   */
  boolean hasNavigationDestinationNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 navigation_destination_number = 2;</code>
   * @return The navigationDestinationNumber.
   */
  long getNavigationDestinationNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 navigation_source_number = 3;</code>
   * @return Whether the navigationSourceNumber field is set.
   */
  boolean hasNavigationSourceNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 navigation_source_number = 3;</code>
   * @return The navigationSourceNumber.
   */
  long getNavigationSourceNumber();

  /**
   * <pre>
   * unknown typeton
   * </pre>
   *
   * <code>optional int64 relative_timestamp_ms = 4;</code>
   * @return Whether the relativeTimestampMs field is set.
   */
  boolean hasRelativeTimestampMs();
  /**
   * <pre>
   * unknown typeton
   * </pre>
   *
   * <code>optional int64 relative_timestamp_ms = 4;</code>
   * @return The relativeTimestampMs.
   */
  long getRelativeTimestampMs();

  /**
   * <code>optional string smb_catalog_business_vertical = 20;</code>
   * @return Whether the smbCatalogBusinessVertical field is set.
   */
  boolean hasSmbCatalogBusinessVertical();
  /**
   * <code>optional string smb_catalog_business_vertical = 20;</code>
   * @return The smbCatalogBusinessVertical.
   */
  java.lang.String getSmbCatalogBusinessVertical();
  /**
   * <code>optional string smb_catalog_business_vertical = 20;</code>
   * @return The bytes for smbCatalogBusinessVertical.
   */
  com.google.protobuf.ByteString
      getSmbCatalogBusinessVerticalBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_catalog_is_catalog_visible = 21;</code>
   * @return Whether the smbCatalogIsCatalogVisible field is set.
   */
  boolean hasSmbCatalogIsCatalogVisible();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_catalog_is_catalog_visible = 21;</code>
   * @return The smbCatalogIsCatalogVisible.
   */
  long getSmbCatalogIsCatalogVisible();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 thread_type_number = 7;</code>
   * @return Whether the threadTypeNumber field is set.
   */
  boolean hasThreadTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 thread_type_number = 7;</code>
   * @return The threadTypeNumber.
   */
  long getThreadTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 ts_session_id = 5;</code>
   * @return Whether the tsSessionId field is set.
   */
  boolean hasTsSessionId();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 ts_session_id = 5;</code>
   * @return The tsSessionId.
   */
  long getTsSessionId();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 type_of_group_number = 6;</code>
   * @return Whether the typeOfGroupNumber field is set.
   */
  boolean hasTypeOfGroupNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 type_of_group_number = 6;</code>
   * @return The typeOfGroupNumber.
   */
  long getTypeOfGroupNumber();

  /**
   * <code>optional string entry_point_conversion_app = 24;</code>
   * @return Whether the entryPointConversionApp field is set.
   */
  boolean hasEntryPointConversionApp();
  /**
   * <code>optional string entry_point_conversion_app = 24;</code>
   * @return The entryPointConversionApp.
   */
  java.lang.String getEntryPointConversionApp();
  /**
   * <code>optional string entry_point_conversion_app = 24;</code>
   * @return The bytes for entryPointConversionApp.
   */
  com.google.protobuf.ByteString
      getEntryPointConversionAppBytes();

  /**
   * <code>optional string entry_point_conversion_source = 25;</code>
   * @return Whether the entryPointConversionSource field is set.
   */
  boolean hasEntryPointConversionSource();
  /**
   * <code>optional string entry_point_conversion_source = 25;</code>
   * @return The entryPointConversionSource.
   */
  java.lang.String getEntryPointConversionSource();
  /**
   * <code>optional string entry_point_conversion_source = 25;</code>
   * @return The bytes for entryPointConversionSource.
   */
  com.google.protobuf.ByteString
      getEntryPointConversionSourceBytes();

  /**
   * <code>optional int64 referrerAction = 31;</code>
   * @return Whether the referrerAction field is set.
   */
  boolean hasReferrerAction();
  /**
   * <code>optional int64 referrerAction = 31;</code>
   * @return The referrerAction.
   */
  long getReferrerAction();

  /**
   * <code>optional int64 tsTimestampMs = 32;</code>
   * @return Whether the tsTimestampMs field is set.
   */
  boolean hasTsTimestampMs();
  /**
   * <code>optional int64 tsTimestampMs = 32;</code>
   * @return The tsTimestampMs.
   */
  long getTsTimestampMs();

  /**
   * <code>optional string unifiedSessionId = 33;</code>
   * @return Whether the unifiedSessionId field is set.
   */
  boolean hasUnifiedSessionId();
  /**
   * <code>optional string unifiedSessionId = 33;</code>
   * @return The unifiedSessionId.
   */
  java.lang.String getUnifiedSessionId();
  /**
   * <code>optional string unifiedSessionId = 33;</code>
   * @return The bytes for unifiedSessionId.
   */
  com.google.protobuf.ByteString
      getUnifiedSessionIdBytes();
}
