// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventMessageReceiveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventMessageReceive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 agent_engagement_type_number = 28;</code>
   * @return Whether the agentEngagementTypeNumber field is set.
   */
  boolean hasAgentEngagementTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 agent_engagement_type_number = 28;</code>
   * @return The agentEngagementTypeNumber.
   */
  long getAgentEngagementTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 bot_type_number = 37;</code>
   * @return Whether the botTypeNumber field is set.
   */
  boolean hasBotTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 bot_type_number = 37;</code>
   * @return The botTypeNumber.
   */
  long getBotTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 device_count = 16;</code>
   * @return Whether the deviceCount field is set.
   */
  boolean hasDeviceCount();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 device_count = 16;</code>
   * @return The deviceCount.
   */
  long getDeviceCount();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 device_size_bucket_number = 10;</code>
   * @return Whether the deviceSizeBucketNumber field is set.
   */
  boolean hasDeviceSizeBucketNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 device_size_bucket_number = 10;</code>
   * @return The deviceSizeBucketNumber.
   */
  long getDeviceSizeBucketNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 disappearing_chat_initiator_number = 14;</code>
   * @return Whether the disappearingChatInitiatorNumber field is set.
   */
  boolean hasDisappearingChatInitiatorNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 disappearing_chat_initiator_number = 14;</code>
   * @return The disappearingChatInitiatorNumber.
   */
  long getDisappearingChatInitiatorNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 edit_type_number = 25;</code>
   * @return Whether the editTypeNumber field is set.
   */
  boolean hasEditTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 edit_type_number = 25;</code>
   * @return The editTypeNumber.
   */
  long getEditTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 ephemerality_duration = 13;</code>
   * @return Whether the ephemeralityDuration field is set.
   */
  boolean hasEphemeralityDuration();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 ephemerality_duration = 13;</code>
   * @return The ephemeralityDuration.
   */
  long getEphemeralityDuration();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 ephemerality_initiator_number = 26;</code>
   * @return Whether the ephemeralityInitiatorNumber field is set.
   */
  boolean hasEphemeralityInitiatorNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 ephemerality_initiator_number = 26;</code>
   * @return The ephemeralityInitiatorNumber.
   */
  long getEphemeralityInitiatorNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 ephemerality_trigger_action_number = 27;</code>
   * @return Whether the ephemeralityTriggerActionNumber field is set.
   */
  boolean hasEphemeralityTriggerActionNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 ephemerality_trigger_action_number = 27;</code>
   * @return The ephemeralityTriggerActionNumber.
   */
  long getEphemeralityTriggerActionNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 has_username = 39;</code>
   * @return Whether the hasUsername field is set.
   */
  boolean hasHasUsername();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 has_username = 39;</code>
   * @return The hasUsername.
   */
  long getHasUsername();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_addressing_mode_number = 34;</code>
   * @return Whether the messageAddressingModeNumber field is set.
   */
  boolean hasMessageAddressingModeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_addressing_mode_number = 34;</code>
   * @return The messageAddressingModeNumber.
   */
  long getMessageAddressingModeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_is_international = 4;</code>
   * @return Whether the messageIsInternational field is set.
   */
  boolean hasMessageIsInternational();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_is_international = 4;</code>
   * @return The messageIsInternational.
   */
  long getMessageIsInternational();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_media_type_number = 2;</code>
   * @return Whether the messageMediaTypeNumber field is set.
   */
  boolean hasMessageMediaTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_media_type_number = 2;</code>
   * @return The messageMediaTypeNumber.
   */
  long getMessageMediaTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_queue_time = 15;</code>
   * @return Whether the messageQueueTime field is set.
   */
  boolean hasMessageQueueTime();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_queue_time = 15;</code>
   * @return The messageQueueTime.
   */
  long getMessageQueueTime();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_receive_t0 = 6;</code>
   * @return Whether the messageReceiveT0 field is set.
   */
  boolean hasMessageReceiveT0();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_receive_t0 = 6;</code>
   * @return The messageReceiveT0.
   */
  long getMessageReceiveT0();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_receive_t1 = 7;</code>
   * @return Whether the messageReceiveT1 field is set.
   */
  boolean hasMessageReceiveT1();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_receive_t1 = 7;</code>
   * @return The messageReceiveT1.
   */
  long getMessageReceiveT1();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_type_number = 1;</code>
   * @return Whether the messageTypeNumber field is set.
   */
  boolean hasMessageTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_type_number = 1;</code>
   * @return The messageTypeNumber.
   */
  long getMessageTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 muted_group_message = 8;</code>
   * @return Whether the mutedGroupMessage field is set.
   */
  boolean hasMutedGroupMessage();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 muted_group_message = 8;</code>
   * @return The mutedGroupMessage.
   */
  long getMutedGroupMessage();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 offline_count = 30;</code>
   * @return Whether the offlineCount field is set.
   */
  boolean hasOfflineCount();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 offline_count = 30;</code>
   * @return The offlineCount.
   */
  long getOfflineCount();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 padding_bytes_size = 22;</code>
   * @return Whether the paddingBytesSize field is set.
   */
  boolean hasPaddingBytesSize();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 padding_bytes_size = 22;</code>
   * @return The paddingBytesSize.
   */
  long getPaddingBytesSize();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 participant_count = 17;</code>
   * @return Whether the participantCount field is set.
   */
  boolean hasParticipantCount();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 participant_count = 17;</code>
   * @return The participantCount.
   */
  long getParticipantCount();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 revoke_type_number = 20;</code>
   * @return Whether the revokeTypeNumber field is set.
   */
  boolean hasRevokeTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 revoke_type_number = 20;</code>
   * @return The revokeTypeNumber.
   */
  long getRevokeTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 sender_default_disappearing_duration = 11;</code>
   * @return Whether the senderDefaultDisappearingDuration field is set.
   */
  boolean hasSenderDefaultDisappearingDuration();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 sender_default_disappearing_duration = 11;</code>
   * @return The senderDefaultDisappearingDuration.
   */
  long getSenderDefaultDisappearingDuration();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 server_addressing_mode_number = 35;</code>
   * @return Whether the serverAddressingModeNumber field is set.
   */
  boolean hasServerAddressingModeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 server_addressing_mode_number = 35;</code>
   * @return The serverAddressingModeNumber.
   */
  long getServerAddressingModeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 sticker_is_ai = 29;</code>
   * @return Whether the stickerIsAi field is set.
   */
  boolean hasStickerIsAi();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 sticker_is_ai = 29;</code>
   * @return The stickerIsAi.
   */
  long getStickerIsAi();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 sticker_is_from_sticker_maker = 31;</code>
   * @return Whether the stickerIsFromStickerMaker field is set.
   */
  boolean hasStickerIsFromStickerMaker();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 sticker_is_from_sticker_maker = 31;</code>
   * @return The stickerIsFromStickerMaker.
   */
  long getStickerIsFromStickerMaker();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 sticker_maker_source_type_number = 32;</code>
   * @return Whether the stickerMakerSourceTypeNumber field is set.
   */
  boolean hasStickerMakerSourceTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 sticker_maker_source_type_number = 32;</code>
   * @return The stickerMakerSourceTypeNumber.
   */
  long getStickerMakerSourceTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 type_of_group_number = 21;</code>
   * @return Whether the typeOfGroupNumber field is set.
   */
  boolean hasTypeOfGroupNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 type_of_group_number = 21;</code>
   * @return The typeOfGroupNumber.
   */
  long getTypeOfGroupNumber();

  /**
   * <code>optional int64 isAComment = 36;</code>
   * @return Whether the isAComment field is set.
   */
  boolean hasIsAComment();
  /**
   * <code>optional int64 isAComment = 36;</code>
   * @return The isAComment.
   */
  long getIsAComment();

  /**
   * <code>optional int64 isAReply = 19;</code>
   * @return Whether the isAReply field is set.
   */
  boolean hasIsAReply();
  /**
   * <code>optional int64 isAReply = 19;</code>
   * @return The isAReply.
   */
  long getIsAReply();

  /**
   * <code>optional int64 isForwardedForward = 18;</code>
   * @return Whether the isForwardedForward field is set.
   */
  boolean hasIsForwardedForward();
  /**
   * <code>optional int64 isForwardedForward = 18;</code>
   * @return The isForwardedForward.
   */
  long getIsForwardedForward();

  /**
   * <code>optional int64 isLid = 24;</code>
   * @return Whether the isLid field is set.
   */
  boolean hasIsLid();
  /**
   * <code>optional int64 isLid = 24;</code>
   * @return The isLid.
   */
  long getIsLid();

  /**
   * <code>optional int64 isViewOnce = 9;</code>
   * @return Whether the isViewOnce field is set.
   */
  boolean hasIsViewOnce();
  /**
   * <code>optional int64 isViewOnce = 9;</code>
   * @return The isViewOnce.
   */
  long getIsViewOnce();

  /**
   * <code>optional int64 localAddressingMode = 33;</code>
   * @return Whether the localAddressingMode field is set.
   */
  boolean hasLocalAddressingMode();
  /**
   * <code>optional int64 localAddressingMode = 33;</code>
   * @return The localAddressingMode.
   */
  long getLocalAddressingMode();

  /**
   * <code>optional int64 messageIsOffline = 5;</code>
   * @return Whether the messageIsOffline field is set.
   */
  boolean hasMessageIsOffline();
  /**
   * <code>optional int64 messageIsOffline = 5;</code>
   * @return The messageIsOffline.
   */
  long getMessageIsOffline();

  /**
   * <code>optional int64 receiverDefaultDisappearingDuration = 12;</code>
   * @return Whether the receiverDefaultDisappearingDuration field is set.
   */
  boolean hasReceiverDefaultDisappearingDuration();
  /**
   * <code>optional int64 receiverDefaultDisappearingDuration = 12;</code>
   * @return The receiverDefaultDisappearingDuration.
   */
  long getReceiverDefaultDisappearingDuration();
}
