// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventAdvStoredTimestampExpiredOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventAdvStoredTimestampExpired)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 adv_expire_time_in_hours = 1;</code>
   * @return Whether the advExpireTimeInHours field is set.
   */
  boolean hasAdvExpireTimeInHours();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 adv_expire_time_in_hours = 1;</code>
   * @return The advExpireTimeInHours.
   */
  long getAdvExpireTimeInHours();
}
