// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventE2eMessageRecvOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventE2eMessageRecv)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 agent_engagement_type_number = 15;</code>
   * @return Whether the agentEngagementTypeNumber field is set.
   */
  boolean hasAgentEngagementTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 agent_engagement_type_number = 15;</code>
   * @return The agentEngagementTypeNumber.
   */
  long getAgentEngagementTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 bot_type_number = 19;</code>
   * @return Whether the botTypeNumber field is set.
   */
  boolean hasBotTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 bot_type_number = 19;</code>
   * @return The botTypeNumber.
   */
  long getBotTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_ciphertext_type_number = 5;</code>
   * @return Whether the e2eCiphertextTypeNumber field is set.
   */
  boolean hasE2ECiphertextTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_ciphertext_type_number = 5;</code>
   * @return The e2eCiphertextTypeNumber.
   */
  long getE2ECiphertextTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_ciphertext_version = 6;</code>
   * @return Whether the e2eCiphertextVersion field is set.
   */
  boolean hasE2ECiphertextVersion();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_ciphertext_version = 6;</code>
   * @return The e2eCiphertextVersion.
   */
  long getE2ECiphertextVersion();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_destination_number = 4;</code>
   * @return Whether the e2eDestinationNumber field is set.
   */
  boolean hasE2EDestinationNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_destination_number = 4;</code>
   * @return The e2eDestinationNumber.
   */
  long getE2EDestinationNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_failure_reason_number = 2;</code>
   * @return Whether the e2eFailureReasonNumber field is set.
   */
  boolean hasE2EFailureReasonNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_failure_reason_number = 2;</code>
   * @return The e2eFailureReasonNumber.
   */
  long getE2EFailureReasonNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_sender_type_number = 8;</code>
   * @return Whether the e2eSenderTypeNumber field is set.
   */
  boolean hasE2ESenderTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_sender_type_number = 8;</code>
   * @return The e2eSenderTypeNumber.
   */
  long getE2ESenderTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_successful = 1;</code>
   * @return Whether the e2eSuccessful field is set.
   */
  boolean hasE2ESuccessful();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 e2e_successful = 1;</code>
   * @return The e2eSuccessful.
   */
  long getE2ESuccessful();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 edit_type_number = 13;</code>
   * @return Whether the editTypeNumber field is set.
   */
  boolean hasEditTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 edit_type_number = 13;</code>
   * @return The editTypeNumber.
   */
  long getEditTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_hosted_chat = 20;</code>
   * @return Whether the isHostedChat field is set.
   */
  boolean hasIsHostedChat();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_hosted_chat = 20;</code>
   * @return The isHostedChat.
   */
  long getIsHostedChat();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_lid = 11;</code>
   * @return Whether the isLid field is set.
   */
  boolean hasIsLid();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_lid = 11;</code>
   * @return The isLid.
   */
  long getIsLid();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 local_addressing_mode_number = 16;</code>
   * @return Whether the localAddressingModeNumber field is set.
   */
  boolean hasLocalAddressingModeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 local_addressing_mode_number = 16;</code>
   * @return The localAddressingModeNumber.
   */
  long getLocalAddressingModeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_addressing_mode_number = 17;</code>
   * @return Whether the messageAddressingModeNumber field is set.
   */
  boolean hasMessageAddressingModeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_addressing_mode_number = 17;</code>
   * @return The messageAddressingModeNumber.
   */
  long getMessageAddressingModeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_media_type_number = 7;</code>
   * @return Whether the messageMediaTypeNumber field is set.
   */
  boolean hasMessageMediaTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_media_type_number = 7;</code>
   * @return The messageMediaTypeNumber.
   */
  long getMessageMediaTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 offline = 9;</code>
   * @return Whether the offline field is set.
   */
  boolean hasOffline();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 offline = 9;</code>
   * @return The offline.
   */
  long getOffline();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 retry_count = 3;</code>
   * @return Whether the retryCount field is set.
   */
  boolean hasRetryCount();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 retry_count = 3;</code>
   * @return The retryCount.
   */
  long getRetryCount();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 revoke_type_number = 10;</code>
   * @return Whether the revokeTypeNumber field is set.
   */
  boolean hasRevokeTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 revoke_type_number = 10;</code>
   * @return The revokeTypeNumber.
   */
  long getRevokeTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 server_addressing_mode_number = 18;</code>
   * @return Whether the serverAddressingModeNumber field is set.
   */
  boolean hasServerAddressingModeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 server_addressing_mode_number = 18;</code>
   * @return The serverAddressingModeNumber.
   */
  long getServerAddressingModeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 stanza_type_number = 14;</code>
   * @return Whether the stanzaTypeNumber field is set.
   */
  boolean hasStanzaTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 stanza_type_number = 14;</code>
   * @return The stanzaTypeNumber.
   */
  long getStanzaTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 type_of_group_number = 12;</code>
   * @return Whether the typeOfGroupNumber field is set.
   */
  boolean hasTypeOfGroupNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 type_of_group_number = 12;</code>
   * @return The typeOfGroupNumber.
   */
  long getTypeOfGroupNumber();

  /**
   * <code>optional int64 messageDistributionType = 21;</code>
   * @return Whether the messageDistributionType field is set.
   */
  boolean hasMessageDistributionType();
  /**
   * <code>optional int64 messageDistributionType = 21;</code>
   * @return The messageDistributionType.
   */
  long getMessageDistributionType();
}
