// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

/**
 * Protobuf type {@code Wam.WamEntryPointConversion}
 */
public  final class WamEntryPointConversion extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Wam.WamEntryPointConversion)
    WamEntryPointConversionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WamEntryPointConversion.newBuilder() to construct.
  private WamEntryPointConversion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WamEntryPointConversion() {
    entryPointConversionSource_ = "";
    entryPointConversionApp_ = "";
    entryPointConversionExternalMedium_ = "";
    entryPointConversionExternalSource_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WamEntryPointConversion();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WamEntryPointConversion(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            entryPointConverstionType_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            entryPointConversionSource_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            entryPointConversionApp_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            firstMessageTimeStamp_ = input.readInt64();
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            entryPointConversionExternalMedium_ = bs;
            break;
          }
          case 50: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000020;
            entryPointConversionExternalSource_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Wam.proto.WamProto.internal_static_Wam_WamEntryPointConversion_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Wam.proto.WamProto.internal_static_Wam_WamEntryPointConversion_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Wam.proto.WamEntryPointConversion.class, Wam.proto.WamEntryPointConversion.Builder.class);
  }

  private int bitField0_;
  public static final int ENTRY_POINT_CONVERSTION_TYPE_FIELD_NUMBER = 1;
  private long entryPointConverstionType_;
  /**
   * <code>optional int64 entry_point_converstion_type = 1;</code>
   * @return Whether the entryPointConverstionType field is set.
   */
  public boolean hasEntryPointConverstionType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 entry_point_converstion_type = 1;</code>
   * @return The entryPointConverstionType.
   */
  public long getEntryPointConverstionType() {
    return entryPointConverstionType_;
  }

  public static final int ENTRY_POINT_CONVERSION_SOURCE_FIELD_NUMBER = 2;
  private volatile java.lang.Object entryPointConversionSource_;
  /**
   * <code>optional string entry_point_conversion_source = 2;</code>
   * @return Whether the entryPointConversionSource field is set.
   */
  public boolean hasEntryPointConversionSource() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string entry_point_conversion_source = 2;</code>
   * @return The entryPointConversionSource.
   */
  public java.lang.String getEntryPointConversionSource() {
    java.lang.Object ref = entryPointConversionSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        entryPointConversionSource_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string entry_point_conversion_source = 2;</code>
   * @return The bytes for entryPointConversionSource.
   */
  public com.google.protobuf.ByteString
      getEntryPointConversionSourceBytes() {
    java.lang.Object ref = entryPointConversionSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entryPointConversionSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTRY_POINT_CONVERSION_APP_FIELD_NUMBER = 3;
  private volatile java.lang.Object entryPointConversionApp_;
  /**
   * <code>optional string entry_point_conversion_app = 3;</code>
   * @return Whether the entryPointConversionApp field is set.
   */
  public boolean hasEntryPointConversionApp() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string entry_point_conversion_app = 3;</code>
   * @return The entryPointConversionApp.
   */
  public java.lang.String getEntryPointConversionApp() {
    java.lang.Object ref = entryPointConversionApp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        entryPointConversionApp_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string entry_point_conversion_app = 3;</code>
   * @return The bytes for entryPointConversionApp.
   */
  public com.google.protobuf.ByteString
      getEntryPointConversionAppBytes() {
    java.lang.Object ref = entryPointConversionApp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entryPointConversionApp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRST_MESSAGE_TIME_STAMP_FIELD_NUMBER = 4;
  private long firstMessageTimeStamp_;
  /**
   * <code>optional int64 first_message_time_stamp = 4;</code>
   * @return Whether the firstMessageTimeStamp field is set.
   */
  public boolean hasFirstMessageTimeStamp() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int64 first_message_time_stamp = 4;</code>
   * @return The firstMessageTimeStamp.
   */
  public long getFirstMessageTimeStamp() {
    return firstMessageTimeStamp_;
  }

  public static final int ENTRY_POINT_CONVERSION_EXTERNAL_MEDIUM_FIELD_NUMBER = 5;
  private volatile java.lang.Object entryPointConversionExternalMedium_;
  /**
   * <code>optional string entry_point_conversion_external_medium = 5;</code>
   * @return Whether the entryPointConversionExternalMedium field is set.
   */
  public boolean hasEntryPointConversionExternalMedium() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string entry_point_conversion_external_medium = 5;</code>
   * @return The entryPointConversionExternalMedium.
   */
  public java.lang.String getEntryPointConversionExternalMedium() {
    java.lang.Object ref = entryPointConversionExternalMedium_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        entryPointConversionExternalMedium_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string entry_point_conversion_external_medium = 5;</code>
   * @return The bytes for entryPointConversionExternalMedium.
   */
  public com.google.protobuf.ByteString
      getEntryPointConversionExternalMediumBytes() {
    java.lang.Object ref = entryPointConversionExternalMedium_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entryPointConversionExternalMedium_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTRY_POINT_CONVERSION_EXTERNAL_SOURCE_FIELD_NUMBER = 6;
  private volatile java.lang.Object entryPointConversionExternalSource_;
  /**
   * <code>optional string entry_point_conversion_external_source = 6;</code>
   * @return Whether the entryPointConversionExternalSource field is set.
   */
  public boolean hasEntryPointConversionExternalSource() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string entry_point_conversion_external_source = 6;</code>
   * @return The entryPointConversionExternalSource.
   */
  public java.lang.String getEntryPointConversionExternalSource() {
    java.lang.Object ref = entryPointConversionExternalSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        entryPointConversionExternalSource_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string entry_point_conversion_external_source = 6;</code>
   * @return The bytes for entryPointConversionExternalSource.
   */
  public com.google.protobuf.ByteString
      getEntryPointConversionExternalSourceBytes() {
    java.lang.Object ref = entryPointConversionExternalSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entryPointConversionExternalSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, entryPointConverstionType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, entryPointConversionSource_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, entryPointConversionApp_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt64(4, firstMessageTimeStamp_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, entryPointConversionExternalMedium_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, entryPointConversionExternalSource_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, entryPointConverstionType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, entryPointConversionSource_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, entryPointConversionApp_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, firstMessageTimeStamp_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, entryPointConversionExternalMedium_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, entryPointConversionExternalSource_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Wam.proto.WamEntryPointConversion)) {
      return super.equals(obj);
    }
    Wam.proto.WamEntryPointConversion other = (Wam.proto.WamEntryPointConversion) obj;

    if (hasEntryPointConverstionType() != other.hasEntryPointConverstionType()) return false;
    if (hasEntryPointConverstionType()) {
      if (getEntryPointConverstionType()
          != other.getEntryPointConverstionType()) return false;
    }
    if (hasEntryPointConversionSource() != other.hasEntryPointConversionSource()) return false;
    if (hasEntryPointConversionSource()) {
      if (!getEntryPointConversionSource()
          .equals(other.getEntryPointConversionSource())) return false;
    }
    if (hasEntryPointConversionApp() != other.hasEntryPointConversionApp()) return false;
    if (hasEntryPointConversionApp()) {
      if (!getEntryPointConversionApp()
          .equals(other.getEntryPointConversionApp())) return false;
    }
    if (hasFirstMessageTimeStamp() != other.hasFirstMessageTimeStamp()) return false;
    if (hasFirstMessageTimeStamp()) {
      if (getFirstMessageTimeStamp()
          != other.getFirstMessageTimeStamp()) return false;
    }
    if (hasEntryPointConversionExternalMedium() != other.hasEntryPointConversionExternalMedium()) return false;
    if (hasEntryPointConversionExternalMedium()) {
      if (!getEntryPointConversionExternalMedium()
          .equals(other.getEntryPointConversionExternalMedium())) return false;
    }
    if (hasEntryPointConversionExternalSource() != other.hasEntryPointConversionExternalSource()) return false;
    if (hasEntryPointConversionExternalSource()) {
      if (!getEntryPointConversionExternalSource()
          .equals(other.getEntryPointConversionExternalSource())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEntryPointConverstionType()) {
      hash = (37 * hash) + ENTRY_POINT_CONVERSTION_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEntryPointConverstionType());
    }
    if (hasEntryPointConversionSource()) {
      hash = (37 * hash) + ENTRY_POINT_CONVERSION_SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getEntryPointConversionSource().hashCode();
    }
    if (hasEntryPointConversionApp()) {
      hash = (37 * hash) + ENTRY_POINT_CONVERSION_APP_FIELD_NUMBER;
      hash = (53 * hash) + getEntryPointConversionApp().hashCode();
    }
    if (hasFirstMessageTimeStamp()) {
      hash = (37 * hash) + FIRST_MESSAGE_TIME_STAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFirstMessageTimeStamp());
    }
    if (hasEntryPointConversionExternalMedium()) {
      hash = (37 * hash) + ENTRY_POINT_CONVERSION_EXTERNAL_MEDIUM_FIELD_NUMBER;
      hash = (53 * hash) + getEntryPointConversionExternalMedium().hashCode();
    }
    if (hasEntryPointConversionExternalSource()) {
      hash = (37 * hash) + ENTRY_POINT_CONVERSION_EXTERNAL_SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getEntryPointConversionExternalSource().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Wam.proto.WamEntryPointConversion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEntryPointConversion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEntryPointConversion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEntryPointConversion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEntryPointConversion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEntryPointConversion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEntryPointConversion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEntryPointConversion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEntryPointConversion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEntryPointConversion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEntryPointConversion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEntryPointConversion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Wam.proto.WamEntryPointConversion prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Wam.WamEntryPointConversion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Wam.WamEntryPointConversion)
      Wam.proto.WamEntryPointConversionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Wam.proto.WamProto.internal_static_Wam_WamEntryPointConversion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Wam.proto.WamProto.internal_static_Wam_WamEntryPointConversion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Wam.proto.WamEntryPointConversion.class, Wam.proto.WamEntryPointConversion.Builder.class);
    }

    // Construct using Wam.proto.WamEntryPointConversion.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      entryPointConverstionType_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      entryPointConversionSource_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      entryPointConversionApp_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      firstMessageTimeStamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      entryPointConversionExternalMedium_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      entryPointConversionExternalSource_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Wam.proto.WamProto.internal_static_Wam_WamEntryPointConversion_descriptor;
    }

    @java.lang.Override
    public Wam.proto.WamEntryPointConversion getDefaultInstanceForType() {
      return Wam.proto.WamEntryPointConversion.getDefaultInstance();
    }

    @java.lang.Override
    public Wam.proto.WamEntryPointConversion build() {
      Wam.proto.WamEntryPointConversion result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Wam.proto.WamEntryPointConversion buildPartial() {
      Wam.proto.WamEntryPointConversion result = new Wam.proto.WamEntryPointConversion(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.entryPointConverstionType_ = entryPointConverstionType_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.entryPointConversionSource_ = entryPointConversionSource_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.entryPointConversionApp_ = entryPointConversionApp_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.firstMessageTimeStamp_ = firstMessageTimeStamp_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.entryPointConversionExternalMedium_ = entryPointConversionExternalMedium_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.entryPointConversionExternalSource_ = entryPointConversionExternalSource_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Wam.proto.WamEntryPointConversion) {
        return mergeFrom((Wam.proto.WamEntryPointConversion)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Wam.proto.WamEntryPointConversion other) {
      if (other == Wam.proto.WamEntryPointConversion.getDefaultInstance()) return this;
      if (other.hasEntryPointConverstionType()) {
        setEntryPointConverstionType(other.getEntryPointConverstionType());
      }
      if (other.hasEntryPointConversionSource()) {
        bitField0_ |= 0x00000002;
        entryPointConversionSource_ = other.entryPointConversionSource_;
        onChanged();
      }
      if (other.hasEntryPointConversionApp()) {
        bitField0_ |= 0x00000004;
        entryPointConversionApp_ = other.entryPointConversionApp_;
        onChanged();
      }
      if (other.hasFirstMessageTimeStamp()) {
        setFirstMessageTimeStamp(other.getFirstMessageTimeStamp());
      }
      if (other.hasEntryPointConversionExternalMedium()) {
        bitField0_ |= 0x00000010;
        entryPointConversionExternalMedium_ = other.entryPointConversionExternalMedium_;
        onChanged();
      }
      if (other.hasEntryPointConversionExternalSource()) {
        bitField0_ |= 0x00000020;
        entryPointConversionExternalSource_ = other.entryPointConversionExternalSource_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Wam.proto.WamEntryPointConversion parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Wam.proto.WamEntryPointConversion) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long entryPointConverstionType_ ;
    /**
     * <code>optional int64 entry_point_converstion_type = 1;</code>
     * @return Whether the entryPointConverstionType field is set.
     */
    public boolean hasEntryPointConverstionType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 entry_point_converstion_type = 1;</code>
     * @return The entryPointConverstionType.
     */
    public long getEntryPointConverstionType() {
      return entryPointConverstionType_;
    }
    /**
     * <code>optional int64 entry_point_converstion_type = 1;</code>
     * @param value The entryPointConverstionType to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConverstionType(long value) {
      bitField0_ |= 0x00000001;
      entryPointConverstionType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 entry_point_converstion_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntryPointConverstionType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      entryPointConverstionType_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object entryPointConversionSource_ = "";
    /**
     * <code>optional string entry_point_conversion_source = 2;</code>
     * @return Whether the entryPointConversionSource field is set.
     */
    public boolean hasEntryPointConversionSource() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string entry_point_conversion_source = 2;</code>
     * @return The entryPointConversionSource.
     */
    public java.lang.String getEntryPointConversionSource() {
      java.lang.Object ref = entryPointConversionSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entryPointConversionSource_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_source = 2;</code>
     * @return The bytes for entryPointConversionSource.
     */
    public com.google.protobuf.ByteString
        getEntryPointConversionSourceBytes() {
      java.lang.Object ref = entryPointConversionSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entryPointConversionSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_source = 2;</code>
     * @param value The entryPointConversionSource to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      entryPointConversionSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_source = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntryPointConversionSource() {
      bitField0_ = (bitField0_ & ~0x00000002);
      entryPointConversionSource_ = getDefaultInstance().getEntryPointConversionSource();
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_source = 2;</code>
     * @param value The bytes for entryPointConversionSource to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      entryPointConversionSource_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object entryPointConversionApp_ = "";
    /**
     * <code>optional string entry_point_conversion_app = 3;</code>
     * @return Whether the entryPointConversionApp field is set.
     */
    public boolean hasEntryPointConversionApp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string entry_point_conversion_app = 3;</code>
     * @return The entryPointConversionApp.
     */
    public java.lang.String getEntryPointConversionApp() {
      java.lang.Object ref = entryPointConversionApp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entryPointConversionApp_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_app = 3;</code>
     * @return The bytes for entryPointConversionApp.
     */
    public com.google.protobuf.ByteString
        getEntryPointConversionAppBytes() {
      java.lang.Object ref = entryPointConversionApp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entryPointConversionApp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_app = 3;</code>
     * @param value The entryPointConversionApp to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionApp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      entryPointConversionApp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_app = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntryPointConversionApp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      entryPointConversionApp_ = getDefaultInstance().getEntryPointConversionApp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_app = 3;</code>
     * @param value The bytes for entryPointConversionApp to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionAppBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      entryPointConversionApp_ = value;
      onChanged();
      return this;
    }

    private long firstMessageTimeStamp_ ;
    /**
     * <code>optional int64 first_message_time_stamp = 4;</code>
     * @return Whether the firstMessageTimeStamp field is set.
     */
    public boolean hasFirstMessageTimeStamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int64 first_message_time_stamp = 4;</code>
     * @return The firstMessageTimeStamp.
     */
    public long getFirstMessageTimeStamp() {
      return firstMessageTimeStamp_;
    }
    /**
     * <code>optional int64 first_message_time_stamp = 4;</code>
     * @param value The firstMessageTimeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setFirstMessageTimeStamp(long value) {
      bitField0_ |= 0x00000008;
      firstMessageTimeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 first_message_time_stamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstMessageTimeStamp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      firstMessageTimeStamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object entryPointConversionExternalMedium_ = "";
    /**
     * <code>optional string entry_point_conversion_external_medium = 5;</code>
     * @return Whether the entryPointConversionExternalMedium field is set.
     */
    public boolean hasEntryPointConversionExternalMedium() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string entry_point_conversion_external_medium = 5;</code>
     * @return The entryPointConversionExternalMedium.
     */
    public java.lang.String getEntryPointConversionExternalMedium() {
      java.lang.Object ref = entryPointConversionExternalMedium_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entryPointConversionExternalMedium_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_external_medium = 5;</code>
     * @return The bytes for entryPointConversionExternalMedium.
     */
    public com.google.protobuf.ByteString
        getEntryPointConversionExternalMediumBytes() {
      java.lang.Object ref = entryPointConversionExternalMedium_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entryPointConversionExternalMedium_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_external_medium = 5;</code>
     * @param value The entryPointConversionExternalMedium to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionExternalMedium(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      entryPointConversionExternalMedium_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_external_medium = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntryPointConversionExternalMedium() {
      bitField0_ = (bitField0_ & ~0x00000010);
      entryPointConversionExternalMedium_ = getDefaultInstance().getEntryPointConversionExternalMedium();
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_external_medium = 5;</code>
     * @param value The bytes for entryPointConversionExternalMedium to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionExternalMediumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      entryPointConversionExternalMedium_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object entryPointConversionExternalSource_ = "";
    /**
     * <code>optional string entry_point_conversion_external_source = 6;</code>
     * @return Whether the entryPointConversionExternalSource field is set.
     */
    public boolean hasEntryPointConversionExternalSource() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string entry_point_conversion_external_source = 6;</code>
     * @return The entryPointConversionExternalSource.
     */
    public java.lang.String getEntryPointConversionExternalSource() {
      java.lang.Object ref = entryPointConversionExternalSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entryPointConversionExternalSource_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_external_source = 6;</code>
     * @return The bytes for entryPointConversionExternalSource.
     */
    public com.google.protobuf.ByteString
        getEntryPointConversionExternalSourceBytes() {
      java.lang.Object ref = entryPointConversionExternalSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entryPointConversionExternalSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_external_source = 6;</code>
     * @param value The entryPointConversionExternalSource to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionExternalSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      entryPointConversionExternalSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_external_source = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntryPointConversionExternalSource() {
      bitField0_ = (bitField0_ & ~0x00000020);
      entryPointConversionExternalSource_ = getDefaultInstance().getEntryPointConversionExternalSource();
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_external_source = 6;</code>
     * @param value The bytes for entryPointConversionExternalSource to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionExternalSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      entryPointConversionExternalSource_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Wam.WamEntryPointConversion)
  }

  // @@protoc_insertion_point(class_scope:Wam.WamEntryPointConversion)
  private static final Wam.proto.WamEntryPointConversion DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Wam.proto.WamEntryPointConversion();
  }

  public static Wam.proto.WamEntryPointConversion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<WamEntryPointConversion>
      PARSER = new com.google.protobuf.AbstractParser<WamEntryPointConversion>() {
    @java.lang.Override
    public WamEntryPointConversion parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WamEntryPointConversion(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WamEntryPointConversion> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WamEntryPointConversion> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Wam.proto.WamEntryPointConversion getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

