// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

/**
 * Protobuf type {@code Wam.WamEventAdvPrimaryIdentityMissing}
 */
public  final class WamEventAdvPrimaryIdentityMissing extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Wam.WamEventAdvPrimaryIdentityMissing)
    WamEventAdvPrimaryIdentityMissingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WamEventAdvPrimaryIdentityMissing.newBuilder() to construct.
  private WamEventAdvPrimaryIdentityMissing(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WamEventAdvPrimaryIdentityMissing() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WamEventAdvPrimaryIdentityMissing();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WamEventAdvPrimaryIdentityMissing(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            primaryIdentityMissingProtoTypeNumber_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Wam.proto.WamProto.internal_static_Wam_WamEventAdvPrimaryIdentityMissing_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Wam.proto.WamProto.internal_static_Wam_WamEventAdvPrimaryIdentityMissing_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Wam.proto.WamEventAdvPrimaryIdentityMissing.class, Wam.proto.WamEventAdvPrimaryIdentityMissing.Builder.class);
  }

  private int bitField0_;
  public static final int PRIMARY_IDENTITY_MISSING_PROTO_TYPE_NUMBER_FIELD_NUMBER = 1;
  private long primaryIdentityMissingProtoTypeNumber_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 primary_identity_missing_proto_type_number = 1;</code>
   * @return Whether the primaryIdentityMissingProtoTypeNumber field is set.
   */
  public boolean hasPrimaryIdentityMissingProtoTypeNumber() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 primary_identity_missing_proto_type_number = 1;</code>
   * @return The primaryIdentityMissingProtoTypeNumber.
   */
  public long getPrimaryIdentityMissingProtoTypeNumber() {
    return primaryIdentityMissingProtoTypeNumber_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, primaryIdentityMissingProtoTypeNumber_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, primaryIdentityMissingProtoTypeNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Wam.proto.WamEventAdvPrimaryIdentityMissing)) {
      return super.equals(obj);
    }
    Wam.proto.WamEventAdvPrimaryIdentityMissing other = (Wam.proto.WamEventAdvPrimaryIdentityMissing) obj;

    if (hasPrimaryIdentityMissingProtoTypeNumber() != other.hasPrimaryIdentityMissingProtoTypeNumber()) return false;
    if (hasPrimaryIdentityMissingProtoTypeNumber()) {
      if (getPrimaryIdentityMissingProtoTypeNumber()
          != other.getPrimaryIdentityMissingProtoTypeNumber()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPrimaryIdentityMissingProtoTypeNumber()) {
      hash = (37 * hash) + PRIMARY_IDENTITY_MISSING_PROTO_TYPE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrimaryIdentityMissingProtoTypeNumber());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventAdvPrimaryIdentityMissing parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Wam.proto.WamEventAdvPrimaryIdentityMissing prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Wam.WamEventAdvPrimaryIdentityMissing}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Wam.WamEventAdvPrimaryIdentityMissing)
      Wam.proto.WamEventAdvPrimaryIdentityMissingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventAdvPrimaryIdentityMissing_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventAdvPrimaryIdentityMissing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Wam.proto.WamEventAdvPrimaryIdentityMissing.class, Wam.proto.WamEventAdvPrimaryIdentityMissing.Builder.class);
    }

    // Construct using Wam.proto.WamEventAdvPrimaryIdentityMissing.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      primaryIdentityMissingProtoTypeNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventAdvPrimaryIdentityMissing_descriptor;
    }

    @java.lang.Override
    public Wam.proto.WamEventAdvPrimaryIdentityMissing getDefaultInstanceForType() {
      return Wam.proto.WamEventAdvPrimaryIdentityMissing.getDefaultInstance();
    }

    @java.lang.Override
    public Wam.proto.WamEventAdvPrimaryIdentityMissing build() {
      Wam.proto.WamEventAdvPrimaryIdentityMissing result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Wam.proto.WamEventAdvPrimaryIdentityMissing buildPartial() {
      Wam.proto.WamEventAdvPrimaryIdentityMissing result = new Wam.proto.WamEventAdvPrimaryIdentityMissing(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.primaryIdentityMissingProtoTypeNumber_ = primaryIdentityMissingProtoTypeNumber_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Wam.proto.WamEventAdvPrimaryIdentityMissing) {
        return mergeFrom((Wam.proto.WamEventAdvPrimaryIdentityMissing)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Wam.proto.WamEventAdvPrimaryIdentityMissing other) {
      if (other == Wam.proto.WamEventAdvPrimaryIdentityMissing.getDefaultInstance()) return this;
      if (other.hasPrimaryIdentityMissingProtoTypeNumber()) {
        setPrimaryIdentityMissingProtoTypeNumber(other.getPrimaryIdentityMissingProtoTypeNumber());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Wam.proto.WamEventAdvPrimaryIdentityMissing parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Wam.proto.WamEventAdvPrimaryIdentityMissing) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long primaryIdentityMissingProtoTypeNumber_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 primary_identity_missing_proto_type_number = 1;</code>
     * @return Whether the primaryIdentityMissingProtoTypeNumber field is set.
     */
    public boolean hasPrimaryIdentityMissingProtoTypeNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 primary_identity_missing_proto_type_number = 1;</code>
     * @return The primaryIdentityMissingProtoTypeNumber.
     */
    public long getPrimaryIdentityMissingProtoTypeNumber() {
      return primaryIdentityMissingProtoTypeNumber_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 primary_identity_missing_proto_type_number = 1;</code>
     * @param value The primaryIdentityMissingProtoTypeNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPrimaryIdentityMissingProtoTypeNumber(long value) {
      bitField0_ |= 0x00000001;
      primaryIdentityMissingProtoTypeNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 primary_identity_missing_proto_type_number = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrimaryIdentityMissingProtoTypeNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      primaryIdentityMissingProtoTypeNumber_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Wam.WamEventAdvPrimaryIdentityMissing)
  }

  // @@protoc_insertion_point(class_scope:Wam.WamEventAdvPrimaryIdentityMissing)
  private static final Wam.proto.WamEventAdvPrimaryIdentityMissing DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Wam.proto.WamEventAdvPrimaryIdentityMissing();
  }

  public static Wam.proto.WamEventAdvPrimaryIdentityMissing getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<WamEventAdvPrimaryIdentityMissing>
      PARSER = new com.google.protobuf.AbstractParser<WamEventAdvPrimaryIdentityMissing>() {
    @java.lang.Override
    public WamEventAdvPrimaryIdentityMissing parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WamEventAdvPrimaryIdentityMissing(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WamEventAdvPrimaryIdentityMissing> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WamEventAdvPrimaryIdentityMissing> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Wam.proto.WamEventAdvPrimaryIdentityMissing getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

