// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventQbmIncomingMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventQbmIncomingMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 api_daily_thread_count_7d = 21;</code>
   * @return Whether the apiDailyThreadCount7d field is set.
   */
  boolean hasApiDailyThreadCount7D();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 api_daily_thread_count_7d = 21;</code>
   * @return The apiDailyThreadCount7d.
   */
  long getApiDailyThreadCount7D();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 api_message_count_1d = 22;</code>
   * @return Whether the apiMessageCount1d field is set.
   */
  boolean hasApiMessageCount1D();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 api_message_count_1d = 22;</code>
   * @return The apiMessageCount1d.
   */
  long getApiMessageCount1D();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 api_message_count_7d = 23;</code>
   * @return Whether the apiMessageCount7d field is set.
   */
  boolean hasApiMessageCount7D();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 api_message_count_7d = 23;</code>
   * @return The apiMessageCount7d.
   */
  long getApiMessageCount7D();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 api_unique_thread_count_7d = 25;</code>
   * @return Whether the apiUniqueThreadCount7d field is set.
   */
  boolean hasApiUniqueThreadCount7D();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 api_unique_thread_count_7d = 25;</code>
   * @return The apiUniqueThreadCount7d.
   */
  long getApiUniqueThreadCount7D();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 chats_folder_type_number = 1;</code>
   * @return Whether the chatsFolderTypeNumber field is set.
   */
  boolean hasChatsFolderTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 chats_folder_type_number = 1;</code>
   * @return The chatsFolderTypeNumber.
   */
  long getChatsFolderTypeNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 companion_devices = 10;</code>
   * @return Whether the companionDevices field is set.
   */
  boolean hasCompanionDevices();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 companion_devices = 10;</code>
   * @return The companionDevices.
   */
  long getCompanionDevices();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 contact_type_number = 2;</code>
   * @return Whether the contactTypeNumber field is set.
   */
  boolean hasContactTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 contact_type_number = 2;</code>
   * @return The contactTypeNumber.
   */
  long getContactTypeNumber();

  /**
   * <code>optional string hsm_tag_str = 14;</code>
   * @return Whether the hsmTagStr field is set.
   */
  boolean hasHsmTagStr();
  /**
   * <code>optional string hsm_tag_str = 14;</code>
   * @return The hsmTagStr.
   */
  java.lang.String getHsmTagStr();
  /**
   * <code>optional string hsm_tag_str = 14;</code>
   * @return The bytes for hsmTagStr.
   */
  com.google.protobuf.ByteString
      getHsmTagStrBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_from_ads_manager_mm = 15;</code>
   * @return Whether the isFromAdsManagerMm field is set.
   */
  boolean hasIsFromAdsManagerMm();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_from_ads_manager_mm = 15;</code>
   * @return The isFromAdsManagerMm.
   */
  long getIsFromAdsManagerMm();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_from_capi = 16;</code>
   * @return Whether the isFromCapi field is set.
   */
  boolean hasIsFromCapi();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_from_capi = 16;</code>
   * @return The isFromCapi.
   */
  long getIsFromCapi();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_muted = 20;</code>
   * @return Whether the isMuted field is set.
   */
  boolean hasIsMuted();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_muted = 20;</code>
   * @return The isMuted.
   */
  long getIsMuted();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 last_outgoing_message_delta_time_received = 13;</code>
   * @return Whether the lastOutgoingMessageDeltaTimeReceived field is set.
   */
  boolean hasLastOutgoingMessageDeltaTimeReceived();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 last_outgoing_message_delta_time_received = 13;</code>
   * @return The lastOutgoingMessageDeltaTimeReceived.
   */
  long getLastOutgoingMessageDeltaTimeReceived();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_has_button = 18;</code>
   * @return Whether the messageHasButton field is set.
   */
  boolean hasMessageHasButton();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_has_button = 18;</code>
   * @return The messageHasButton.
   */
  long getMessageHasButton();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_has_url = 19;</code>
   * @return Whether the messageHasUrl field is set.
   */
  boolean hasMessageHasUrl();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 message_has_url = 19;</code>
   * @return The messageHasUrl.
   */
  long getMessageHasUrl();

  /**
   * <code>optional string message_id_hmac = 17;</code>
   * @return Whether the messageIdHmac field is set.
   */
  boolean hasMessageIdHmac();
  /**
   * <code>optional string message_id_hmac = 17;</code>
   * @return The messageIdHmac.
   */
  java.lang.String getMessageIdHmac();
  /**
   * <code>optional string message_id_hmac = 17;</code>
   * @return The bytes for messageIdHmac.
   */
  com.google.protobuf.ByteString
      getMessageIdHmacBytes();

  /**
   * <code>optional string message_type_str = 7;</code>
   * @return Whether the messageTypeStr field is set.
   */
  boolean hasMessageTypeStr();
  /**
   * <code>optional string message_type_str = 7;</code>
   * @return The messageTypeStr.
   */
  java.lang.String getMessageTypeStr();
  /**
   * <code>optional string message_type_str = 7;</code>
   * @return The bytes for messageTypeStr.
   */
  com.google.protobuf.ByteString
      getMessageTypeStrBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 muted = 4;</code>
   * @return Whether the muted field is set.
   */
  boolean hasMuted();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 muted = 4;</code>
   * @return The muted.
   */
  long getMuted();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 notification_enabled = 5;</code>
   * @return Whether the notificationEnabled field is set.
   */
  boolean hasNotificationEnabled();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 notification_enabled = 5;</code>
   * @return The notificationEnabled.
   */
  long getNotificationEnabled();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 qbm_flag_number = 6;</code>
   * @return Whether the qbmFlagNumber field is set.
   */
  boolean hasQbmFlagNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 qbm_flag_number = 6;</code>
   * @return The qbmFlagNumber.
   */
  long getQbmFlagNumber();

  /**
   * <code>optional string qbm_flag_str = 12;</code>
   * @return Whether the qbmFlagStr field is set.
   */
  boolean hasQbmFlagStr();
  /**
   * <code>optional string qbm_flag_str = 12;</code>
   * @return The qbmFlagStr.
   */
  java.lang.String getQbmFlagStr();
  /**
   * <code>optional string qbm_flag_str = 12;</code>
   * @return The bytes for qbmFlagStr.
   */
  com.google.protobuf.ByteString
      getQbmFlagStrBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 read_receipts_enabled = 9;</code>
   * @return Whether the readReceiptsEnabled field is set.
   */
  boolean hasReadReceiptsEnabled();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 read_receipts_enabled = 9;</code>
   * @return The readReceiptsEnabled.
   */
  long getReadReceiptsEnabled();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_daily_thread_count_7d = 28;</code>
   * @return Whether the smbDailyThreadCount7d field is set.
   */
  boolean hasSmbDailyThreadCount7D();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_daily_thread_count_7d = 28;</code>
   * @return The smbDailyThreadCount7d.
   */
  long getSmbDailyThreadCount7D();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_message_count_1d = 29;</code>
   * @return Whether the smbMessageCount1d field is set.
   */
  boolean hasSmbMessageCount1D();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_message_count_1d = 29;</code>
   * @return The smbMessageCount1d.
   */
  long getSmbMessageCount1D();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_message_count_7d = 30;</code>
   * @return Whether the smbMessageCount7d field is set.
   */
  boolean hasSmbMessageCount7D();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_message_count_7d = 30;</code>
   * @return The smbMessageCount7d.
   */
  long getSmbMessageCount7D();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_total_message_count = 31;</code>
   * @return Whether the smbTotalMessageCount field is set.
   */
  boolean hasSmbTotalMessageCount();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_total_message_count = 31;</code>
   * @return The smbTotalMessageCount.
   */
  long getSmbTotalMessageCount();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_total_new_thread_count = 32;</code>
   * @return Whether the smbTotalNewThreadCount field is set.
   */
  boolean hasSmbTotalNewThreadCount();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_total_new_thread_count = 32;</code>
   * @return The smbTotalNewThreadCount.
   */
  long getSmbTotalNewThreadCount();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_unique_thread_count_1d = 33;</code>
   * @return Whether the smbUniqueThreadCount1d field is set.
   */
  boolean hasSmbUniqueThreadCount1D();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_unique_thread_count_1d = 33;</code>
   * @return The smbUniqueThreadCount1d.
   */
  long getSmbUniqueThreadCount1D();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_unique_thread_count_7d = 34;</code>
   * @return Whether the smbUniqueThreadCount7d field is set.
   */
  boolean hasSmbUniqueThreadCount7D();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_unique_thread_count_7d = 34;</code>
   * @return The smbUniqueThreadCount7d.
   */
  long getSmbUniqueThreadCount7D();

  /**
   * <code>optional string thread_id_hmac = 8;</code>
   * @return Whether the threadIdHmac field is set.
   */
  boolean hasThreadIdHmac();
  /**
   * <code>optional string thread_id_hmac = 8;</code>
   * @return The threadIdHmac.
   */
  java.lang.String getThreadIdHmac();
  /**
   * <code>optional string thread_id_hmac = 8;</code>
   * @return The bytes for threadIdHmac.
   */
  com.google.protobuf.ByteString
      getThreadIdHmacBytes();

  /**
   * <code>optional int64 keepChatsArchivedEnabled = 3;</code>
   * @return Whether the keepChatsArchivedEnabled field is set.
   */
  boolean hasKeepChatsArchivedEnabled();
  /**
   * <code>optional int64 keepChatsArchivedEnabled = 3;</code>
   * @return The keepChatsArchivedEnabled.
   */
  long getKeepChatsArchivedEnabled();

  /**
   * <code>optional int64 lastOutgoingMessageDeltaTime = 11;</code>
   * @return Whether the lastOutgoingMessageDeltaTime field is set.
   */
  boolean hasLastOutgoingMessageDeltaTime();
  /**
   * <code>optional int64 lastOutgoingMessageDeltaTime = 11;</code>
   * @return The lastOutgoingMessageDeltaTime.
   */
  long getLastOutgoingMessageDeltaTime();

  /**
   * <code>optional int64 threadCreationTime = 35;</code>
   * @return Whether the threadCreationTime field is set.
   */
  boolean hasThreadCreationTime();
  /**
   * <code>optional int64 threadCreationTime = 35;</code>
   * @return The threadCreationTime.
   */
  long getThreadCreationTime();
}
