// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

/**
 * Protobuf type {@code Wam.WamEventProfilePicDownload}
 */
public  final class WamEventProfilePicDownload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Wam.WamEventProfilePicDownload)
    WamEventProfilePicDownloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WamEventProfilePicDownload.newBuilder() to construct.
  private WamEventProfilePicDownload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WamEventProfilePicDownload() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WamEventProfilePicDownload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WamEventProfilePicDownload(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000002;
            profilePicDownloadResultNumber_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000010;
            profilePicTypeNumber_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000008;
            profilePicDownloadT_ = input.readInt64();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000004;
            profilePicDownloadSize_ = input.readInt64();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000001;
            profilePicDownloadHttpCode_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Wam.proto.WamProto.internal_static_Wam_WamEventProfilePicDownload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Wam.proto.WamProto.internal_static_Wam_WamEventProfilePicDownload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Wam.proto.WamEventProfilePicDownload.class, Wam.proto.WamEventProfilePicDownload.Builder.class);
  }

  private int bitField0_;
  public static final int PROFILE_PIC_DOWNLOAD_HTTP_CODE_FIELD_NUMBER = 5;
  private long profilePicDownloadHttpCode_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 profile_pic_download_http_code = 5;</code>
   * @return Whether the profilePicDownloadHttpCode field is set.
   */
  public boolean hasProfilePicDownloadHttpCode() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 profile_pic_download_http_code = 5;</code>
   * @return The profilePicDownloadHttpCode.
   */
  public long getProfilePicDownloadHttpCode() {
    return profilePicDownloadHttpCode_;
  }

  public static final int PROFILE_PIC_DOWNLOAD_RESULT_NUMBER_FIELD_NUMBER = 1;
  private long profilePicDownloadResultNumber_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 profile_pic_download_result_number = 1;</code>
   * @return Whether the profilePicDownloadResultNumber field is set.
   */
  public boolean hasProfilePicDownloadResultNumber() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 profile_pic_download_result_number = 1;</code>
   * @return The profilePicDownloadResultNumber.
   */
  public long getProfilePicDownloadResultNumber() {
    return profilePicDownloadResultNumber_;
  }

  public static final int PROFILE_PIC_DOWNLOAD_SIZE_FIELD_NUMBER = 4;
  private long profilePicDownloadSize_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 profile_pic_download_size = 4;</code>
   * @return Whether the profilePicDownloadSize field is set.
   */
  public boolean hasProfilePicDownloadSize() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 profile_pic_download_size = 4;</code>
   * @return The profilePicDownloadSize.
   */
  public long getProfilePicDownloadSize() {
    return profilePicDownloadSize_;
  }

  public static final int PROFILE_PIC_DOWNLOAD_T_FIELD_NUMBER = 3;
  private long profilePicDownloadT_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 profile_pic_download_t = 3;</code>
   * @return Whether the profilePicDownloadT field is set.
   */
  public boolean hasProfilePicDownloadT() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 profile_pic_download_t = 3;</code>
   * @return The profilePicDownloadT.
   */
  public long getProfilePicDownloadT() {
    return profilePicDownloadT_;
  }

  public static final int PROFILE_PIC_TYPE_NUMBER_FIELD_NUMBER = 2;
  private long profilePicTypeNumber_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 profile_pic_type_number = 2;</code>
   * @return Whether the profilePicTypeNumber field is set.
   */
  public boolean hasProfilePicTypeNumber() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 profile_pic_type_number = 2;</code>
   * @return The profilePicTypeNumber.
   */
  public long getProfilePicTypeNumber() {
    return profilePicTypeNumber_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(1, profilePicDownloadResultNumber_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt64(2, profilePicTypeNumber_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt64(3, profilePicDownloadT_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(4, profilePicDownloadSize_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(5, profilePicDownloadHttpCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, profilePicDownloadResultNumber_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, profilePicTypeNumber_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, profilePicDownloadT_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, profilePicDownloadSize_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, profilePicDownloadHttpCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Wam.proto.WamEventProfilePicDownload)) {
      return super.equals(obj);
    }
    Wam.proto.WamEventProfilePicDownload other = (Wam.proto.WamEventProfilePicDownload) obj;

    if (hasProfilePicDownloadHttpCode() != other.hasProfilePicDownloadHttpCode()) return false;
    if (hasProfilePicDownloadHttpCode()) {
      if (getProfilePicDownloadHttpCode()
          != other.getProfilePicDownloadHttpCode()) return false;
    }
    if (hasProfilePicDownloadResultNumber() != other.hasProfilePicDownloadResultNumber()) return false;
    if (hasProfilePicDownloadResultNumber()) {
      if (getProfilePicDownloadResultNumber()
          != other.getProfilePicDownloadResultNumber()) return false;
    }
    if (hasProfilePicDownloadSize() != other.hasProfilePicDownloadSize()) return false;
    if (hasProfilePicDownloadSize()) {
      if (getProfilePicDownloadSize()
          != other.getProfilePicDownloadSize()) return false;
    }
    if (hasProfilePicDownloadT() != other.hasProfilePicDownloadT()) return false;
    if (hasProfilePicDownloadT()) {
      if (getProfilePicDownloadT()
          != other.getProfilePicDownloadT()) return false;
    }
    if (hasProfilePicTypeNumber() != other.hasProfilePicTypeNumber()) return false;
    if (hasProfilePicTypeNumber()) {
      if (getProfilePicTypeNumber()
          != other.getProfilePicTypeNumber()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProfilePicDownloadHttpCode()) {
      hash = (37 * hash) + PROFILE_PIC_DOWNLOAD_HTTP_CODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProfilePicDownloadHttpCode());
    }
    if (hasProfilePicDownloadResultNumber()) {
      hash = (37 * hash) + PROFILE_PIC_DOWNLOAD_RESULT_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProfilePicDownloadResultNumber());
    }
    if (hasProfilePicDownloadSize()) {
      hash = (37 * hash) + PROFILE_PIC_DOWNLOAD_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProfilePicDownloadSize());
    }
    if (hasProfilePicDownloadT()) {
      hash = (37 * hash) + PROFILE_PIC_DOWNLOAD_T_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProfilePicDownloadT());
    }
    if (hasProfilePicTypeNumber()) {
      hash = (37 * hash) + PROFILE_PIC_TYPE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProfilePicTypeNumber());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Wam.proto.WamEventProfilePicDownload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventProfilePicDownload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventProfilePicDownload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventProfilePicDownload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventProfilePicDownload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventProfilePicDownload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventProfilePicDownload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventProfilePicDownload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEventProfilePicDownload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventProfilePicDownload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEventProfilePicDownload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventProfilePicDownload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Wam.proto.WamEventProfilePicDownload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Wam.WamEventProfilePicDownload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Wam.WamEventProfilePicDownload)
      Wam.proto.WamEventProfilePicDownloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventProfilePicDownload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventProfilePicDownload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Wam.proto.WamEventProfilePicDownload.class, Wam.proto.WamEventProfilePicDownload.Builder.class);
    }

    // Construct using Wam.proto.WamEventProfilePicDownload.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      profilePicDownloadHttpCode_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      profilePicDownloadResultNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      profilePicDownloadSize_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      profilePicDownloadT_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      profilePicTypeNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventProfilePicDownload_descriptor;
    }

    @java.lang.Override
    public Wam.proto.WamEventProfilePicDownload getDefaultInstanceForType() {
      return Wam.proto.WamEventProfilePicDownload.getDefaultInstance();
    }

    @java.lang.Override
    public Wam.proto.WamEventProfilePicDownload build() {
      Wam.proto.WamEventProfilePicDownload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Wam.proto.WamEventProfilePicDownload buildPartial() {
      Wam.proto.WamEventProfilePicDownload result = new Wam.proto.WamEventProfilePicDownload(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.profilePicDownloadHttpCode_ = profilePicDownloadHttpCode_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.profilePicDownloadResultNumber_ = profilePicDownloadResultNumber_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.profilePicDownloadSize_ = profilePicDownloadSize_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.profilePicDownloadT_ = profilePicDownloadT_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.profilePicTypeNumber_ = profilePicTypeNumber_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Wam.proto.WamEventProfilePicDownload) {
        return mergeFrom((Wam.proto.WamEventProfilePicDownload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Wam.proto.WamEventProfilePicDownload other) {
      if (other == Wam.proto.WamEventProfilePicDownload.getDefaultInstance()) return this;
      if (other.hasProfilePicDownloadHttpCode()) {
        setProfilePicDownloadHttpCode(other.getProfilePicDownloadHttpCode());
      }
      if (other.hasProfilePicDownloadResultNumber()) {
        setProfilePicDownloadResultNumber(other.getProfilePicDownloadResultNumber());
      }
      if (other.hasProfilePicDownloadSize()) {
        setProfilePicDownloadSize(other.getProfilePicDownloadSize());
      }
      if (other.hasProfilePicDownloadT()) {
        setProfilePicDownloadT(other.getProfilePicDownloadT());
      }
      if (other.hasProfilePicTypeNumber()) {
        setProfilePicTypeNumber(other.getProfilePicTypeNumber());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Wam.proto.WamEventProfilePicDownload parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Wam.proto.WamEventProfilePicDownload) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long profilePicDownloadHttpCode_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_http_code = 5;</code>
     * @return Whether the profilePicDownloadHttpCode field is set.
     */
    public boolean hasProfilePicDownloadHttpCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_http_code = 5;</code>
     * @return The profilePicDownloadHttpCode.
     */
    public long getProfilePicDownloadHttpCode() {
      return profilePicDownloadHttpCode_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_http_code = 5;</code>
     * @param value The profilePicDownloadHttpCode to set.
     * @return This builder for chaining.
     */
    public Builder setProfilePicDownloadHttpCode(long value) {
      bitField0_ |= 0x00000001;
      profilePicDownloadHttpCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_http_code = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfilePicDownloadHttpCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      profilePicDownloadHttpCode_ = 0L;
      onChanged();
      return this;
    }

    private long profilePicDownloadResultNumber_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_result_number = 1;</code>
     * @return Whether the profilePicDownloadResultNumber field is set.
     */
    public boolean hasProfilePicDownloadResultNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_result_number = 1;</code>
     * @return The profilePicDownloadResultNumber.
     */
    public long getProfilePicDownloadResultNumber() {
      return profilePicDownloadResultNumber_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_result_number = 1;</code>
     * @param value The profilePicDownloadResultNumber to set.
     * @return This builder for chaining.
     */
    public Builder setProfilePicDownloadResultNumber(long value) {
      bitField0_ |= 0x00000002;
      profilePicDownloadResultNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_result_number = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfilePicDownloadResultNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      profilePicDownloadResultNumber_ = 0L;
      onChanged();
      return this;
    }

    private long profilePicDownloadSize_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_size = 4;</code>
     * @return Whether the profilePicDownloadSize field is set.
     */
    public boolean hasProfilePicDownloadSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_size = 4;</code>
     * @return The profilePicDownloadSize.
     */
    public long getProfilePicDownloadSize() {
      return profilePicDownloadSize_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_size = 4;</code>
     * @param value The profilePicDownloadSize to set.
     * @return This builder for chaining.
     */
    public Builder setProfilePicDownloadSize(long value) {
      bitField0_ |= 0x00000004;
      profilePicDownloadSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_size = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfilePicDownloadSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      profilePicDownloadSize_ = 0L;
      onChanged();
      return this;
    }

    private long profilePicDownloadT_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_t = 3;</code>
     * @return Whether the profilePicDownloadT field is set.
     */
    public boolean hasProfilePicDownloadT() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_t = 3;</code>
     * @return The profilePicDownloadT.
     */
    public long getProfilePicDownloadT() {
      return profilePicDownloadT_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_t = 3;</code>
     * @param value The profilePicDownloadT to set.
     * @return This builder for chaining.
     */
    public Builder setProfilePicDownloadT(long value) {
      bitField0_ |= 0x00000008;
      profilePicDownloadT_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_download_t = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfilePicDownloadT() {
      bitField0_ = (bitField0_ & ~0x00000008);
      profilePicDownloadT_ = 0L;
      onChanged();
      return this;
    }

    private long profilePicTypeNumber_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_type_number = 2;</code>
     * @return Whether the profilePicTypeNumber field is set.
     */
    public boolean hasProfilePicTypeNumber() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_type_number = 2;</code>
     * @return The profilePicTypeNumber.
     */
    public long getProfilePicTypeNumber() {
      return profilePicTypeNumber_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_type_number = 2;</code>
     * @param value The profilePicTypeNumber to set.
     * @return This builder for chaining.
     */
    public Builder setProfilePicTypeNumber(long value) {
      bitField0_ |= 0x00000010;
      profilePicTypeNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 profile_pic_type_number = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProfilePicTypeNumber() {
      bitField0_ = (bitField0_ & ~0x00000010);
      profilePicTypeNumber_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Wam.WamEventProfilePicDownload)
  }

  // @@protoc_insertion_point(class_scope:Wam.WamEventProfilePicDownload)
  private static final Wam.proto.WamEventProfilePicDownload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Wam.proto.WamEventProfilePicDownload();
  }

  public static Wam.proto.WamEventProfilePicDownload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<WamEventProfilePicDownload>
      PARSER = new com.google.protobuf.AbstractParser<WamEventProfilePicDownload>() {
    @java.lang.Override
    public WamEventProfilePicDownload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WamEventProfilePicDownload(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WamEventProfilePicDownload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WamEventProfilePicDownload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Wam.proto.WamEventProfilePicDownload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

