// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventTsBitArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventTsBitArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 bitarray_high = 1;</code>
   * @return Whether the bitarrayHigh field is set.
   */
  boolean hasBitarrayHigh();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 bitarray_high = 1;</code>
   * @return The bitarrayHigh.
   */
  long getBitarrayHigh();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 bitarray_length = 2;</code>
   * @return Whether the bitarrayLength field is set.
   */
  boolean hasBitarrayLength();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 bitarray_length = 2;</code>
   * @return The bitarrayLength.
   */
  long getBitarrayLength();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 bitarray_low = 3;</code>
   * @return Whether the bitarrayLow field is set.
   */
  boolean hasBitarrayLow();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 bitarray_low = 3;</code>
   * @return The bitarrayLow.
   */
  long getBitarrayLow();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 cumulative_bits = 4;</code>
   * @return Whether the cumulativeBits field is set.
   */
  boolean hasCumulativeBits();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 cumulative_bits = 4;</code>
   * @return The cumulativeBits.
   */
  long getCumulativeBits();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 relative_timestamp_ms = 5;</code>
   * @return Whether the relativeTimestampMs field is set.
   */
  boolean hasRelativeTimestampMs();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 relative_timestamp_ms = 5;</code>
   * @return The relativeTimestampMs.
   */
  long getRelativeTimestampMs();

  /**
   * <code>optional int64 session_seq = 6;</code>
   * @return Whether the sessionSeq field is set.
   */
  boolean hasSessionSeq();
  /**
   * <code>optional int64 session_seq = 6;</code>
   * @return The sessionSeq.
   */
  long getSessionSeq();

  /**
   * <code>optional int64 ts_session_id = 7;</code>
   * @return Whether the tsSessionId field is set.
   */
  boolean hasTsSessionId();
  /**
   * <code>optional int64 ts_session_id = 7;</code>
   * @return The tsSessionId.
   */
  long getTsSessionId();

  /**
   * <code>optional int64 ts_timestamp_ms = 8;</code>
   * @return Whether the tsTimestampMs field is set.
   */
  boolean hasTsTimestampMs();
  /**
   * <code>optional int64 ts_timestamp_ms = 8;</code>
   * @return The tsTimestampMs.
   */
  long getTsTimestampMs();

  /**
   * <code>optional string unified_session_id = 9;</code>
   * @return Whether the unifiedSessionId field is set.
   */
  boolean hasUnifiedSessionId();
  /**
   * <code>optional string unified_session_id = 9;</code>
   * @return The unifiedSessionId.
   */
  java.lang.String getUnifiedSessionId();
  /**
   * <code>optional string unified_session_id = 9;</code>
   * @return The bytes for unifiedSessionId.
   */
  com.google.protobuf.ByteString
      getUnifiedSessionIdBytes();
}
