// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventWamLoginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventWamLogin)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 androidKeystoreState = 10;</code>
   * @return Whether the androidKeystoreState field is set.
   */
  boolean hasAndroidKeystoreState();
  /**
   * <code>optional int64 androidKeystoreState = 10;</code>
   * @return The androidKeystoreState.
   */
  long getAndroidKeystoreState();

  /**
   * <code>optional int64 connectionOrigin = 6;</code>
   * @return Whether the connectionOrigin field is set.
   */
  boolean hasConnectionOrigin();
  /**
   * <code>optional int64 connectionOrigin = 6;</code>
   * @return The connectionOrigin.
   */
  long getConnectionOrigin();

  /**
   * <code>optional int64 connectionT = 5;</code>
   * @return Whether the connectionT field is set.
   */
  boolean hasConnectionT();
  /**
   * <code>optional int64 connectionT = 5;</code>
   * @return The connectionT.
   */
  long getConnectionT();

  /**
   * <code>optional int64 loginDnsResolver = 13;</code>
   * @return Whether the loginDnsResolver field is set.
   */
  boolean hasLoginDnsResolver();
  /**
   * <code>optional int64 loginDnsResolver = 13;</code>
   * @return The loginDnsResolver.
   */
  long getLoginDnsResolver();

  /**
   * <code>optional int64 loginIpSource = 14;</code>
   * @return Whether the loginIpSource field is set.
   */
  boolean hasLoginIpSource();
  /**
   * <code>optional int64 loginIpSource = 14;</code>
   * @return The loginIpSource.
   */
  long getLoginIpSource();

  /**
   * <code>optional int64 loginPort = 15;</code>
   * @return Whether the loginPort field is set.
   */
  boolean hasLoginPort();
  /**
   * <code>optional int64 loginPort = 15;</code>
   * @return The loginPort.
   */
  long getLoginPort();

  /**
   * <code>optional string loginResolvedPop = 19;</code>
   * @return Whether the loginResolvedPop field is set.
   */
  boolean hasLoginResolvedPop();
  /**
   * <code>optional string loginResolvedPop = 19;</code>
   * @return The loginResolvedPop.
   */
  java.lang.String getLoginResolvedPop();
  /**
   * <code>optional string loginResolvedPop = 19;</code>
   * @return The bytes for loginResolvedPop.
   */
  com.google.protobuf.ByteString
      getLoginResolvedPopBytes();

  /**
   * <code>optional int64 loginResult = 1;</code>
   * @return Whether the loginResult field is set.
   */
  boolean hasLoginResult();
  /**
   * <code>optional int64 loginResult = 1;</code>
   * @return The loginResult.
   */
  long getLoginResult();

  /**
   * <code>optional int64 loginT = 3;</code>
   * @return Whether the loginT field is set.
   */
  boolean hasLoginT();
  /**
   * <code>optional int64 loginT = 3;</code>
   * @return The loginT.
   */
  long getLoginT();

  /**
   * <code>optional int64 logoutSessionId = 18;</code>
   * @return Whether the logoutSessionId field is set.
   */
  boolean hasLogoutSessionId();
  /**
   * <code>optional int64 logoutSessionId = 18;</code>
   * @return The logoutSessionId.
   */
  long getLogoutSessionId();

  /**
   * <code>optional int64 longConnect = 4;</code>
   * @return Whether the longConnect field is set.
   */
  boolean hasLongConnect();
  /**
   * <code>optional int64 longConnect = 4;</code>
   * @return The longConnect.
   */
  long getLongConnect();

  /**
   * <code>optional int64 noiseProtocolVersion = 16;</code>
   * @return Whether the noiseProtocolVersion field is set.
   */
  boolean hasNoiseProtocolVersion();
  /**
   * <code>optional int64 noiseProtocolVersion = 16;</code>
   * @return The noiseProtocolVersion.
   */
  long getNoiseProtocolVersion();

  /**
   * <code>optional int64 passive = 8;</code>
   * @return Whether the passive field is set.
   */
  boolean hasPassive();
  /**
   * <code>optional int64 passive = 8;</code>
   * @return The passive.
   */
  long getPassive();

  /**
   * <code>optional int64 pendingAcksCount = 17;</code>
   * @return Whether the pendingAcksCount field is set.
   */
  boolean hasPendingAcksCount();
  /**
   * <code>optional int64 pendingAcksCount = 17;</code>
   * @return The pendingAcksCount.
   */
  long getPendingAcksCount();

  /**
   * <code>optional int64 retryCount = 2;</code>
   * @return Whether the retryCount field is set.
   */
  boolean hasRetryCount();
  /**
   * <code>optional int64 retryCount = 2;</code>
   * @return The retryCount.
   */
  long getRetryCount();

  /**
   * <code>optional int64 sequenceStep = 7;</code>
   * @return Whether the sequenceStep field is set.
   */
  boolean hasSequenceStep();
  /**
   * <code>optional int64 sequenceStep = 7;</code>
   * @return The sequenceStep.
   */
  long getSequenceStep();

  /**
   * <code>optional int64 serverErrorCode = 9;</code>
   * @return Whether the serverErrorCode field is set.
   */
  boolean hasServerErrorCode();
  /**
   * <code>optional int64 serverErrorCode = 9;</code>
   * @return The serverErrorCode.
   */
  long getServerErrorCode();
}
