// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

/**
 * Protobuf type {@code Wam.WamEventWamLogin}
 */
public  final class WamEventWamLogin extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Wam.WamEventWamLogin)
    WamEventWamLoginOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WamEventWamLogin.newBuilder() to construct.
  private WamEventWamLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WamEventWamLogin() {
    loginResolvedPop_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WamEventWamLogin();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WamEventWamLogin(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000080;
            loginResult_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00004000;
            retryCount_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000100;
            loginT_ = input.readInt64();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000400;
            longConnect_ = input.readInt64();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000004;
            connectionT_ = input.readInt64();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000002;
            connectionOrigin_ = input.readInt64();
            break;
          }
          case 56: {
            bitField0_ |= 0x00008000;
            sequenceStep_ = input.readInt64();
            break;
          }
          case 64: {
            bitField0_ |= 0x00001000;
            passive_ = input.readInt64();
            break;
          }
          case 72: {
            bitField0_ |= 0x00010000;
            serverErrorCode_ = input.readInt64();
            break;
          }
          case 80: {
            bitField0_ |= 0x00000001;
            androidKeystoreState_ = input.readInt64();
            break;
          }
          case 104: {
            bitField0_ |= 0x00000008;
            loginDnsResolver_ = input.readInt64();
            break;
          }
          case 112: {
            bitField0_ |= 0x00000010;
            loginIpSource_ = input.readInt64();
            break;
          }
          case 120: {
            bitField0_ |= 0x00000020;
            loginPort_ = input.readInt64();
            break;
          }
          case 128: {
            bitField0_ |= 0x00000800;
            noiseProtocolVersion_ = input.readInt64();
            break;
          }
          case 136: {
            bitField0_ |= 0x00002000;
            pendingAcksCount_ = input.readInt64();
            break;
          }
          case 144: {
            bitField0_ |= 0x00000200;
            logoutSessionId_ = input.readInt64();
            break;
          }
          case 154: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000040;
            loginResolvedPop_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Wam.proto.WamProto.internal_static_Wam_WamEventWamLogin_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Wam.proto.WamProto.internal_static_Wam_WamEventWamLogin_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Wam.proto.WamEventWamLogin.class, Wam.proto.WamEventWamLogin.Builder.class);
  }

  private int bitField0_;
  public static final int ANDROIDKEYSTORESTATE_FIELD_NUMBER = 10;
  private long androidKeystoreState_;
  /**
   * <code>optional int64 androidKeystoreState = 10;</code>
   * @return Whether the androidKeystoreState field is set.
   */
  public boolean hasAndroidKeystoreState() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int64 androidKeystoreState = 10;</code>
   * @return The androidKeystoreState.
   */
  public long getAndroidKeystoreState() {
    return androidKeystoreState_;
  }

  public static final int CONNECTIONORIGIN_FIELD_NUMBER = 6;
  private long connectionOrigin_;
  /**
   * <code>optional int64 connectionOrigin = 6;</code>
   * @return Whether the connectionOrigin field is set.
   */
  public boolean hasConnectionOrigin() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 connectionOrigin = 6;</code>
   * @return The connectionOrigin.
   */
  public long getConnectionOrigin() {
    return connectionOrigin_;
  }

  public static final int CONNECTIONT_FIELD_NUMBER = 5;
  private long connectionT_;
  /**
   * <code>optional int64 connectionT = 5;</code>
   * @return Whether the connectionT field is set.
   */
  public boolean hasConnectionT() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int64 connectionT = 5;</code>
   * @return The connectionT.
   */
  public long getConnectionT() {
    return connectionT_;
  }

  public static final int LOGINDNSRESOLVER_FIELD_NUMBER = 13;
  private long loginDnsResolver_;
  /**
   * <code>optional int64 loginDnsResolver = 13;</code>
   * @return Whether the loginDnsResolver field is set.
   */
  public boolean hasLoginDnsResolver() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int64 loginDnsResolver = 13;</code>
   * @return The loginDnsResolver.
   */
  public long getLoginDnsResolver() {
    return loginDnsResolver_;
  }

  public static final int LOGINIPSOURCE_FIELD_NUMBER = 14;
  private long loginIpSource_;
  /**
   * <code>optional int64 loginIpSource = 14;</code>
   * @return Whether the loginIpSource field is set.
   */
  public boolean hasLoginIpSource() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int64 loginIpSource = 14;</code>
   * @return The loginIpSource.
   */
  public long getLoginIpSource() {
    return loginIpSource_;
  }

  public static final int LOGINPORT_FIELD_NUMBER = 15;
  private long loginPort_;
  /**
   * <code>optional int64 loginPort = 15;</code>
   * @return Whether the loginPort field is set.
   */
  public boolean hasLoginPort() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int64 loginPort = 15;</code>
   * @return The loginPort.
   */
  public long getLoginPort() {
    return loginPort_;
  }

  public static final int LOGINRESOLVEDPOP_FIELD_NUMBER = 19;
  private volatile java.lang.Object loginResolvedPop_;
  /**
   * <code>optional string loginResolvedPop = 19;</code>
   * @return Whether the loginResolvedPop field is set.
   */
  public boolean hasLoginResolvedPop() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string loginResolvedPop = 19;</code>
   * @return The loginResolvedPop.
   */
  public java.lang.String getLoginResolvedPop() {
    java.lang.Object ref = loginResolvedPop_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        loginResolvedPop_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string loginResolvedPop = 19;</code>
   * @return The bytes for loginResolvedPop.
   */
  public com.google.protobuf.ByteString
      getLoginResolvedPopBytes() {
    java.lang.Object ref = loginResolvedPop_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      loginResolvedPop_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGINRESULT_FIELD_NUMBER = 1;
  private long loginResult_;
  /**
   * <code>optional int64 loginResult = 1;</code>
   * @return Whether the loginResult field is set.
   */
  public boolean hasLoginResult() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional int64 loginResult = 1;</code>
   * @return The loginResult.
   */
  public long getLoginResult() {
    return loginResult_;
  }

  public static final int LOGINT_FIELD_NUMBER = 3;
  private long loginT_;
  /**
   * <code>optional int64 loginT = 3;</code>
   * @return Whether the loginT field is set.
   */
  public boolean hasLoginT() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional int64 loginT = 3;</code>
   * @return The loginT.
   */
  public long getLoginT() {
    return loginT_;
  }

  public static final int LOGOUTSESSIONID_FIELD_NUMBER = 18;
  private long logoutSessionId_;
  /**
   * <code>optional int64 logoutSessionId = 18;</code>
   * @return Whether the logoutSessionId field is set.
   */
  public boolean hasLogoutSessionId() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional int64 logoutSessionId = 18;</code>
   * @return The logoutSessionId.
   */
  public long getLogoutSessionId() {
    return logoutSessionId_;
  }

  public static final int LONGCONNECT_FIELD_NUMBER = 4;
  private long longConnect_;
  /**
   * <code>optional int64 longConnect = 4;</code>
   * @return Whether the longConnect field is set.
   */
  public boolean hasLongConnect() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>optional int64 longConnect = 4;</code>
   * @return The longConnect.
   */
  public long getLongConnect() {
    return longConnect_;
  }

  public static final int NOISEPROTOCOLVERSION_FIELD_NUMBER = 16;
  private long noiseProtocolVersion_;
  /**
   * <code>optional int64 noiseProtocolVersion = 16;</code>
   * @return Whether the noiseProtocolVersion field is set.
   */
  public boolean hasNoiseProtocolVersion() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <code>optional int64 noiseProtocolVersion = 16;</code>
   * @return The noiseProtocolVersion.
   */
  public long getNoiseProtocolVersion() {
    return noiseProtocolVersion_;
  }

  public static final int PASSIVE_FIELD_NUMBER = 8;
  private long passive_;
  /**
   * <code>optional int64 passive = 8;</code>
   * @return Whether the passive field is set.
   */
  public boolean hasPassive() {
    return ((bitField0_ & 0x00001000) != 0);
  }
  /**
   * <code>optional int64 passive = 8;</code>
   * @return The passive.
   */
  public long getPassive() {
    return passive_;
  }

  public static final int PENDINGACKSCOUNT_FIELD_NUMBER = 17;
  private long pendingAcksCount_;
  /**
   * <code>optional int64 pendingAcksCount = 17;</code>
   * @return Whether the pendingAcksCount field is set.
   */
  public boolean hasPendingAcksCount() {
    return ((bitField0_ & 0x00002000) != 0);
  }
  /**
   * <code>optional int64 pendingAcksCount = 17;</code>
   * @return The pendingAcksCount.
   */
  public long getPendingAcksCount() {
    return pendingAcksCount_;
  }

  public static final int RETRYCOUNT_FIELD_NUMBER = 2;
  private long retryCount_;
  /**
   * <code>optional int64 retryCount = 2;</code>
   * @return Whether the retryCount field is set.
   */
  public boolean hasRetryCount() {
    return ((bitField0_ & 0x00004000) != 0);
  }
  /**
   * <code>optional int64 retryCount = 2;</code>
   * @return The retryCount.
   */
  public long getRetryCount() {
    return retryCount_;
  }

  public static final int SEQUENCESTEP_FIELD_NUMBER = 7;
  private long sequenceStep_;
  /**
   * <code>optional int64 sequenceStep = 7;</code>
   * @return Whether the sequenceStep field is set.
   */
  public boolean hasSequenceStep() {
    return ((bitField0_ & 0x00008000) != 0);
  }
  /**
   * <code>optional int64 sequenceStep = 7;</code>
   * @return The sequenceStep.
   */
  public long getSequenceStep() {
    return sequenceStep_;
  }

  public static final int SERVERERRORCODE_FIELD_NUMBER = 9;
  private long serverErrorCode_;
  /**
   * <code>optional int64 serverErrorCode = 9;</code>
   * @return Whether the serverErrorCode field is set.
   */
  public boolean hasServerErrorCode() {
    return ((bitField0_ & 0x00010000) != 0);
  }
  /**
   * <code>optional int64 serverErrorCode = 9;</code>
   * @return The serverErrorCode.
   */
  public long getServerErrorCode() {
    return serverErrorCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeInt64(1, loginResult_);
    }
    if (((bitField0_ & 0x00004000) != 0)) {
      output.writeInt64(2, retryCount_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeInt64(3, loginT_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      output.writeInt64(4, longConnect_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(5, connectionT_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(6, connectionOrigin_);
    }
    if (((bitField0_ & 0x00008000) != 0)) {
      output.writeInt64(7, sequenceStep_);
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      output.writeInt64(8, passive_);
    }
    if (((bitField0_ & 0x00010000) != 0)) {
      output.writeInt64(9, serverErrorCode_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(10, androidKeystoreState_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt64(13, loginDnsResolver_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt64(14, loginIpSource_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt64(15, loginPort_);
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      output.writeInt64(16, noiseProtocolVersion_);
    }
    if (((bitField0_ & 0x00002000) != 0)) {
      output.writeInt64(17, pendingAcksCount_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      output.writeInt64(18, logoutSessionId_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, loginResolvedPop_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, loginResult_);
    }
    if (((bitField0_ & 0x00004000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, retryCount_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, loginT_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, longConnect_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, connectionT_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, connectionOrigin_);
    }
    if (((bitField0_ & 0x00008000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, sequenceStep_);
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, passive_);
    }
    if (((bitField0_ & 0x00010000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, serverErrorCode_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, androidKeystoreState_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, loginDnsResolver_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, loginIpSource_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(15, loginPort_);
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(16, noiseProtocolVersion_);
    }
    if (((bitField0_ & 0x00002000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(17, pendingAcksCount_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(18, logoutSessionId_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, loginResolvedPop_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Wam.proto.WamEventWamLogin)) {
      return super.equals(obj);
    }
    Wam.proto.WamEventWamLogin other = (Wam.proto.WamEventWamLogin) obj;

    if (hasAndroidKeystoreState() != other.hasAndroidKeystoreState()) return false;
    if (hasAndroidKeystoreState()) {
      if (getAndroidKeystoreState()
          != other.getAndroidKeystoreState()) return false;
    }
    if (hasConnectionOrigin() != other.hasConnectionOrigin()) return false;
    if (hasConnectionOrigin()) {
      if (getConnectionOrigin()
          != other.getConnectionOrigin()) return false;
    }
    if (hasConnectionT() != other.hasConnectionT()) return false;
    if (hasConnectionT()) {
      if (getConnectionT()
          != other.getConnectionT()) return false;
    }
    if (hasLoginDnsResolver() != other.hasLoginDnsResolver()) return false;
    if (hasLoginDnsResolver()) {
      if (getLoginDnsResolver()
          != other.getLoginDnsResolver()) return false;
    }
    if (hasLoginIpSource() != other.hasLoginIpSource()) return false;
    if (hasLoginIpSource()) {
      if (getLoginIpSource()
          != other.getLoginIpSource()) return false;
    }
    if (hasLoginPort() != other.hasLoginPort()) return false;
    if (hasLoginPort()) {
      if (getLoginPort()
          != other.getLoginPort()) return false;
    }
    if (hasLoginResolvedPop() != other.hasLoginResolvedPop()) return false;
    if (hasLoginResolvedPop()) {
      if (!getLoginResolvedPop()
          .equals(other.getLoginResolvedPop())) return false;
    }
    if (hasLoginResult() != other.hasLoginResult()) return false;
    if (hasLoginResult()) {
      if (getLoginResult()
          != other.getLoginResult()) return false;
    }
    if (hasLoginT() != other.hasLoginT()) return false;
    if (hasLoginT()) {
      if (getLoginT()
          != other.getLoginT()) return false;
    }
    if (hasLogoutSessionId() != other.hasLogoutSessionId()) return false;
    if (hasLogoutSessionId()) {
      if (getLogoutSessionId()
          != other.getLogoutSessionId()) return false;
    }
    if (hasLongConnect() != other.hasLongConnect()) return false;
    if (hasLongConnect()) {
      if (getLongConnect()
          != other.getLongConnect()) return false;
    }
    if (hasNoiseProtocolVersion() != other.hasNoiseProtocolVersion()) return false;
    if (hasNoiseProtocolVersion()) {
      if (getNoiseProtocolVersion()
          != other.getNoiseProtocolVersion()) return false;
    }
    if (hasPassive() != other.hasPassive()) return false;
    if (hasPassive()) {
      if (getPassive()
          != other.getPassive()) return false;
    }
    if (hasPendingAcksCount() != other.hasPendingAcksCount()) return false;
    if (hasPendingAcksCount()) {
      if (getPendingAcksCount()
          != other.getPendingAcksCount()) return false;
    }
    if (hasRetryCount() != other.hasRetryCount()) return false;
    if (hasRetryCount()) {
      if (getRetryCount()
          != other.getRetryCount()) return false;
    }
    if (hasSequenceStep() != other.hasSequenceStep()) return false;
    if (hasSequenceStep()) {
      if (getSequenceStep()
          != other.getSequenceStep()) return false;
    }
    if (hasServerErrorCode() != other.hasServerErrorCode()) return false;
    if (hasServerErrorCode()) {
      if (getServerErrorCode()
          != other.getServerErrorCode()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAndroidKeystoreState()) {
      hash = (37 * hash) + ANDROIDKEYSTORESTATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAndroidKeystoreState());
    }
    if (hasConnectionOrigin()) {
      hash = (37 * hash) + CONNECTIONORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getConnectionOrigin());
    }
    if (hasConnectionT()) {
      hash = (37 * hash) + CONNECTIONT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getConnectionT());
    }
    if (hasLoginDnsResolver()) {
      hash = (37 * hash) + LOGINDNSRESOLVER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLoginDnsResolver());
    }
    if (hasLoginIpSource()) {
      hash = (37 * hash) + LOGINIPSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLoginIpSource());
    }
    if (hasLoginPort()) {
      hash = (37 * hash) + LOGINPORT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLoginPort());
    }
    if (hasLoginResolvedPop()) {
      hash = (37 * hash) + LOGINRESOLVEDPOP_FIELD_NUMBER;
      hash = (53 * hash) + getLoginResolvedPop().hashCode();
    }
    if (hasLoginResult()) {
      hash = (37 * hash) + LOGINRESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLoginResult());
    }
    if (hasLoginT()) {
      hash = (37 * hash) + LOGINT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLoginT());
    }
    if (hasLogoutSessionId()) {
      hash = (37 * hash) + LOGOUTSESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLogoutSessionId());
    }
    if (hasLongConnect()) {
      hash = (37 * hash) + LONGCONNECT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongConnect());
    }
    if (hasNoiseProtocolVersion()) {
      hash = (37 * hash) + NOISEPROTOCOLVERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNoiseProtocolVersion());
    }
    if (hasPassive()) {
      hash = (37 * hash) + PASSIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPassive());
    }
    if (hasPendingAcksCount()) {
      hash = (37 * hash) + PENDINGACKSCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPendingAcksCount());
    }
    if (hasRetryCount()) {
      hash = (37 * hash) + RETRYCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRetryCount());
    }
    if (hasSequenceStep()) {
      hash = (37 * hash) + SEQUENCESTEP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSequenceStep());
    }
    if (hasServerErrorCode()) {
      hash = (37 * hash) + SERVERERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerErrorCode());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Wam.proto.WamEventWamLogin parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventWamLogin parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventWamLogin parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventWamLogin parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventWamLogin parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventWamLogin parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventWamLogin parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventWamLogin parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEventWamLogin parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventWamLogin parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEventWamLogin parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventWamLogin parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Wam.proto.WamEventWamLogin prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Wam.WamEventWamLogin}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Wam.WamEventWamLogin)
      Wam.proto.WamEventWamLoginOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventWamLogin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventWamLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Wam.proto.WamEventWamLogin.class, Wam.proto.WamEventWamLogin.Builder.class);
    }

    // Construct using Wam.proto.WamEventWamLogin.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      androidKeystoreState_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      connectionOrigin_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      connectionT_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      loginDnsResolver_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      loginIpSource_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      loginPort_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      loginResolvedPop_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      loginResult_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000080);
      loginT_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000100);
      logoutSessionId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000200);
      longConnect_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000400);
      noiseProtocolVersion_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000800);
      passive_ = 0L;
      bitField0_ = (bitField0_ & ~0x00001000);
      pendingAcksCount_ = 0L;
      bitField0_ = (bitField0_ & ~0x00002000);
      retryCount_ = 0L;
      bitField0_ = (bitField0_ & ~0x00004000);
      sequenceStep_ = 0L;
      bitField0_ = (bitField0_ & ~0x00008000);
      serverErrorCode_ = 0L;
      bitField0_ = (bitField0_ & ~0x00010000);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventWamLogin_descriptor;
    }

    @java.lang.Override
    public Wam.proto.WamEventWamLogin getDefaultInstanceForType() {
      return Wam.proto.WamEventWamLogin.getDefaultInstance();
    }

    @java.lang.Override
    public Wam.proto.WamEventWamLogin build() {
      Wam.proto.WamEventWamLogin result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Wam.proto.WamEventWamLogin buildPartial() {
      Wam.proto.WamEventWamLogin result = new Wam.proto.WamEventWamLogin(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.androidKeystoreState_ = androidKeystoreState_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.connectionOrigin_ = connectionOrigin_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.connectionT_ = connectionT_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.loginDnsResolver_ = loginDnsResolver_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.loginIpSource_ = loginIpSource_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.loginPort_ = loginPort_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.loginResolvedPop_ = loginResolvedPop_;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.loginResult_ = loginResult_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.loginT_ = loginT_;
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.logoutSessionId_ = logoutSessionId_;
        to_bitField0_ |= 0x00000200;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.longConnect_ = longConnect_;
        to_bitField0_ |= 0x00000400;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.noiseProtocolVersion_ = noiseProtocolVersion_;
        to_bitField0_ |= 0x00000800;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.passive_ = passive_;
        to_bitField0_ |= 0x00001000;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.pendingAcksCount_ = pendingAcksCount_;
        to_bitField0_ |= 0x00002000;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.retryCount_ = retryCount_;
        to_bitField0_ |= 0x00004000;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.sequenceStep_ = sequenceStep_;
        to_bitField0_ |= 0x00008000;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.serverErrorCode_ = serverErrorCode_;
        to_bitField0_ |= 0x00010000;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Wam.proto.WamEventWamLogin) {
        return mergeFrom((Wam.proto.WamEventWamLogin)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Wam.proto.WamEventWamLogin other) {
      if (other == Wam.proto.WamEventWamLogin.getDefaultInstance()) return this;
      if (other.hasAndroidKeystoreState()) {
        setAndroidKeystoreState(other.getAndroidKeystoreState());
      }
      if (other.hasConnectionOrigin()) {
        setConnectionOrigin(other.getConnectionOrigin());
      }
      if (other.hasConnectionT()) {
        setConnectionT(other.getConnectionT());
      }
      if (other.hasLoginDnsResolver()) {
        setLoginDnsResolver(other.getLoginDnsResolver());
      }
      if (other.hasLoginIpSource()) {
        setLoginIpSource(other.getLoginIpSource());
      }
      if (other.hasLoginPort()) {
        setLoginPort(other.getLoginPort());
      }
      if (other.hasLoginResolvedPop()) {
        bitField0_ |= 0x00000040;
        loginResolvedPop_ = other.loginResolvedPop_;
        onChanged();
      }
      if (other.hasLoginResult()) {
        setLoginResult(other.getLoginResult());
      }
      if (other.hasLoginT()) {
        setLoginT(other.getLoginT());
      }
      if (other.hasLogoutSessionId()) {
        setLogoutSessionId(other.getLogoutSessionId());
      }
      if (other.hasLongConnect()) {
        setLongConnect(other.getLongConnect());
      }
      if (other.hasNoiseProtocolVersion()) {
        setNoiseProtocolVersion(other.getNoiseProtocolVersion());
      }
      if (other.hasPassive()) {
        setPassive(other.getPassive());
      }
      if (other.hasPendingAcksCount()) {
        setPendingAcksCount(other.getPendingAcksCount());
      }
      if (other.hasRetryCount()) {
        setRetryCount(other.getRetryCount());
      }
      if (other.hasSequenceStep()) {
        setSequenceStep(other.getSequenceStep());
      }
      if (other.hasServerErrorCode()) {
        setServerErrorCode(other.getServerErrorCode());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Wam.proto.WamEventWamLogin parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Wam.proto.WamEventWamLogin) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long androidKeystoreState_ ;
    /**
     * <code>optional int64 androidKeystoreState = 10;</code>
     * @return Whether the androidKeystoreState field is set.
     */
    public boolean hasAndroidKeystoreState() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 androidKeystoreState = 10;</code>
     * @return The androidKeystoreState.
     */
    public long getAndroidKeystoreState() {
      return androidKeystoreState_;
    }
    /**
     * <code>optional int64 androidKeystoreState = 10;</code>
     * @param value The androidKeystoreState to set.
     * @return This builder for chaining.
     */
    public Builder setAndroidKeystoreState(long value) {
      bitField0_ |= 0x00000001;
      androidKeystoreState_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 androidKeystoreState = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAndroidKeystoreState() {
      bitField0_ = (bitField0_ & ~0x00000001);
      androidKeystoreState_ = 0L;
      onChanged();
      return this;
    }

    private long connectionOrigin_ ;
    /**
     * <code>optional int64 connectionOrigin = 6;</code>
     * @return Whether the connectionOrigin field is set.
     */
    public boolean hasConnectionOrigin() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 connectionOrigin = 6;</code>
     * @return The connectionOrigin.
     */
    public long getConnectionOrigin() {
      return connectionOrigin_;
    }
    /**
     * <code>optional int64 connectionOrigin = 6;</code>
     * @param value The connectionOrigin to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionOrigin(long value) {
      bitField0_ |= 0x00000002;
      connectionOrigin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 connectionOrigin = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionOrigin() {
      bitField0_ = (bitField0_ & ~0x00000002);
      connectionOrigin_ = 0L;
      onChanged();
      return this;
    }

    private long connectionT_ ;
    /**
     * <code>optional int64 connectionT = 5;</code>
     * @return Whether the connectionT field is set.
     */
    public boolean hasConnectionT() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 connectionT = 5;</code>
     * @return The connectionT.
     */
    public long getConnectionT() {
      return connectionT_;
    }
    /**
     * <code>optional int64 connectionT = 5;</code>
     * @param value The connectionT to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionT(long value) {
      bitField0_ |= 0x00000004;
      connectionT_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 connectionT = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionT() {
      bitField0_ = (bitField0_ & ~0x00000004);
      connectionT_ = 0L;
      onChanged();
      return this;
    }

    private long loginDnsResolver_ ;
    /**
     * <code>optional int64 loginDnsResolver = 13;</code>
     * @return Whether the loginDnsResolver field is set.
     */
    public boolean hasLoginDnsResolver() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int64 loginDnsResolver = 13;</code>
     * @return The loginDnsResolver.
     */
    public long getLoginDnsResolver() {
      return loginDnsResolver_;
    }
    /**
     * <code>optional int64 loginDnsResolver = 13;</code>
     * @param value The loginDnsResolver to set.
     * @return This builder for chaining.
     */
    public Builder setLoginDnsResolver(long value) {
      bitField0_ |= 0x00000008;
      loginDnsResolver_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 loginDnsResolver = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoginDnsResolver() {
      bitField0_ = (bitField0_ & ~0x00000008);
      loginDnsResolver_ = 0L;
      onChanged();
      return this;
    }

    private long loginIpSource_ ;
    /**
     * <code>optional int64 loginIpSource = 14;</code>
     * @return Whether the loginIpSource field is set.
     */
    public boolean hasLoginIpSource() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int64 loginIpSource = 14;</code>
     * @return The loginIpSource.
     */
    public long getLoginIpSource() {
      return loginIpSource_;
    }
    /**
     * <code>optional int64 loginIpSource = 14;</code>
     * @param value The loginIpSource to set.
     * @return This builder for chaining.
     */
    public Builder setLoginIpSource(long value) {
      bitField0_ |= 0x00000010;
      loginIpSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 loginIpSource = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoginIpSource() {
      bitField0_ = (bitField0_ & ~0x00000010);
      loginIpSource_ = 0L;
      onChanged();
      return this;
    }

    private long loginPort_ ;
    /**
     * <code>optional int64 loginPort = 15;</code>
     * @return Whether the loginPort field is set.
     */
    public boolean hasLoginPort() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int64 loginPort = 15;</code>
     * @return The loginPort.
     */
    public long getLoginPort() {
      return loginPort_;
    }
    /**
     * <code>optional int64 loginPort = 15;</code>
     * @param value The loginPort to set.
     * @return This builder for chaining.
     */
    public Builder setLoginPort(long value) {
      bitField0_ |= 0x00000020;
      loginPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 loginPort = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoginPort() {
      bitField0_ = (bitField0_ & ~0x00000020);
      loginPort_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object loginResolvedPop_ = "";
    /**
     * <code>optional string loginResolvedPop = 19;</code>
     * @return Whether the loginResolvedPop field is set.
     */
    public boolean hasLoginResolvedPop() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string loginResolvedPop = 19;</code>
     * @return The loginResolvedPop.
     */
    public java.lang.String getLoginResolvedPop() {
      java.lang.Object ref = loginResolvedPop_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginResolvedPop_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string loginResolvedPop = 19;</code>
     * @return The bytes for loginResolvedPop.
     */
    public com.google.protobuf.ByteString
        getLoginResolvedPopBytes() {
      java.lang.Object ref = loginResolvedPop_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginResolvedPop_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string loginResolvedPop = 19;</code>
     * @param value The loginResolvedPop to set.
     * @return This builder for chaining.
     */
    public Builder setLoginResolvedPop(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      loginResolvedPop_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string loginResolvedPop = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoginResolvedPop() {
      bitField0_ = (bitField0_ & ~0x00000040);
      loginResolvedPop_ = getDefaultInstance().getLoginResolvedPop();
      onChanged();
      return this;
    }
    /**
     * <code>optional string loginResolvedPop = 19;</code>
     * @param value The bytes for loginResolvedPop to set.
     * @return This builder for chaining.
     */
    public Builder setLoginResolvedPopBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      loginResolvedPop_ = value;
      onChanged();
      return this;
    }

    private long loginResult_ ;
    /**
     * <code>optional int64 loginResult = 1;</code>
     * @return Whether the loginResult field is set.
     */
    public boolean hasLoginResult() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int64 loginResult = 1;</code>
     * @return The loginResult.
     */
    public long getLoginResult() {
      return loginResult_;
    }
    /**
     * <code>optional int64 loginResult = 1;</code>
     * @param value The loginResult to set.
     * @return This builder for chaining.
     */
    public Builder setLoginResult(long value) {
      bitField0_ |= 0x00000080;
      loginResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 loginResult = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoginResult() {
      bitField0_ = (bitField0_ & ~0x00000080);
      loginResult_ = 0L;
      onChanged();
      return this;
    }

    private long loginT_ ;
    /**
     * <code>optional int64 loginT = 3;</code>
     * @return Whether the loginT field is set.
     */
    public boolean hasLoginT() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional int64 loginT = 3;</code>
     * @return The loginT.
     */
    public long getLoginT() {
      return loginT_;
    }
    /**
     * <code>optional int64 loginT = 3;</code>
     * @param value The loginT to set.
     * @return This builder for chaining.
     */
    public Builder setLoginT(long value) {
      bitField0_ |= 0x00000100;
      loginT_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 loginT = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoginT() {
      bitField0_ = (bitField0_ & ~0x00000100);
      loginT_ = 0L;
      onChanged();
      return this;
    }

    private long logoutSessionId_ ;
    /**
     * <code>optional int64 logoutSessionId = 18;</code>
     * @return Whether the logoutSessionId field is set.
     */
    public boolean hasLogoutSessionId() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional int64 logoutSessionId = 18;</code>
     * @return The logoutSessionId.
     */
    public long getLogoutSessionId() {
      return logoutSessionId_;
    }
    /**
     * <code>optional int64 logoutSessionId = 18;</code>
     * @param value The logoutSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setLogoutSessionId(long value) {
      bitField0_ |= 0x00000200;
      logoutSessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 logoutSessionId = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogoutSessionId() {
      bitField0_ = (bitField0_ & ~0x00000200);
      logoutSessionId_ = 0L;
      onChanged();
      return this;
    }

    private long longConnect_ ;
    /**
     * <code>optional int64 longConnect = 4;</code>
     * @return Whether the longConnect field is set.
     */
    public boolean hasLongConnect() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional int64 longConnect = 4;</code>
     * @return The longConnect.
     */
    public long getLongConnect() {
      return longConnect_;
    }
    /**
     * <code>optional int64 longConnect = 4;</code>
     * @param value The longConnect to set.
     * @return This builder for chaining.
     */
    public Builder setLongConnect(long value) {
      bitField0_ |= 0x00000400;
      longConnect_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 longConnect = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLongConnect() {
      bitField0_ = (bitField0_ & ~0x00000400);
      longConnect_ = 0L;
      onChanged();
      return this;
    }

    private long noiseProtocolVersion_ ;
    /**
     * <code>optional int64 noiseProtocolVersion = 16;</code>
     * @return Whether the noiseProtocolVersion field is set.
     */
    public boolean hasNoiseProtocolVersion() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional int64 noiseProtocolVersion = 16;</code>
     * @return The noiseProtocolVersion.
     */
    public long getNoiseProtocolVersion() {
      return noiseProtocolVersion_;
    }
    /**
     * <code>optional int64 noiseProtocolVersion = 16;</code>
     * @param value The noiseProtocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setNoiseProtocolVersion(long value) {
      bitField0_ |= 0x00000800;
      noiseProtocolVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 noiseProtocolVersion = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearNoiseProtocolVersion() {
      bitField0_ = (bitField0_ & ~0x00000800);
      noiseProtocolVersion_ = 0L;
      onChanged();
      return this;
    }

    private long passive_ ;
    /**
     * <code>optional int64 passive = 8;</code>
     * @return Whether the passive field is set.
     */
    public boolean hasPassive() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>optional int64 passive = 8;</code>
     * @return The passive.
     */
    public long getPassive() {
      return passive_;
    }
    /**
     * <code>optional int64 passive = 8;</code>
     * @param value The passive to set.
     * @return This builder for chaining.
     */
    public Builder setPassive(long value) {
      bitField0_ |= 0x00001000;
      passive_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 passive = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassive() {
      bitField0_ = (bitField0_ & ~0x00001000);
      passive_ = 0L;
      onChanged();
      return this;
    }

    private long pendingAcksCount_ ;
    /**
     * <code>optional int64 pendingAcksCount = 17;</code>
     * @return Whether the pendingAcksCount field is set.
     */
    public boolean hasPendingAcksCount() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>optional int64 pendingAcksCount = 17;</code>
     * @return The pendingAcksCount.
     */
    public long getPendingAcksCount() {
      return pendingAcksCount_;
    }
    /**
     * <code>optional int64 pendingAcksCount = 17;</code>
     * @param value The pendingAcksCount to set.
     * @return This builder for chaining.
     */
    public Builder setPendingAcksCount(long value) {
      bitField0_ |= 0x00002000;
      pendingAcksCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 pendingAcksCount = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearPendingAcksCount() {
      bitField0_ = (bitField0_ & ~0x00002000);
      pendingAcksCount_ = 0L;
      onChanged();
      return this;
    }

    private long retryCount_ ;
    /**
     * <code>optional int64 retryCount = 2;</code>
     * @return Whether the retryCount field is set.
     */
    public boolean hasRetryCount() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>optional int64 retryCount = 2;</code>
     * @return The retryCount.
     */
    public long getRetryCount() {
      return retryCount_;
    }
    /**
     * <code>optional int64 retryCount = 2;</code>
     * @param value The retryCount to set.
     * @return This builder for chaining.
     */
    public Builder setRetryCount(long value) {
      bitField0_ |= 0x00004000;
      retryCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 retryCount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetryCount() {
      bitField0_ = (bitField0_ & ~0x00004000);
      retryCount_ = 0L;
      onChanged();
      return this;
    }

    private long sequenceStep_ ;
    /**
     * <code>optional int64 sequenceStep = 7;</code>
     * @return Whether the sequenceStep field is set.
     */
    public boolean hasSequenceStep() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <code>optional int64 sequenceStep = 7;</code>
     * @return The sequenceStep.
     */
    public long getSequenceStep() {
      return sequenceStep_;
    }
    /**
     * <code>optional int64 sequenceStep = 7;</code>
     * @param value The sequenceStep to set.
     * @return This builder for chaining.
     */
    public Builder setSequenceStep(long value) {
      bitField0_ |= 0x00008000;
      sequenceStep_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 sequenceStep = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSequenceStep() {
      bitField0_ = (bitField0_ & ~0x00008000);
      sequenceStep_ = 0L;
      onChanged();
      return this;
    }

    private long serverErrorCode_ ;
    /**
     * <code>optional int64 serverErrorCode = 9;</code>
     * @return Whether the serverErrorCode field is set.
     */
    public boolean hasServerErrorCode() {
      return ((bitField0_ & 0x00010000) != 0);
    }
    /**
     * <code>optional int64 serverErrorCode = 9;</code>
     * @return The serverErrorCode.
     */
    public long getServerErrorCode() {
      return serverErrorCode_;
    }
    /**
     * <code>optional int64 serverErrorCode = 9;</code>
     * @param value The serverErrorCode to set.
     * @return This builder for chaining.
     */
    public Builder setServerErrorCode(long value) {
      bitField0_ |= 0x00010000;
      serverErrorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 serverErrorCode = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerErrorCode() {
      bitField0_ = (bitField0_ & ~0x00010000);
      serverErrorCode_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Wam.WamEventWamLogin)
  }

  // @@protoc_insertion_point(class_scope:Wam.WamEventWamLogin)
  private static final Wam.proto.WamEventWamLogin DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Wam.proto.WamEventWamLogin();
  }

  public static Wam.proto.WamEventWamLogin getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<WamEventWamLogin>
      PARSER = new com.google.protobuf.AbstractParser<WamEventWamLogin>() {
    @java.lang.Override
    public WamEventWamLogin parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WamEventWamLogin(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WamEventWamLogin> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WamEventWamLogin> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Wam.proto.WamEventWamLogin getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

