// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventStickerCommonQueryToStaticServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventStickerCommonQueryToStaticServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 http_response_code = 2;</code>
   * @return Whether the httpResponseCode field is set.
   */
  boolean hasHttpResponseCode();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 http_response_code = 2;</code>
   * @return The httpResponseCode.
   */
  long getHttpResponseCode();

  /**
   * <code>optional string params = 3;</code>
   * @return Whether the params field is set.
   */
  boolean hasParams();
  /**
   * <code>optional string params = 3;</code>
   * @return The params.
   */
  java.lang.String getParams();
  /**
   * <code>optional string params = 3;</code>
   * @return The bytes for params.
   */
  com.google.protobuf.ByteString
      getParamsBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 query_latency_ms = 4;</code>
   * @return Whether the queryLatencyMs field is set.
   */
  boolean hasQueryLatencyMs();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 query_latency_ms = 4;</code>
   * @return The queryLatencyMs.
   */
  long getQueryLatencyMs();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 query_type_number = 1;</code>
   * @return Whether the queryTypeNumber field is set.
   */
  boolean hasQueryTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 query_type_number = 1;</code>
   * @return The queryTypeNumber.
   */
  long getQueryTypeNumber();
}
