// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

/**
 * Protobuf type {@code Wam.WamEventTsNavigation}
 */
public  final class WamEventTsNavigation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Wam.WamEventTsNavigation)
    WamEventTsNavigationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WamEventTsNavigation.newBuilder() to construct.
  private WamEventTsNavigation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WamEventTsNavigation() {
    cid_ = "";
    smbCatalogBusinessVertical_ = "";
    entryPointConversionApp_ = "";
    entryPointConversionSource_ = "";
    unifiedSessionId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WamEventTsNavigation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WamEventTsNavigation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000004;
            groupSize_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000080;
            navigationDestinationNumber_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000100;
            navigationSourceNumber_ = input.readInt64();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000200;
            relativeTimestampMs_ = input.readInt64();
            break;
          }
          case 40: {
            bitField0_ |= 0x00002000;
            tsSessionId_ = input.readInt64();
            break;
          }
          case 48: {
            bitField0_ |= 0x00004000;
            typeOfGroupNumber_ = input.readInt64();
            break;
          }
          case 56: {
            bitField0_ |= 0x00001000;
            threadTypeNumber_ = input.readInt64();
            break;
          }
          case 154: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            cid_ = bs;
            break;
          }
          case 162: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000400;
            smbCatalogBusinessVertical_ = bs;
            break;
          }
          case 168: {
            bitField0_ |= 0x00000800;
            smbCatalogIsCatalogVisible_ = input.readInt64();
            break;
          }
          case 184: {
            bitField0_ |= 0x00000002;
            entryPointConversationInitiatedNumber_ = input.readInt64();
            break;
          }
          case 194: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00008000;
            entryPointConversionApp_ = bs;
            break;
          }
          case 202: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00010000;
            entryPointConversionSource_ = bs;
            break;
          }
          case 208: {
            bitField0_ |= 0x00000010;
            isCloudapi_ = input.readInt64();
            break;
          }
          case 216: {
            bitField0_ |= 0x00000020;
            isOnpremises_ = input.readInt64();
            break;
          }
          case 224: {
            bitField0_ |= 0x00000040;
            isSmb_ = input.readInt64();
            break;
          }
          case 232: {
            bitField0_ |= 0x00000008;
            isCatalogVisible_ = input.readInt64();
            break;
          }
          case 248: {
            bitField0_ |= 0x00020000;
            referrerAction_ = input.readInt64();
            break;
          }
          case 256: {
            bitField0_ |= 0x00040000;
            tsTimestampMs_ = input.readInt64();
            break;
          }
          case 266: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00080000;
            unifiedSessionId_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Wam.proto.WamProto.internal_static_Wam_WamEventTsNavigation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Wam.proto.WamProto.internal_static_Wam_WamEventTsNavigation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Wam.proto.WamEventTsNavigation.class, Wam.proto.WamEventTsNavigation.Builder.class);
  }

  private int bitField0_;
  public static final int CID_FIELD_NUMBER = 19;
  private volatile java.lang.Object cid_;
  /**
   * <code>optional string cid = 19;</code>
   * @return Whether the cid field is set.
   */
  public boolean hasCid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string cid = 19;</code>
   * @return The cid.
   */
  public java.lang.String getCid() {
    java.lang.Object ref = cid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        cid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string cid = 19;</code>
   * @return The bytes for cid.
   */
  public com.google.protobuf.ByteString
      getCidBytes() {
    java.lang.Object ref = cid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTRY_POINT_CONVERSATION_INITIATED_NUMBER_FIELD_NUMBER = 23;
  private long entryPointConversationInitiatedNumber_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 entry_point_conversation_initiated_number = 23;</code>
   * @return Whether the entryPointConversationInitiatedNumber field is set.
   */
  public boolean hasEntryPointConversationInitiatedNumber() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 entry_point_conversation_initiated_number = 23;</code>
   * @return The entryPointConversationInitiatedNumber.
   */
  public long getEntryPointConversationInitiatedNumber() {
    return entryPointConversationInitiatedNumber_;
  }

  public static final int GROUP_SIZE_FIELD_NUMBER = 1;
  private long groupSize_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 group_size = 1;</code>
   * @return Whether the groupSize field is set.
   */
  public boolean hasGroupSize() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 group_size = 1;</code>
   * @return The groupSize.
   */
  public long getGroupSize() {
    return groupSize_;
  }

  public static final int IS_CATALOG_VISIBLE_FIELD_NUMBER = 29;
  private long isCatalogVisible_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_catalog_visible = 29;</code>
   * @return Whether the isCatalogVisible field is set.
   */
  public boolean hasIsCatalogVisible() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_catalog_visible = 29;</code>
   * @return The isCatalogVisible.
   */
  public long getIsCatalogVisible() {
    return isCatalogVisible_;
  }

  public static final int IS_CLOUDAPI_FIELD_NUMBER = 26;
  private long isCloudapi_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_cloudapi = 26;</code>
   * @return Whether the isCloudapi field is set.
   */
  public boolean hasIsCloudapi() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_cloudapi = 26;</code>
   * @return The isCloudapi.
   */
  public long getIsCloudapi() {
    return isCloudapi_;
  }

  public static final int IS_ONPREMISES_FIELD_NUMBER = 27;
  private long isOnpremises_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_onpremises = 27;</code>
   * @return Whether the isOnpremises field is set.
   */
  public boolean hasIsOnpremises() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_onpremises = 27;</code>
   * @return The isOnpremises.
   */
  public long getIsOnpremises() {
    return isOnpremises_;
  }

  public static final int IS_SMB_FIELD_NUMBER = 28;
  private long isSmb_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_smb = 28;</code>
   * @return Whether the isSmb field is set.
   */
  public boolean hasIsSmb() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_smb = 28;</code>
   * @return The isSmb.
   */
  public long getIsSmb() {
    return isSmb_;
  }

  public static final int NAVIGATION_DESTINATION_NUMBER_FIELD_NUMBER = 2;
  private long navigationDestinationNumber_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 navigation_destination_number = 2;</code>
   * @return Whether the navigationDestinationNumber field is set.
   */
  public boolean hasNavigationDestinationNumber() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 navigation_destination_number = 2;</code>
   * @return The navigationDestinationNumber.
   */
  public long getNavigationDestinationNumber() {
    return navigationDestinationNumber_;
  }

  public static final int NAVIGATION_SOURCE_NUMBER_FIELD_NUMBER = 3;
  private long navigationSourceNumber_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 navigation_source_number = 3;</code>
   * @return Whether the navigationSourceNumber field is set.
   */
  public boolean hasNavigationSourceNumber() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 navigation_source_number = 3;</code>
   * @return The navigationSourceNumber.
   */
  public long getNavigationSourceNumber() {
    return navigationSourceNumber_;
  }

  public static final int RELATIVE_TIMESTAMP_MS_FIELD_NUMBER = 4;
  private long relativeTimestampMs_;
  /**
   * <pre>
   * unknown typeton
   * </pre>
   *
   * <code>optional int64 relative_timestamp_ms = 4;</code>
   * @return Whether the relativeTimestampMs field is set.
   */
  public boolean hasRelativeTimestampMs() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <pre>
   * unknown typeton
   * </pre>
   *
   * <code>optional int64 relative_timestamp_ms = 4;</code>
   * @return The relativeTimestampMs.
   */
  public long getRelativeTimestampMs() {
    return relativeTimestampMs_;
  }

  public static final int SMB_CATALOG_BUSINESS_VERTICAL_FIELD_NUMBER = 20;
  private volatile java.lang.Object smbCatalogBusinessVertical_;
  /**
   * <code>optional string smb_catalog_business_vertical = 20;</code>
   * @return Whether the smbCatalogBusinessVertical field is set.
   */
  public boolean hasSmbCatalogBusinessVertical() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>optional string smb_catalog_business_vertical = 20;</code>
   * @return The smbCatalogBusinessVertical.
   */
  public java.lang.String getSmbCatalogBusinessVertical() {
    java.lang.Object ref = smbCatalogBusinessVertical_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        smbCatalogBusinessVertical_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string smb_catalog_business_vertical = 20;</code>
   * @return The bytes for smbCatalogBusinessVertical.
   */
  public com.google.protobuf.ByteString
      getSmbCatalogBusinessVerticalBytes() {
    java.lang.Object ref = smbCatalogBusinessVertical_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      smbCatalogBusinessVertical_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SMB_CATALOG_IS_CATALOG_VISIBLE_FIELD_NUMBER = 21;
  private long smbCatalogIsCatalogVisible_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_catalog_is_catalog_visible = 21;</code>
   * @return Whether the smbCatalogIsCatalogVisible field is set.
   */
  public boolean hasSmbCatalogIsCatalogVisible() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 smb_catalog_is_catalog_visible = 21;</code>
   * @return The smbCatalogIsCatalogVisible.
   */
  public long getSmbCatalogIsCatalogVisible() {
    return smbCatalogIsCatalogVisible_;
  }

  public static final int THREAD_TYPE_NUMBER_FIELD_NUMBER = 7;
  private long threadTypeNumber_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 thread_type_number = 7;</code>
   * @return Whether the threadTypeNumber field is set.
   */
  public boolean hasThreadTypeNumber() {
    return ((bitField0_ & 0x00001000) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 thread_type_number = 7;</code>
   * @return The threadTypeNumber.
   */
  public long getThreadTypeNumber() {
    return threadTypeNumber_;
  }

  public static final int TS_SESSION_ID_FIELD_NUMBER = 5;
  private long tsSessionId_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 ts_session_id = 5;</code>
   * @return Whether the tsSessionId field is set.
   */
  public boolean hasTsSessionId() {
    return ((bitField0_ & 0x00002000) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 ts_session_id = 5;</code>
   * @return The tsSessionId.
   */
  public long getTsSessionId() {
    return tsSessionId_;
  }

  public static final int TYPE_OF_GROUP_NUMBER_FIELD_NUMBER = 6;
  private long typeOfGroupNumber_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 type_of_group_number = 6;</code>
   * @return Whether the typeOfGroupNumber field is set.
   */
  public boolean hasTypeOfGroupNumber() {
    return ((bitField0_ & 0x00004000) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 type_of_group_number = 6;</code>
   * @return The typeOfGroupNumber.
   */
  public long getTypeOfGroupNumber() {
    return typeOfGroupNumber_;
  }

  public static final int ENTRY_POINT_CONVERSION_APP_FIELD_NUMBER = 24;
  private volatile java.lang.Object entryPointConversionApp_;
  /**
   * <code>optional string entry_point_conversion_app = 24;</code>
   * @return Whether the entryPointConversionApp field is set.
   */
  public boolean hasEntryPointConversionApp() {
    return ((bitField0_ & 0x00008000) != 0);
  }
  /**
   * <code>optional string entry_point_conversion_app = 24;</code>
   * @return The entryPointConversionApp.
   */
  public java.lang.String getEntryPointConversionApp() {
    java.lang.Object ref = entryPointConversionApp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        entryPointConversionApp_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string entry_point_conversion_app = 24;</code>
   * @return The bytes for entryPointConversionApp.
   */
  public com.google.protobuf.ByteString
      getEntryPointConversionAppBytes() {
    java.lang.Object ref = entryPointConversionApp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entryPointConversionApp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTRY_POINT_CONVERSION_SOURCE_FIELD_NUMBER = 25;
  private volatile java.lang.Object entryPointConversionSource_;
  /**
   * <code>optional string entry_point_conversion_source = 25;</code>
   * @return Whether the entryPointConversionSource field is set.
   */
  public boolean hasEntryPointConversionSource() {
    return ((bitField0_ & 0x00010000) != 0);
  }
  /**
   * <code>optional string entry_point_conversion_source = 25;</code>
   * @return The entryPointConversionSource.
   */
  public java.lang.String getEntryPointConversionSource() {
    java.lang.Object ref = entryPointConversionSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        entryPointConversionSource_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string entry_point_conversion_source = 25;</code>
   * @return The bytes for entryPointConversionSource.
   */
  public com.google.protobuf.ByteString
      getEntryPointConversionSourceBytes() {
    java.lang.Object ref = entryPointConversionSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entryPointConversionSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFERRERACTION_FIELD_NUMBER = 31;
  private long referrerAction_;
  /**
   * <code>optional int64 referrerAction = 31;</code>
   * @return Whether the referrerAction field is set.
   */
  public boolean hasReferrerAction() {
    return ((bitField0_ & 0x00020000) != 0);
  }
  /**
   * <code>optional int64 referrerAction = 31;</code>
   * @return The referrerAction.
   */
  public long getReferrerAction() {
    return referrerAction_;
  }

  public static final int TSTIMESTAMPMS_FIELD_NUMBER = 32;
  private long tsTimestampMs_;
  /**
   * <code>optional int64 tsTimestampMs = 32;</code>
   * @return Whether the tsTimestampMs field is set.
   */
  public boolean hasTsTimestampMs() {
    return ((bitField0_ & 0x00040000) != 0);
  }
  /**
   * <code>optional int64 tsTimestampMs = 32;</code>
   * @return The tsTimestampMs.
   */
  public long getTsTimestampMs() {
    return tsTimestampMs_;
  }

  public static final int UNIFIEDSESSIONID_FIELD_NUMBER = 33;
  private volatile java.lang.Object unifiedSessionId_;
  /**
   * <code>optional string unifiedSessionId = 33;</code>
   * @return Whether the unifiedSessionId field is set.
   */
  public boolean hasUnifiedSessionId() {
    return ((bitField0_ & 0x00080000) != 0);
  }
  /**
   * <code>optional string unifiedSessionId = 33;</code>
   * @return The unifiedSessionId.
   */
  public java.lang.String getUnifiedSessionId() {
    java.lang.Object ref = unifiedSessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        unifiedSessionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string unifiedSessionId = 33;</code>
   * @return The bytes for unifiedSessionId.
   */
  public com.google.protobuf.ByteString
      getUnifiedSessionIdBytes() {
    java.lang.Object ref = unifiedSessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unifiedSessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(1, groupSize_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeInt64(2, navigationDestinationNumber_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeInt64(3, navigationSourceNumber_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      output.writeInt64(4, relativeTimestampMs_);
    }
    if (((bitField0_ & 0x00002000) != 0)) {
      output.writeInt64(5, tsSessionId_);
    }
    if (((bitField0_ & 0x00004000) != 0)) {
      output.writeInt64(6, typeOfGroupNumber_);
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      output.writeInt64(7, threadTypeNumber_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, cid_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, smbCatalogBusinessVertical_);
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      output.writeInt64(21, smbCatalogIsCatalogVisible_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(23, entryPointConversationInitiatedNumber_);
    }
    if (((bitField0_ & 0x00008000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 24, entryPointConversionApp_);
    }
    if (((bitField0_ & 0x00010000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 25, entryPointConversionSource_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt64(26, isCloudapi_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt64(27, isOnpremises_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt64(28, isSmb_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt64(29, isCatalogVisible_);
    }
    if (((bitField0_ & 0x00020000) != 0)) {
      output.writeInt64(31, referrerAction_);
    }
    if (((bitField0_ & 0x00040000) != 0)) {
      output.writeInt64(32, tsTimestampMs_);
    }
    if (((bitField0_ & 0x00080000) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 33, unifiedSessionId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, groupSize_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, navigationDestinationNumber_);
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, navigationSourceNumber_);
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, relativeTimestampMs_);
    }
    if (((bitField0_ & 0x00002000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, tsSessionId_);
    }
    if (((bitField0_ & 0x00004000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, typeOfGroupNumber_);
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, threadTypeNumber_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, cid_);
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, smbCatalogBusinessVertical_);
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(21, smbCatalogIsCatalogVisible_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(23, entryPointConversationInitiatedNumber_);
    }
    if (((bitField0_ & 0x00008000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(24, entryPointConversionApp_);
    }
    if (((bitField0_ & 0x00010000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(25, entryPointConversionSource_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(26, isCloudapi_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(27, isOnpremises_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(28, isSmb_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(29, isCatalogVisible_);
    }
    if (((bitField0_ & 0x00020000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(31, referrerAction_);
    }
    if (((bitField0_ & 0x00040000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(32, tsTimestampMs_);
    }
    if (((bitField0_ & 0x00080000) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(33, unifiedSessionId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Wam.proto.WamEventTsNavigation)) {
      return super.equals(obj);
    }
    Wam.proto.WamEventTsNavigation other = (Wam.proto.WamEventTsNavigation) obj;

    if (hasCid() != other.hasCid()) return false;
    if (hasCid()) {
      if (!getCid()
          .equals(other.getCid())) return false;
    }
    if (hasEntryPointConversationInitiatedNumber() != other.hasEntryPointConversationInitiatedNumber()) return false;
    if (hasEntryPointConversationInitiatedNumber()) {
      if (getEntryPointConversationInitiatedNumber()
          != other.getEntryPointConversationInitiatedNumber()) return false;
    }
    if (hasGroupSize() != other.hasGroupSize()) return false;
    if (hasGroupSize()) {
      if (getGroupSize()
          != other.getGroupSize()) return false;
    }
    if (hasIsCatalogVisible() != other.hasIsCatalogVisible()) return false;
    if (hasIsCatalogVisible()) {
      if (getIsCatalogVisible()
          != other.getIsCatalogVisible()) return false;
    }
    if (hasIsCloudapi() != other.hasIsCloudapi()) return false;
    if (hasIsCloudapi()) {
      if (getIsCloudapi()
          != other.getIsCloudapi()) return false;
    }
    if (hasIsOnpremises() != other.hasIsOnpremises()) return false;
    if (hasIsOnpremises()) {
      if (getIsOnpremises()
          != other.getIsOnpremises()) return false;
    }
    if (hasIsSmb() != other.hasIsSmb()) return false;
    if (hasIsSmb()) {
      if (getIsSmb()
          != other.getIsSmb()) return false;
    }
    if (hasNavigationDestinationNumber() != other.hasNavigationDestinationNumber()) return false;
    if (hasNavigationDestinationNumber()) {
      if (getNavigationDestinationNumber()
          != other.getNavigationDestinationNumber()) return false;
    }
    if (hasNavigationSourceNumber() != other.hasNavigationSourceNumber()) return false;
    if (hasNavigationSourceNumber()) {
      if (getNavigationSourceNumber()
          != other.getNavigationSourceNumber()) return false;
    }
    if (hasRelativeTimestampMs() != other.hasRelativeTimestampMs()) return false;
    if (hasRelativeTimestampMs()) {
      if (getRelativeTimestampMs()
          != other.getRelativeTimestampMs()) return false;
    }
    if (hasSmbCatalogBusinessVertical() != other.hasSmbCatalogBusinessVertical()) return false;
    if (hasSmbCatalogBusinessVertical()) {
      if (!getSmbCatalogBusinessVertical()
          .equals(other.getSmbCatalogBusinessVertical())) return false;
    }
    if (hasSmbCatalogIsCatalogVisible() != other.hasSmbCatalogIsCatalogVisible()) return false;
    if (hasSmbCatalogIsCatalogVisible()) {
      if (getSmbCatalogIsCatalogVisible()
          != other.getSmbCatalogIsCatalogVisible()) return false;
    }
    if (hasThreadTypeNumber() != other.hasThreadTypeNumber()) return false;
    if (hasThreadTypeNumber()) {
      if (getThreadTypeNumber()
          != other.getThreadTypeNumber()) return false;
    }
    if (hasTsSessionId() != other.hasTsSessionId()) return false;
    if (hasTsSessionId()) {
      if (getTsSessionId()
          != other.getTsSessionId()) return false;
    }
    if (hasTypeOfGroupNumber() != other.hasTypeOfGroupNumber()) return false;
    if (hasTypeOfGroupNumber()) {
      if (getTypeOfGroupNumber()
          != other.getTypeOfGroupNumber()) return false;
    }
    if (hasEntryPointConversionApp() != other.hasEntryPointConversionApp()) return false;
    if (hasEntryPointConversionApp()) {
      if (!getEntryPointConversionApp()
          .equals(other.getEntryPointConversionApp())) return false;
    }
    if (hasEntryPointConversionSource() != other.hasEntryPointConversionSource()) return false;
    if (hasEntryPointConversionSource()) {
      if (!getEntryPointConversionSource()
          .equals(other.getEntryPointConversionSource())) return false;
    }
    if (hasReferrerAction() != other.hasReferrerAction()) return false;
    if (hasReferrerAction()) {
      if (getReferrerAction()
          != other.getReferrerAction()) return false;
    }
    if (hasTsTimestampMs() != other.hasTsTimestampMs()) return false;
    if (hasTsTimestampMs()) {
      if (getTsTimestampMs()
          != other.getTsTimestampMs()) return false;
    }
    if (hasUnifiedSessionId() != other.hasUnifiedSessionId()) return false;
    if (hasUnifiedSessionId()) {
      if (!getUnifiedSessionId()
          .equals(other.getUnifiedSessionId())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCid()) {
      hash = (37 * hash) + CID_FIELD_NUMBER;
      hash = (53 * hash) + getCid().hashCode();
    }
    if (hasEntryPointConversationInitiatedNumber()) {
      hash = (37 * hash) + ENTRY_POINT_CONVERSATION_INITIATED_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEntryPointConversationInitiatedNumber());
    }
    if (hasGroupSize()) {
      hash = (37 * hash) + GROUP_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupSize());
    }
    if (hasIsCatalogVisible()) {
      hash = (37 * hash) + IS_CATALOG_VISIBLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIsCatalogVisible());
    }
    if (hasIsCloudapi()) {
      hash = (37 * hash) + IS_CLOUDAPI_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIsCloudapi());
    }
    if (hasIsOnpremises()) {
      hash = (37 * hash) + IS_ONPREMISES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIsOnpremises());
    }
    if (hasIsSmb()) {
      hash = (37 * hash) + IS_SMB_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIsSmb());
    }
    if (hasNavigationDestinationNumber()) {
      hash = (37 * hash) + NAVIGATION_DESTINATION_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNavigationDestinationNumber());
    }
    if (hasNavigationSourceNumber()) {
      hash = (37 * hash) + NAVIGATION_SOURCE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNavigationSourceNumber());
    }
    if (hasRelativeTimestampMs()) {
      hash = (37 * hash) + RELATIVE_TIMESTAMP_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRelativeTimestampMs());
    }
    if (hasSmbCatalogBusinessVertical()) {
      hash = (37 * hash) + SMB_CATALOG_BUSINESS_VERTICAL_FIELD_NUMBER;
      hash = (53 * hash) + getSmbCatalogBusinessVertical().hashCode();
    }
    if (hasSmbCatalogIsCatalogVisible()) {
      hash = (37 * hash) + SMB_CATALOG_IS_CATALOG_VISIBLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSmbCatalogIsCatalogVisible());
    }
    if (hasThreadTypeNumber()) {
      hash = (37 * hash) + THREAD_TYPE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getThreadTypeNumber());
    }
    if (hasTsSessionId()) {
      hash = (37 * hash) + TS_SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTsSessionId());
    }
    if (hasTypeOfGroupNumber()) {
      hash = (37 * hash) + TYPE_OF_GROUP_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTypeOfGroupNumber());
    }
    if (hasEntryPointConversionApp()) {
      hash = (37 * hash) + ENTRY_POINT_CONVERSION_APP_FIELD_NUMBER;
      hash = (53 * hash) + getEntryPointConversionApp().hashCode();
    }
    if (hasEntryPointConversionSource()) {
      hash = (37 * hash) + ENTRY_POINT_CONVERSION_SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getEntryPointConversionSource().hashCode();
    }
    if (hasReferrerAction()) {
      hash = (37 * hash) + REFERRERACTION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReferrerAction());
    }
    if (hasTsTimestampMs()) {
      hash = (37 * hash) + TSTIMESTAMPMS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTsTimestampMs());
    }
    if (hasUnifiedSessionId()) {
      hash = (37 * hash) + UNIFIEDSESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getUnifiedSessionId().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Wam.proto.WamEventTsNavigation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventTsNavigation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventTsNavigation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventTsNavigation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventTsNavigation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventTsNavigation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventTsNavigation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventTsNavigation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEventTsNavigation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventTsNavigation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEventTsNavigation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventTsNavigation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Wam.proto.WamEventTsNavigation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Wam.WamEventTsNavigation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Wam.WamEventTsNavigation)
      Wam.proto.WamEventTsNavigationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventTsNavigation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventTsNavigation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Wam.proto.WamEventTsNavigation.class, Wam.proto.WamEventTsNavigation.Builder.class);
    }

    // Construct using Wam.proto.WamEventTsNavigation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cid_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      entryPointConversationInitiatedNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      groupSize_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      isCatalogVisible_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      isCloudapi_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      isOnpremises_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      isSmb_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      navigationDestinationNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000080);
      navigationSourceNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000100);
      relativeTimestampMs_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000200);
      smbCatalogBusinessVertical_ = "";
      bitField0_ = (bitField0_ & ~0x00000400);
      smbCatalogIsCatalogVisible_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000800);
      threadTypeNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00001000);
      tsSessionId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00002000);
      typeOfGroupNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00004000);
      entryPointConversionApp_ = "";
      bitField0_ = (bitField0_ & ~0x00008000);
      entryPointConversionSource_ = "";
      bitField0_ = (bitField0_ & ~0x00010000);
      referrerAction_ = 0L;
      bitField0_ = (bitField0_ & ~0x00020000);
      tsTimestampMs_ = 0L;
      bitField0_ = (bitField0_ & ~0x00040000);
      unifiedSessionId_ = "";
      bitField0_ = (bitField0_ & ~0x00080000);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventTsNavigation_descriptor;
    }

    @java.lang.Override
    public Wam.proto.WamEventTsNavigation getDefaultInstanceForType() {
      return Wam.proto.WamEventTsNavigation.getDefaultInstance();
    }

    @java.lang.Override
    public Wam.proto.WamEventTsNavigation build() {
      Wam.proto.WamEventTsNavigation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Wam.proto.WamEventTsNavigation buildPartial() {
      Wam.proto.WamEventTsNavigation result = new Wam.proto.WamEventTsNavigation(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.cid_ = cid_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.entryPointConversationInitiatedNumber_ = entryPointConversationInitiatedNumber_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.groupSize_ = groupSize_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isCatalogVisible_ = isCatalogVisible_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isCloudapi_ = isCloudapi_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.isOnpremises_ = isOnpremises_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.isSmb_ = isSmb_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.navigationDestinationNumber_ = navigationDestinationNumber_;
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.navigationSourceNumber_ = navigationSourceNumber_;
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.relativeTimestampMs_ = relativeTimestampMs_;
        to_bitField0_ |= 0x00000200;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        to_bitField0_ |= 0x00000400;
      }
      result.smbCatalogBusinessVertical_ = smbCatalogBusinessVertical_;
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.smbCatalogIsCatalogVisible_ = smbCatalogIsCatalogVisible_;
        to_bitField0_ |= 0x00000800;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.threadTypeNumber_ = threadTypeNumber_;
        to_bitField0_ |= 0x00001000;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.tsSessionId_ = tsSessionId_;
        to_bitField0_ |= 0x00002000;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.typeOfGroupNumber_ = typeOfGroupNumber_;
        to_bitField0_ |= 0x00004000;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        to_bitField0_ |= 0x00008000;
      }
      result.entryPointConversionApp_ = entryPointConversionApp_;
      if (((from_bitField0_ & 0x00010000) != 0)) {
        to_bitField0_ |= 0x00010000;
      }
      result.entryPointConversionSource_ = entryPointConversionSource_;
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.referrerAction_ = referrerAction_;
        to_bitField0_ |= 0x00020000;
      }
      if (((from_bitField0_ & 0x00040000) != 0)) {
        result.tsTimestampMs_ = tsTimestampMs_;
        to_bitField0_ |= 0x00040000;
      }
      if (((from_bitField0_ & 0x00080000) != 0)) {
        to_bitField0_ |= 0x00080000;
      }
      result.unifiedSessionId_ = unifiedSessionId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Wam.proto.WamEventTsNavigation) {
        return mergeFrom((Wam.proto.WamEventTsNavigation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Wam.proto.WamEventTsNavigation other) {
      if (other == Wam.proto.WamEventTsNavigation.getDefaultInstance()) return this;
      if (other.hasCid()) {
        bitField0_ |= 0x00000001;
        cid_ = other.cid_;
        onChanged();
      }
      if (other.hasEntryPointConversationInitiatedNumber()) {
        setEntryPointConversationInitiatedNumber(other.getEntryPointConversationInitiatedNumber());
      }
      if (other.hasGroupSize()) {
        setGroupSize(other.getGroupSize());
      }
      if (other.hasIsCatalogVisible()) {
        setIsCatalogVisible(other.getIsCatalogVisible());
      }
      if (other.hasIsCloudapi()) {
        setIsCloudapi(other.getIsCloudapi());
      }
      if (other.hasIsOnpremises()) {
        setIsOnpremises(other.getIsOnpremises());
      }
      if (other.hasIsSmb()) {
        setIsSmb(other.getIsSmb());
      }
      if (other.hasNavigationDestinationNumber()) {
        setNavigationDestinationNumber(other.getNavigationDestinationNumber());
      }
      if (other.hasNavigationSourceNumber()) {
        setNavigationSourceNumber(other.getNavigationSourceNumber());
      }
      if (other.hasRelativeTimestampMs()) {
        setRelativeTimestampMs(other.getRelativeTimestampMs());
      }
      if (other.hasSmbCatalogBusinessVertical()) {
        bitField0_ |= 0x00000400;
        smbCatalogBusinessVertical_ = other.smbCatalogBusinessVertical_;
        onChanged();
      }
      if (other.hasSmbCatalogIsCatalogVisible()) {
        setSmbCatalogIsCatalogVisible(other.getSmbCatalogIsCatalogVisible());
      }
      if (other.hasThreadTypeNumber()) {
        setThreadTypeNumber(other.getThreadTypeNumber());
      }
      if (other.hasTsSessionId()) {
        setTsSessionId(other.getTsSessionId());
      }
      if (other.hasTypeOfGroupNumber()) {
        setTypeOfGroupNumber(other.getTypeOfGroupNumber());
      }
      if (other.hasEntryPointConversionApp()) {
        bitField0_ |= 0x00008000;
        entryPointConversionApp_ = other.entryPointConversionApp_;
        onChanged();
      }
      if (other.hasEntryPointConversionSource()) {
        bitField0_ |= 0x00010000;
        entryPointConversionSource_ = other.entryPointConversionSource_;
        onChanged();
      }
      if (other.hasReferrerAction()) {
        setReferrerAction(other.getReferrerAction());
      }
      if (other.hasTsTimestampMs()) {
        setTsTimestampMs(other.getTsTimestampMs());
      }
      if (other.hasUnifiedSessionId()) {
        bitField0_ |= 0x00080000;
        unifiedSessionId_ = other.unifiedSessionId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Wam.proto.WamEventTsNavigation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Wam.proto.WamEventTsNavigation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object cid_ = "";
    /**
     * <code>optional string cid = 19;</code>
     * @return Whether the cid field is set.
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string cid = 19;</code>
     * @return The cid.
     */
    public java.lang.String getCid() {
      java.lang.Object ref = cid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cid_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cid = 19;</code>
     * @return The bytes for cid.
     */
    public com.google.protobuf.ByteString
        getCidBytes() {
      java.lang.Object ref = cid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cid = 19;</code>
     * @param value The cid to set.
     * @return This builder for chaining.
     */
    public Builder setCid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      cid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cid = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearCid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cid_ = getDefaultInstance().getCid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cid = 19;</code>
     * @param value The bytes for cid to set.
     * @return This builder for chaining.
     */
    public Builder setCidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      cid_ = value;
      onChanged();
      return this;
    }

    private long entryPointConversationInitiatedNumber_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 entry_point_conversation_initiated_number = 23;</code>
     * @return Whether the entryPointConversationInitiatedNumber field is set.
     */
    public boolean hasEntryPointConversationInitiatedNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 entry_point_conversation_initiated_number = 23;</code>
     * @return The entryPointConversationInitiatedNumber.
     */
    public long getEntryPointConversationInitiatedNumber() {
      return entryPointConversationInitiatedNumber_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 entry_point_conversation_initiated_number = 23;</code>
     * @param value The entryPointConversationInitiatedNumber to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversationInitiatedNumber(long value) {
      bitField0_ |= 0x00000002;
      entryPointConversationInitiatedNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 entry_point_conversation_initiated_number = 23;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntryPointConversationInitiatedNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      entryPointConversationInitiatedNumber_ = 0L;
      onChanged();
      return this;
    }

    private long groupSize_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 group_size = 1;</code>
     * @return Whether the groupSize field is set.
     */
    public boolean hasGroupSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 group_size = 1;</code>
     * @return The groupSize.
     */
    public long getGroupSize() {
      return groupSize_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 group_size = 1;</code>
     * @param value The groupSize to set.
     * @return This builder for chaining.
     */
    public Builder setGroupSize(long value) {
      bitField0_ |= 0x00000004;
      groupSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 group_size = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      groupSize_ = 0L;
      onChanged();
      return this;
    }

    private long isCatalogVisible_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_catalog_visible = 29;</code>
     * @return Whether the isCatalogVisible field is set.
     */
    public boolean hasIsCatalogVisible() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_catalog_visible = 29;</code>
     * @return The isCatalogVisible.
     */
    public long getIsCatalogVisible() {
      return isCatalogVisible_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_catalog_visible = 29;</code>
     * @param value The isCatalogVisible to set.
     * @return This builder for chaining.
     */
    public Builder setIsCatalogVisible(long value) {
      bitField0_ |= 0x00000008;
      isCatalogVisible_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_catalog_visible = 29;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsCatalogVisible() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isCatalogVisible_ = 0L;
      onChanged();
      return this;
    }

    private long isCloudapi_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_cloudapi = 26;</code>
     * @return Whether the isCloudapi field is set.
     */
    public boolean hasIsCloudapi() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_cloudapi = 26;</code>
     * @return The isCloudapi.
     */
    public long getIsCloudapi() {
      return isCloudapi_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_cloudapi = 26;</code>
     * @param value The isCloudapi to set.
     * @return This builder for chaining.
     */
    public Builder setIsCloudapi(long value) {
      bitField0_ |= 0x00000010;
      isCloudapi_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_cloudapi = 26;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsCloudapi() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isCloudapi_ = 0L;
      onChanged();
      return this;
    }

    private long isOnpremises_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_onpremises = 27;</code>
     * @return Whether the isOnpremises field is set.
     */
    public boolean hasIsOnpremises() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_onpremises = 27;</code>
     * @return The isOnpremises.
     */
    public long getIsOnpremises() {
      return isOnpremises_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_onpremises = 27;</code>
     * @param value The isOnpremises to set.
     * @return This builder for chaining.
     */
    public Builder setIsOnpremises(long value) {
      bitField0_ |= 0x00000020;
      isOnpremises_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_onpremises = 27;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOnpremises() {
      bitField0_ = (bitField0_ & ~0x00000020);
      isOnpremises_ = 0L;
      onChanged();
      return this;
    }

    private long isSmb_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_smb = 28;</code>
     * @return Whether the isSmb field is set.
     */
    public boolean hasIsSmb() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_smb = 28;</code>
     * @return The isSmb.
     */
    public long getIsSmb() {
      return isSmb_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_smb = 28;</code>
     * @param value The isSmb to set.
     * @return This builder for chaining.
     */
    public Builder setIsSmb(long value) {
      bitField0_ |= 0x00000040;
      isSmb_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 is_smb = 28;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSmb() {
      bitField0_ = (bitField0_ & ~0x00000040);
      isSmb_ = 0L;
      onChanged();
      return this;
    }

    private long navigationDestinationNumber_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 navigation_destination_number = 2;</code>
     * @return Whether the navigationDestinationNumber field is set.
     */
    public boolean hasNavigationDestinationNumber() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 navigation_destination_number = 2;</code>
     * @return The navigationDestinationNumber.
     */
    public long getNavigationDestinationNumber() {
      return navigationDestinationNumber_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 navigation_destination_number = 2;</code>
     * @param value The navigationDestinationNumber to set.
     * @return This builder for chaining.
     */
    public Builder setNavigationDestinationNumber(long value) {
      bitField0_ |= 0x00000080;
      navigationDestinationNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 navigation_destination_number = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNavigationDestinationNumber() {
      bitField0_ = (bitField0_ & ~0x00000080);
      navigationDestinationNumber_ = 0L;
      onChanged();
      return this;
    }

    private long navigationSourceNumber_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 navigation_source_number = 3;</code>
     * @return Whether the navigationSourceNumber field is set.
     */
    public boolean hasNavigationSourceNumber() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 navigation_source_number = 3;</code>
     * @return The navigationSourceNumber.
     */
    public long getNavigationSourceNumber() {
      return navigationSourceNumber_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 navigation_source_number = 3;</code>
     * @param value The navigationSourceNumber to set.
     * @return This builder for chaining.
     */
    public Builder setNavigationSourceNumber(long value) {
      bitField0_ |= 0x00000100;
      navigationSourceNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 navigation_source_number = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNavigationSourceNumber() {
      bitField0_ = (bitField0_ & ~0x00000100);
      navigationSourceNumber_ = 0L;
      onChanged();
      return this;
    }

    private long relativeTimestampMs_ ;
    /**
     * <pre>
     * unknown typeton
     * </pre>
     *
     * <code>optional int64 relative_timestamp_ms = 4;</code>
     * @return Whether the relativeTimestampMs field is set.
     */
    public boolean hasRelativeTimestampMs() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     * unknown typeton
     * </pre>
     *
     * <code>optional int64 relative_timestamp_ms = 4;</code>
     * @return The relativeTimestampMs.
     */
    public long getRelativeTimestampMs() {
      return relativeTimestampMs_;
    }
    /**
     * <pre>
     * unknown typeton
     * </pre>
     *
     * <code>optional int64 relative_timestamp_ms = 4;</code>
     * @param value The relativeTimestampMs to set.
     * @return This builder for chaining.
     */
    public Builder setRelativeTimestampMs(long value) {
      bitField0_ |= 0x00000200;
      relativeTimestampMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown typeton
     * </pre>
     *
     * <code>optional int64 relative_timestamp_ms = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRelativeTimestampMs() {
      bitField0_ = (bitField0_ & ~0x00000200);
      relativeTimestampMs_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object smbCatalogBusinessVertical_ = "";
    /**
     * <code>optional string smb_catalog_business_vertical = 20;</code>
     * @return Whether the smbCatalogBusinessVertical field is set.
     */
    public boolean hasSmbCatalogBusinessVertical() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>optional string smb_catalog_business_vertical = 20;</code>
     * @return The smbCatalogBusinessVertical.
     */
    public java.lang.String getSmbCatalogBusinessVertical() {
      java.lang.Object ref = smbCatalogBusinessVertical_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          smbCatalogBusinessVertical_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string smb_catalog_business_vertical = 20;</code>
     * @return The bytes for smbCatalogBusinessVertical.
     */
    public com.google.protobuf.ByteString
        getSmbCatalogBusinessVerticalBytes() {
      java.lang.Object ref = smbCatalogBusinessVertical_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        smbCatalogBusinessVertical_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string smb_catalog_business_vertical = 20;</code>
     * @param value The smbCatalogBusinessVertical to set.
     * @return This builder for chaining.
     */
    public Builder setSmbCatalogBusinessVertical(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      smbCatalogBusinessVertical_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string smb_catalog_business_vertical = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearSmbCatalogBusinessVertical() {
      bitField0_ = (bitField0_ & ~0x00000400);
      smbCatalogBusinessVertical_ = getDefaultInstance().getSmbCatalogBusinessVertical();
      onChanged();
      return this;
    }
    /**
     * <code>optional string smb_catalog_business_vertical = 20;</code>
     * @param value The bytes for smbCatalogBusinessVertical to set.
     * @return This builder for chaining.
     */
    public Builder setSmbCatalogBusinessVerticalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
      smbCatalogBusinessVertical_ = value;
      onChanged();
      return this;
    }

    private long smbCatalogIsCatalogVisible_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 smb_catalog_is_catalog_visible = 21;</code>
     * @return Whether the smbCatalogIsCatalogVisible field is set.
     */
    public boolean hasSmbCatalogIsCatalogVisible() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 smb_catalog_is_catalog_visible = 21;</code>
     * @return The smbCatalogIsCatalogVisible.
     */
    public long getSmbCatalogIsCatalogVisible() {
      return smbCatalogIsCatalogVisible_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 smb_catalog_is_catalog_visible = 21;</code>
     * @param value The smbCatalogIsCatalogVisible to set.
     * @return This builder for chaining.
     */
    public Builder setSmbCatalogIsCatalogVisible(long value) {
      bitField0_ |= 0x00000800;
      smbCatalogIsCatalogVisible_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 smb_catalog_is_catalog_visible = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearSmbCatalogIsCatalogVisible() {
      bitField0_ = (bitField0_ & ~0x00000800);
      smbCatalogIsCatalogVisible_ = 0L;
      onChanged();
      return this;
    }

    private long threadTypeNumber_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 thread_type_number = 7;</code>
     * @return Whether the threadTypeNumber field is set.
     */
    public boolean hasThreadTypeNumber() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 thread_type_number = 7;</code>
     * @return The threadTypeNumber.
     */
    public long getThreadTypeNumber() {
      return threadTypeNumber_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 thread_type_number = 7;</code>
     * @param value The threadTypeNumber to set.
     * @return This builder for chaining.
     */
    public Builder setThreadTypeNumber(long value) {
      bitField0_ |= 0x00001000;
      threadTypeNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 thread_type_number = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadTypeNumber() {
      bitField0_ = (bitField0_ & ~0x00001000);
      threadTypeNumber_ = 0L;
      onChanged();
      return this;
    }

    private long tsSessionId_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 ts_session_id = 5;</code>
     * @return Whether the tsSessionId field is set.
     */
    public boolean hasTsSessionId() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 ts_session_id = 5;</code>
     * @return The tsSessionId.
     */
    public long getTsSessionId() {
      return tsSessionId_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 ts_session_id = 5;</code>
     * @param value The tsSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setTsSessionId(long value) {
      bitField0_ |= 0x00002000;
      tsSessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 ts_session_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTsSessionId() {
      bitField0_ = (bitField0_ & ~0x00002000);
      tsSessionId_ = 0L;
      onChanged();
      return this;
    }

    private long typeOfGroupNumber_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 type_of_group_number = 6;</code>
     * @return Whether the typeOfGroupNumber field is set.
     */
    public boolean hasTypeOfGroupNumber() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 type_of_group_number = 6;</code>
     * @return The typeOfGroupNumber.
     */
    public long getTypeOfGroupNumber() {
      return typeOfGroupNumber_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 type_of_group_number = 6;</code>
     * @param value The typeOfGroupNumber to set.
     * @return This builder for chaining.
     */
    public Builder setTypeOfGroupNumber(long value) {
      bitField0_ |= 0x00004000;
      typeOfGroupNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 type_of_group_number = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeOfGroupNumber() {
      bitField0_ = (bitField0_ & ~0x00004000);
      typeOfGroupNumber_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object entryPointConversionApp_ = "";
    /**
     * <code>optional string entry_point_conversion_app = 24;</code>
     * @return Whether the entryPointConversionApp field is set.
     */
    public boolean hasEntryPointConversionApp() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <code>optional string entry_point_conversion_app = 24;</code>
     * @return The entryPointConversionApp.
     */
    public java.lang.String getEntryPointConversionApp() {
      java.lang.Object ref = entryPointConversionApp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entryPointConversionApp_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_app = 24;</code>
     * @return The bytes for entryPointConversionApp.
     */
    public com.google.protobuf.ByteString
        getEntryPointConversionAppBytes() {
      java.lang.Object ref = entryPointConversionApp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entryPointConversionApp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_app = 24;</code>
     * @param value The entryPointConversionApp to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionApp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
      entryPointConversionApp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_app = 24;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntryPointConversionApp() {
      bitField0_ = (bitField0_ & ~0x00008000);
      entryPointConversionApp_ = getDefaultInstance().getEntryPointConversionApp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_app = 24;</code>
     * @param value The bytes for entryPointConversionApp to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionAppBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
      entryPointConversionApp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object entryPointConversionSource_ = "";
    /**
     * <code>optional string entry_point_conversion_source = 25;</code>
     * @return Whether the entryPointConversionSource field is set.
     */
    public boolean hasEntryPointConversionSource() {
      return ((bitField0_ & 0x00010000) != 0);
    }
    /**
     * <code>optional string entry_point_conversion_source = 25;</code>
     * @return The entryPointConversionSource.
     */
    public java.lang.String getEntryPointConversionSource() {
      java.lang.Object ref = entryPointConversionSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entryPointConversionSource_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_source = 25;</code>
     * @return The bytes for entryPointConversionSource.
     */
    public com.google.protobuf.ByteString
        getEntryPointConversionSourceBytes() {
      java.lang.Object ref = entryPointConversionSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entryPointConversionSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string entry_point_conversion_source = 25;</code>
     * @param value The entryPointConversionSource to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
      entryPointConversionSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_source = 25;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntryPointConversionSource() {
      bitField0_ = (bitField0_ & ~0x00010000);
      entryPointConversionSource_ = getDefaultInstance().getEntryPointConversionSource();
      onChanged();
      return this;
    }
    /**
     * <code>optional string entry_point_conversion_source = 25;</code>
     * @param value The bytes for entryPointConversionSource to set.
     * @return This builder for chaining.
     */
    public Builder setEntryPointConversionSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
      entryPointConversionSource_ = value;
      onChanged();
      return this;
    }

    private long referrerAction_ ;
    /**
     * <code>optional int64 referrerAction = 31;</code>
     * @return Whether the referrerAction field is set.
     */
    public boolean hasReferrerAction() {
      return ((bitField0_ & 0x00020000) != 0);
    }
    /**
     * <code>optional int64 referrerAction = 31;</code>
     * @return The referrerAction.
     */
    public long getReferrerAction() {
      return referrerAction_;
    }
    /**
     * <code>optional int64 referrerAction = 31;</code>
     * @param value The referrerAction to set.
     * @return This builder for chaining.
     */
    public Builder setReferrerAction(long value) {
      bitField0_ |= 0x00020000;
      referrerAction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 referrerAction = 31;</code>
     * @return This builder for chaining.
     */
    public Builder clearReferrerAction() {
      bitField0_ = (bitField0_ & ~0x00020000);
      referrerAction_ = 0L;
      onChanged();
      return this;
    }

    private long tsTimestampMs_ ;
    /**
     * <code>optional int64 tsTimestampMs = 32;</code>
     * @return Whether the tsTimestampMs field is set.
     */
    public boolean hasTsTimestampMs() {
      return ((bitField0_ & 0x00040000) != 0);
    }
    /**
     * <code>optional int64 tsTimestampMs = 32;</code>
     * @return The tsTimestampMs.
     */
    public long getTsTimestampMs() {
      return tsTimestampMs_;
    }
    /**
     * <code>optional int64 tsTimestampMs = 32;</code>
     * @param value The tsTimestampMs to set.
     * @return This builder for chaining.
     */
    public Builder setTsTimestampMs(long value) {
      bitField0_ |= 0x00040000;
      tsTimestampMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 tsTimestampMs = 32;</code>
     * @return This builder for chaining.
     */
    public Builder clearTsTimestampMs() {
      bitField0_ = (bitField0_ & ~0x00040000);
      tsTimestampMs_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object unifiedSessionId_ = "";
    /**
     * <code>optional string unifiedSessionId = 33;</code>
     * @return Whether the unifiedSessionId field is set.
     */
    public boolean hasUnifiedSessionId() {
      return ((bitField0_ & 0x00080000) != 0);
    }
    /**
     * <code>optional string unifiedSessionId = 33;</code>
     * @return The unifiedSessionId.
     */
    public java.lang.String getUnifiedSessionId() {
      java.lang.Object ref = unifiedSessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          unifiedSessionId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string unifiedSessionId = 33;</code>
     * @return The bytes for unifiedSessionId.
     */
    public com.google.protobuf.ByteString
        getUnifiedSessionIdBytes() {
      java.lang.Object ref = unifiedSessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unifiedSessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string unifiedSessionId = 33;</code>
     * @param value The unifiedSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setUnifiedSessionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
      unifiedSessionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string unifiedSessionId = 33;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnifiedSessionId() {
      bitField0_ = (bitField0_ & ~0x00080000);
      unifiedSessionId_ = getDefaultInstance().getUnifiedSessionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string unifiedSessionId = 33;</code>
     * @param value The bytes for unifiedSessionId to set.
     * @return This builder for chaining.
     */
    public Builder setUnifiedSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00080000;
      unifiedSessionId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Wam.WamEventTsNavigation)
  }

  // @@protoc_insertion_point(class_scope:Wam.WamEventTsNavigation)
  private static final Wam.proto.WamEventTsNavigation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Wam.proto.WamEventTsNavigation();
  }

  public static Wam.proto.WamEventTsNavigation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<WamEventTsNavigation>
      PARSER = new com.google.protobuf.AbstractParser<WamEventTsNavigation>() {
    @java.lang.Override
    public WamEventTsNavigation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WamEventTsNavigation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WamEventTsNavigation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WamEventTsNavigation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Wam.proto.WamEventTsNavigation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

