// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

/**
 * Protobuf type {@code Wam.WamEventPrekeysFetch}
 */
public  final class WamEventPrekeysFetch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Wam.WamEventPrekeysFetch)
    WamEventPrekeysFetchOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WamEventPrekeysFetch.newBuilder() to construct.
  private WamEventPrekeysFetch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WamEventPrekeysFetch() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WamEventPrekeysFetch();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WamEventPrekeysFetch(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            onIdentityChange_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000004;
            prekeysFetchCount_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000002;
            prekeysFetchContextNumber_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Wam.proto.WamProto.internal_static_Wam_WamEventPrekeysFetch_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Wam.proto.WamProto.internal_static_Wam_WamEventPrekeysFetch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Wam.proto.WamEventPrekeysFetch.class, Wam.proto.WamEventPrekeysFetch.Builder.class);
  }

  private int bitField0_;
  public static final int ON_IDENTITY_CHANGE_FIELD_NUMBER = 1;
  private long onIdentityChange_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 on_identity_change = 1;</code>
   * @return Whether the onIdentityChange field is set.
   */
  public boolean hasOnIdentityChange() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 on_identity_change = 1;</code>
   * @return The onIdentityChange.
   */
  public long getOnIdentityChange() {
    return onIdentityChange_;
  }

  public static final int PREKEYS_FETCH_CONTEXT_NUMBER_FIELD_NUMBER = 3;
  private long prekeysFetchContextNumber_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 prekeys_fetch_context_number = 3;</code>
   * @return Whether the prekeysFetchContextNumber field is set.
   */
  public boolean hasPrekeysFetchContextNumber() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 prekeys_fetch_context_number = 3;</code>
   * @return The prekeysFetchContextNumber.
   */
  public long getPrekeysFetchContextNumber() {
    return prekeysFetchContextNumber_;
  }

  public static final int PREKEYS_FETCH_COUNT_FIELD_NUMBER = 2;
  private long prekeysFetchCount_;
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 prekeys_fetch_count = 2;</code>
   * @return Whether the prekeysFetchCount field is set.
   */
  public boolean hasPrekeysFetchCount() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 prekeys_fetch_count = 2;</code>
   * @return The prekeysFetchCount.
   */
  public long getPrekeysFetchCount() {
    return prekeysFetchCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, onIdentityChange_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(2, prekeysFetchCount_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(3, prekeysFetchContextNumber_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, onIdentityChange_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, prekeysFetchCount_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, prekeysFetchContextNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Wam.proto.WamEventPrekeysFetch)) {
      return super.equals(obj);
    }
    Wam.proto.WamEventPrekeysFetch other = (Wam.proto.WamEventPrekeysFetch) obj;

    if (hasOnIdentityChange() != other.hasOnIdentityChange()) return false;
    if (hasOnIdentityChange()) {
      if (getOnIdentityChange()
          != other.getOnIdentityChange()) return false;
    }
    if (hasPrekeysFetchContextNumber() != other.hasPrekeysFetchContextNumber()) return false;
    if (hasPrekeysFetchContextNumber()) {
      if (getPrekeysFetchContextNumber()
          != other.getPrekeysFetchContextNumber()) return false;
    }
    if (hasPrekeysFetchCount() != other.hasPrekeysFetchCount()) return false;
    if (hasPrekeysFetchCount()) {
      if (getPrekeysFetchCount()
          != other.getPrekeysFetchCount()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOnIdentityChange()) {
      hash = (37 * hash) + ON_IDENTITY_CHANGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOnIdentityChange());
    }
    if (hasPrekeysFetchContextNumber()) {
      hash = (37 * hash) + PREKEYS_FETCH_CONTEXT_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrekeysFetchContextNumber());
    }
    if (hasPrekeysFetchCount()) {
      hash = (37 * hash) + PREKEYS_FETCH_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrekeysFetchCount());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Wam.proto.WamEventPrekeysFetch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventPrekeysFetch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventPrekeysFetch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventPrekeysFetch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventPrekeysFetch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamEventPrekeysFetch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamEventPrekeysFetch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventPrekeysFetch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEventPrekeysFetch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventPrekeysFetch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamEventPrekeysFetch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamEventPrekeysFetch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Wam.proto.WamEventPrekeysFetch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Wam.WamEventPrekeysFetch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Wam.WamEventPrekeysFetch)
      Wam.proto.WamEventPrekeysFetchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventPrekeysFetch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventPrekeysFetch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Wam.proto.WamEventPrekeysFetch.class, Wam.proto.WamEventPrekeysFetch.Builder.class);
    }

    // Construct using Wam.proto.WamEventPrekeysFetch.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      onIdentityChange_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      prekeysFetchContextNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      prekeysFetchCount_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Wam.proto.WamProto.internal_static_Wam_WamEventPrekeysFetch_descriptor;
    }

    @java.lang.Override
    public Wam.proto.WamEventPrekeysFetch getDefaultInstanceForType() {
      return Wam.proto.WamEventPrekeysFetch.getDefaultInstance();
    }

    @java.lang.Override
    public Wam.proto.WamEventPrekeysFetch build() {
      Wam.proto.WamEventPrekeysFetch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Wam.proto.WamEventPrekeysFetch buildPartial() {
      Wam.proto.WamEventPrekeysFetch result = new Wam.proto.WamEventPrekeysFetch(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.onIdentityChange_ = onIdentityChange_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.prekeysFetchContextNumber_ = prekeysFetchContextNumber_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.prekeysFetchCount_ = prekeysFetchCount_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Wam.proto.WamEventPrekeysFetch) {
        return mergeFrom((Wam.proto.WamEventPrekeysFetch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Wam.proto.WamEventPrekeysFetch other) {
      if (other == Wam.proto.WamEventPrekeysFetch.getDefaultInstance()) return this;
      if (other.hasOnIdentityChange()) {
        setOnIdentityChange(other.getOnIdentityChange());
      }
      if (other.hasPrekeysFetchContextNumber()) {
        setPrekeysFetchContextNumber(other.getPrekeysFetchContextNumber());
      }
      if (other.hasPrekeysFetchCount()) {
        setPrekeysFetchCount(other.getPrekeysFetchCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Wam.proto.WamEventPrekeysFetch parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Wam.proto.WamEventPrekeysFetch) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long onIdentityChange_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 on_identity_change = 1;</code>
     * @return Whether the onIdentityChange field is set.
     */
    public boolean hasOnIdentityChange() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 on_identity_change = 1;</code>
     * @return The onIdentityChange.
     */
    public long getOnIdentityChange() {
      return onIdentityChange_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 on_identity_change = 1;</code>
     * @param value The onIdentityChange to set.
     * @return This builder for chaining.
     */
    public Builder setOnIdentityChange(long value) {
      bitField0_ |= 0x00000001;
      onIdentityChange_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 on_identity_change = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnIdentityChange() {
      bitField0_ = (bitField0_ & ~0x00000001);
      onIdentityChange_ = 0L;
      onChanged();
      return this;
    }

    private long prekeysFetchContextNumber_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 prekeys_fetch_context_number = 3;</code>
     * @return Whether the prekeysFetchContextNumber field is set.
     */
    public boolean hasPrekeysFetchContextNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 prekeys_fetch_context_number = 3;</code>
     * @return The prekeysFetchContextNumber.
     */
    public long getPrekeysFetchContextNumber() {
      return prekeysFetchContextNumber_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 prekeys_fetch_context_number = 3;</code>
     * @param value The prekeysFetchContextNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPrekeysFetchContextNumber(long value) {
      bitField0_ |= 0x00000002;
      prekeysFetchContextNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 prekeys_fetch_context_number = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrekeysFetchContextNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      prekeysFetchContextNumber_ = 0L;
      onChanged();
      return this;
    }

    private long prekeysFetchCount_ ;
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 prekeys_fetch_count = 2;</code>
     * @return Whether the prekeysFetchCount field is set.
     */
    public boolean hasPrekeysFetchCount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 prekeys_fetch_count = 2;</code>
     * @return The prekeysFetchCount.
     */
    public long getPrekeysFetchCount() {
      return prekeysFetchCount_;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 prekeys_fetch_count = 2;</code>
     * @param value The prekeysFetchCount to set.
     * @return This builder for chaining.
     */
    public Builder setPrekeysFetchCount(long value) {
      bitField0_ |= 0x00000004;
      prekeysFetchCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unknown type
     * </pre>
     *
     * <code>optional int64 prekeys_fetch_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrekeysFetchCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      prekeysFetchCount_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Wam.WamEventPrekeysFetch)
  }

  // @@protoc_insertion_point(class_scope:Wam.WamEventPrekeysFetch)
  private static final Wam.proto.WamEventPrekeysFetch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Wam.proto.WamEventPrekeysFetch();
  }

  public static Wam.proto.WamEventPrekeysFetch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<WamEventPrekeysFetch>
      PARSER = new com.google.protobuf.AbstractParser<WamEventPrekeysFetch>() {
    @java.lang.Override
    public WamEventPrekeysFetch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WamEventPrekeysFetch(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WamEventPrekeysFetch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WamEventPrekeysFetch> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Wam.proto.WamEventPrekeysFetch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

