// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventFsMissedUpdatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventFsMissedUpdates)
    com.google.protobuf.MessageOrBuilder {
}
