// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventExposuresSendOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventExposuresSend)
    com.google.protobuf.MessageOrBuilder {
}
