// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamEventBannerEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamEventBannerEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string banner_id = 3;</code>
   * @return Whether the bannerId field is set.
   */
  boolean hasBannerId();
  /**
   * <code>optional string banner_id = 3;</code>
   * @return The bannerId.
   */
  java.lang.String getBannerId();
  /**
   * <code>optional string banner_id = 3;</code>
   * @return The bytes for bannerId.
   */
  com.google.protobuf.ByteString
      getBannerIdBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 banner_operation_number = 2;</code>
   * @return Whether the bannerOperationNumber field is set.
   */
  boolean hasBannerOperationNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 banner_operation_number = 2;</code>
   * @return The bannerOperationNumber.
   */
  long getBannerOperationNumber();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 banner_type_number = 1;</code>
   * @return Whether the bannerTypeNumber field is set.
   */
  boolean hasBannerTypeNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 banner_type_number = 1;</code>
   * @return The bannerTypeNumber.
   */
  long getBannerTypeNumber();
}
