// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public final class WamProto {
  private WamProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventFsMissedUpdates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventFsMissedUpdates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventTsBitArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventTsBitArray_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventStickerCommonQueryToStaticServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventStickerCommonQueryToStaticServer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventExposuresSend_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventExposuresSend_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventBannerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventBannerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventTsNavigation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventTsNavigation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventAdvPrimaryIdentityMissing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventAdvPrimaryIdentityMissing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventQbmIncomingMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventQbmIncomingMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamAndroidPerfTimer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamAndroidPerfTimer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventProfilePicDownload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventProfilePicDownload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventPrekeysFetch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventPrekeysFetch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventAdvStoredTimestampExpired_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventAdvStoredTimestampExpired_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventMessageReceive_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventMessageReceive_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventE2eMessageRecv_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventE2eMessageRecv_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEventWamLogin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEventWamLogin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamEntryPointConversion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamEntryPointConversion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wam_WamWefrClientExposure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wam_WamWefrClientExposure_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tWAM.proto\022\003Wam\"\277\010\n\tWamRecord\022\021\n\ttimest" +
      "amp\030/ \001(\003\022\017\n\006ab_key\030\335\020 \001(\t\022\020\n\007ab_key2\030\371\"" +
      " \001(\t\022\022\n\tapp_build\030\371\014 \001(\003\022\031\n\020app_distribu" +
      "tion\030\373\014 \001(\003\022\033\n\023app_is_beta_release\030\025 \001(\003" +
      "\022\023\n\013app_version\030\021 \001(\t\022\034\n\023calling_test_bu" +
      "cket\030\321| \001(\t\022\036\n\025device_classification\030\253q " +
      "\001(\003\022\023\n\013device_name\030\r \001(\t\022\027\n\016device_versi" +
      "on\030\231# \001(\t\022\021\n\010expo_key\030\245\' \001(\t\022\037\n\026iphone_o" +
      "s_build_number\030\221= \001(\t\022\027\n\016iphone_process\030" +
      "\203\003 \001(\003\022\033\n\022iphone_sdk_version\030\371H \001(\t\022\025\n\014i" +
      "s_companion\030\373] \001(\003\022\025\n\014is_md_opt_in\030\2479 \001(" +
      "\003\022\013\n\003mcc\030\005 \001(\003\022\022\n\tmem_class\030\217\005 \001(\003\022\013\n\003mn" +
      "c\030\003 \001(\003\022\034\n\023mobile_build_number\030\373y \001(\t\022\027\n" +
      "\017network_is_wifi\030\027 \001(\003\022\032\n\022network_radio_" +
      "type\030i \001(\003\022\023\n\noc_version\030\3530 \001(\003\022\022\n\nos_ve" +
      "rsion\030\017 \001(\t\022\020\n\010platform\030\013 \001(\003\022\020\n\007product" +
      "\030\3318 \001(\t\022\030\n\017ps_country_code\030\2615 \001(\t\022\016\n\005ps_" +
      "id\030\365. \001(\t\022$\n\033service_improvement_opt_out" +
      "\030\355g \001(\003\022\022\n\tstream_id\030\327\033 \001(\t\022%\n\034user_acti" +
      "vity_logging_method\030\247\020 \001(\t\022\"\n\031wameta_log" +
      "ger_test_filter\030\211| \001(\t\022\034\n\023webc_phone_pla" +
      "tform\030\303\005 \001(\t\022\025\n\014total_memory\030\261\005 \001(\003\022\030\n\017y" +
      "ear_class_2016\030\271\024 \001(\003\022\016\n\005model\030\237\002 \001(\t\022\025\n" +
      "\014manufacturer\030\241\002 \001(\t\022$\n\033number_of_inacti" +
      "ve_accounts\030\241w \001(\003\022\021\n\010location\030\353\025 \001(\t\022\017\n" +
      "\006device\030\357\003 \001(\t\022\030\n\017screen_diagonal\030\361] \001(\003" +
      "\022\037\n\026is_google_play_install\030\217P \001(\003\022\037\n\006eve" +
      "nts\030\377\377\003 \003(\0132\r.Wam.WamEvent\"\031\n\027WamEventFs" +
      "MissedUpdates\"\363\001\n\022WamEventTsBitArray\022\025\n\r" +
      "bitarray_high\030\001 \001(\003\022\027\n\017bitarray_length\030\002" +
      " \001(\003\022\024\n\014bitarray_low\030\003 \001(\003\022\027\n\017cumulative" +
      "_bits\030\004 \001(\003\022\035\n\025relative_timestamp_ms\030\005 \001" +
      "(\003\022\023\n\013session_seq\030\006 \001(\003\022\025\n\rts_session_id" +
      "\030\007 \001(\003\022\027\n\017ts_timestamp_ms\030\010 \001(\003\022\032\n\022unifi" +
      "ed_session_id\030\t \001(\t\"\213\001\n(WamEventStickerC" +
      "ommonQueryToStaticServer\022\032\n\022http_respons" +
      "e_code\030\002 \001(\003\022\016\n\006params\030\003 \001(\t\022\030\n\020query_la" +
      "tency_ms\030\004 \001(\003\022\031\n\021query_type_number\030\001 \001(" +
      "\003\"\027\n\025WamEventExposuresSend\"\362\010\n\010WamEvent\022" +
      "\021\n\ttimestamp\030/ \001(\003\0228\n\024WamEventTsNavigati" +
      "on\030\356! \001(\0132\031.Wam.WamEventTsNavigation\022`\n(" +
      "WamEventStickerCommonQueryToStaticServer" +
      "\030\264\025 \001(\0132-.Wam.WamEventStickerCommonQuery" +
      "ToStaticServer\0224\n\022WamEventTsBitArray\030\354! " +
      "\001(\0132\027.Wam.WamEventTsBitArray\022=\n\027WamEvent" +
      "FsMissedUpdates\030\002 \001(\0132\034.Wam.WamEventFsMi" +
      "ssedUpdates\022:\n\025WamEventExposuresSend\030\234\037 " +
      "\001(\0132\032.Wam.WamEventExposuresSend\022R\n!WamEv" +
      "entAdvPrimaryIdentityMissing\030\344\027 \001(\0132&.Wa" +
      "m.WamEventAdvPrimaryIdentityMissing\0226\n\023W" +
      "amEventBannerEvent\030\252\014 \001(\0132\030.Wam.WamEvent" +
      "BannerEvent\022D\n\032WamEventQbmIncomingMessag" +
      "e\030\316\035 \001(\0132\037.Wam.WamEventQbmIncomingMessag" +
      "e\0226\n\023WamAndroidPerfTimer\030\204\020 \001(\0132\030.Wam.Wa" +
      "mAndroidPerfTimer\022D\n\032WamEventProfilePicD" +
      "ownload\030\320\006 \001(\0132\037.Wam.WamEventProfilePicD" +
      "ownload\0228\n\024WamEventPrekeysFetch\030\354\023 \001(\0132\031" +
      ".Wam.WamEventPrekeysFetch\022R\n!WamEventAdv" +
      "StoredTimestampExpired\030\334\027 \001(\0132&.Wam.WamE" +
      "ventAdvStoredTimestampExpired\022<\n\026WamEven" +
      "tMessageReceive\030\302\003 \001(\0132\033.Wam.WamEventMes" +
      "sageReceive\022<\n\026WamEventE2eMessageRecv\030\336\003" +
      " \001(\0132\033.Wam.WamEventE2eMessageRecv\0220\n\020Wam" +
      "EventWamLogin\030\314\003 \001(\0132\025.Wam.WamEventWamLo" +
      "gin\022>\n\027WamEntryPointConversion\030\340\025 \001(\0132\034." +
      "Wam.WamEntryPointConversion\022:\n\025WamWefrCl" +
      "ientExposure\030\200+ \001(\0132\032.Wam.WamWefrClientE" +
      "xposure\"e\n\023WamEventBannerEvent\022\021\n\tbanner" +
      "_id\030\003 \001(\t\022\037\n\027banner_operation_number\030\002 \001" +
      "(\003\022\032\n\022banner_type_number\030\001 \001(\003\"\336\004\n\024WamEv" +
      "entTsNavigation\022\013\n\003cid\030\023 \001(\t\0221\n)entry_po" +
      "int_conversation_initiated_number\030\027 \001(\003\022" +
      "\022\n\ngroup_size\030\001 \001(\003\022\032\n\022is_catalog_visibl" +
      "e\030\035 \001(\003\022\023\n\013is_cloudapi\030\032 \001(\003\022\025\n\ris_onpre" +
      "mises\030\033 \001(\003\022\016\n\006is_smb\030\034 \001(\003\022%\n\035navigatio" +
      "n_destination_number\030\002 \001(\003\022 \n\030navigation" +
      "_source_number\030\003 \001(\003\022\035\n\025relative_timesta" +
      "mp_ms\030\004 \001(\003\022%\n\035smb_catalog_business_vert" +
      "ical\030\024 \001(\t\022&\n\036smb_catalog_is_catalog_vis" +
      "ible\030\025 \001(\003\022\032\n\022thread_type_number\030\007 \001(\003\022\025" +
      "\n\rts_session_id\030\005 \001(\003\022\034\n\024type_of_group_n" +
      "umber\030\006 \001(\003\022\"\n\032entry_point_conversion_ap" +
      "p\030\030 \001(\t\022%\n\035entry_point_conversion_source" +
      "\030\031 \001(\t\022\026\n\016referrerAction\030\037 \001(\003\022\025\n\rtsTime" +
      "stampMs\030  \001(\003\022\030\n\020unifiedSessionId\030! \001(\t\"" +
      "W\n!WamEventAdvPrimaryIdentityMissing\0222\n*" +
      "primary_identity_missing_proto_type_numb" +
      "er\030\001 \001(\003\"\324\007\n\032WamEventQbmIncomingMessage\022" +
      "!\n\031api_daily_thread_count_7d\030\025 \001(\003\022\034\n\024ap" +
      "i_message_count_1d\030\026 \001(\003\022\034\n\024api_message_" +
      "count_7d\030\027 \001(\003\022\"\n\032api_unique_thread_coun" +
      "t_7d\030\031 \001(\003\022 \n\030chats_folder_type_number\030\001" +
      " \001(\003\022\031\n\021companion_devices\030\n \001(\003\022\033\n\023conta" +
      "ct_type_number\030\002 \001(\003\022\023\n\013hsm_tag_str\030\016 \001(" +
      "\t\022\036\n\026is_from_ads_manager_mm\030\017 \001(\003\022\024\n\014is_" +
      "from_capi\030\020 \001(\003\022\020\n\010is_muted\030\024 \001(\003\0221\n)las" +
      "t_outgoing_message_delta_time_received\030\r" +
      " \001(\003\022\032\n\022message_has_button\030\022 \001(\003\022\027\n\017mess" +
      "age_has_url\030\023 \001(\003\022\027\n\017message_id_hmac\030\021 \001" +
      "(\t\022\030\n\020message_type_str\030\007 \001(\t\022\r\n\005muted\030\004 " +
      "\001(\003\022\034\n\024notification_enabled\030\005 \001(\003\022\027\n\017qbm" +
      "_flag_number\030\006 \001(\003\022\024\n\014qbm_flag_str\030\014 \001(\t" +
      "\022\035\n\025read_receipts_enabled\030\t \001(\003\022!\n\031smb_d" +
      "aily_thread_count_7d\030\034 \001(\003\022\034\n\024smb_messag" +
      "e_count_1d\030\035 \001(\003\022\034\n\024smb_message_count_7d" +
      "\030\036 \001(\003\022\037\n\027smb_total_message_count\030\037 \001(\003\022" +
      "\"\n\032smb_total_new_thread_count\030  \001(\003\022\"\n\032s" +
      "mb_unique_thread_count_1d\030! \001(\003\022\"\n\032smb_u" +
      "nique_thread_count_7d\030\" \001(\003\022\026\n\016thread_id" +
      "_hmac\030\010 \001(\t\022 \n\030keepChatsArchivedEnabled\030" +
      "\003 \001(\003\022$\n\034lastOutgoingMessageDeltaTime\030\013 " +
      "\001(\003\022\032\n\022threadCreationTime\030# \001(\003\"i\n\023WamAn" +
      "droidPerfTimer\022\033\n\023androidPerfDuration\030\001 " +
      "\001(\003\022\034\n\024androidPerfExtraData\030\003 \001(\t\022\027\n\017and" +
      "roidPerfName\030\002 \001(\t\"\324\001\n\032WamEventProfilePi" +
      "cDownload\022&\n\036profile_pic_download_http_c" +
      "ode\030\005 \001(\003\022*\n\"profile_pic_download_result" +
      "_number\030\001 \001(\003\022!\n\031profile_pic_download_si" +
      "ze\030\004 \001(\003\022\036\n\026profile_pic_download_t\030\003 \001(\003" +
      "\022\037\n\027profile_pic_type_number\030\002 \001(\003\"u\n\024Wam" +
      "EventPrekeysFetch\022\032\n\022on_identity_change\030" +
      "\001 \001(\003\022$\n\034prekeys_fetch_context_number\030\003 " +
      "\001(\003\022\033\n\023prekeys_fetch_count\030\002 \001(\003\"E\n!WamE" +
      "ventAdvStoredTimestampExpired\022 \n\030adv_exp" +
      "ire_time_in_hours\030\001 \001(\003\"\347\010\n\026WamEventMess" +
      "ageReceive\022$\n\034agent_engagement_type_numb" +
      "er\030\034 \001(\003\022\027\n\017bot_type_number\030% \001(\003\022\024\n\014dev" +
      "ice_count\030\020 \001(\003\022!\n\031device_size_bucket_nu" +
      "mber\030\n \001(\003\022*\n\"disappearing_chat_initiato" +
      "r_number\030\016 \001(\003\022\030\n\020edit_type_number\030\031 \001(\003" +
      "\022\035\n\025ephemerality_duration\030\r \001(\003\022%\n\035ephem" +
      "erality_initiator_number\030\032 \001(\003\022*\n\"epheme" +
      "rality_trigger_action_number\030\033 \001(\003\022\024\n\014ha" +
      "s_username\030\' \001(\003\022&\n\036message_addressing_m" +
      "ode_number\030\" \001(\003\022 \n\030message_is_internati" +
      "onal\030\004 \001(\003\022!\n\031message_media_type_number\030" +
      "\002 \001(\003\022\032\n\022message_queue_time\030\017 \001(\003\022\032\n\022mes" +
      "sage_receive_t0\030\006 \001(\003\022\032\n\022message_receive" +
      "_t1\030\007 \001(\003\022\033\n\023message_type_number\030\001 \001(\003\022\033" +
      "\n\023muted_group_message\030\010 \001(\003\022\025\n\roffline_c" +
      "ount\030\036 \001(\003\022\032\n\022padding_bytes_size\030\026 \001(\003\022\031" +
      "\n\021participant_count\030\021 \001(\003\022\032\n\022revoke_type" +
      "_number\030\024 \001(\003\022,\n$sender_default_disappea" +
      "ring_duration\030\013 \001(\003\022%\n\035server_addressing" +
      "_mode_number\030# \001(\003\022\025\n\rsticker_is_ai\030\035 \001(" +
      "\003\022%\n\035sticker_is_from_sticker_maker\030\037 \001(\003" +
      "\022(\n sticker_maker_source_type_number\030  \001" +
      "(\003\022\034\n\024type_of_group_number\030\025 \001(\003\022\022\n\nisAC" +
      "omment\030$ \001(\003\022\020\n\010isAReply\030\023 \001(\003\022\032\n\022isForw" +
      "ardedForward\030\022 \001(\003\022\r\n\005isLid\030\030 \001(\003\022\022\n\nisV" +
      "iewOnce\030\t \001(\003\022\033\n\023localAddressingMode\030! \001" +
      "(\003\022\030\n\020messageIsOffline\030\005 \001(\003\022+\n#receiver" +
      "DefaultDisappearingDuration\030\014 \001(\003\"\215\005\n\026Wa" +
      "mEventE2eMessageRecv\022$\n\034agent_engagement" +
      "_type_number\030\017 \001(\003\022\027\n\017bot_type_number\030\023 " +
      "\001(\003\022\"\n\032e2e_ciphertext_type_number\030\005 \001(\003\022" +
      "\036\n\026e2e_ciphertext_version\030\006 \001(\003\022\036\n\026e2e_d" +
      "estination_number\030\004 \001(\003\022!\n\031e2e_failure_r" +
      "eason_number\030\002 \001(\003\022\036\n\026e2e_sender_type_nu" +
      "mber\030\010 \001(\003\022\026\n\016e2e_successful\030\001 \001(\003\022\030\n\020ed" +
      "it_type_number\030\r \001(\003\022\026\n\016is_hosted_chat\030\024" +
      " \001(\003\022\016\n\006is_lid\030\013 \001(\003\022$\n\034local_addressing" +
      "_mode_number\030\020 \001(\003\022&\n\036message_addressing" +
      "_mode_number\030\021 \001(\003\022!\n\031message_media_type" +
      "_number\030\007 \001(\003\022\017\n\007offline\030\t \001(\003\022\023\n\013retry_" +
      "count\030\003 \001(\003\022\032\n\022revoke_type_number\030\n \001(\003\022" +
      "%\n\035server_addressing_mode_number\030\022 \001(\003\022\032" +
      "\n\022stanza_type_number\030\016 \001(\003\022\034\n\024type_of_gr" +
      "oup_number\030\014 \001(\003\022\037\n\027messageDistributionT" +
      "ype\030\025 \001(\003\"\234\003\n\020WamEventWamLogin\022\034\n\024androi" +
      "dKeystoreState\030\n \001(\003\022\030\n\020connectionOrigin" +
      "\030\006 \001(\003\022\023\n\013connectionT\030\005 \001(\003\022\030\n\020loginDnsR" +
      "esolver\030\r \001(\003\022\025\n\rloginIpSource\030\016 \001(\003\022\021\n\t" +
      "loginPort\030\017 \001(\003\022\030\n\020loginResolvedPop\030\023 \001(" +
      "\t\022\023\n\013loginResult\030\001 \001(\003\022\016\n\006loginT\030\003 \001(\003\022\027" +
      "\n\017logoutSessionId\030\022 \001(\003\022\023\n\013longConnect\030\004" +
      " \001(\003\022\034\n\024noiseProtocolVersion\030\020 \001(\003\022\017\n\007pa" +
      "ssive\030\010 \001(\003\022\030\n\020pendingAcksCount\030\021 \001(\003\022\022\n" +
      "\nretryCount\030\002 \001(\003\022\024\n\014sequenceStep\030\007 \001(\003\022" +
      "\027\n\017serverErrorCode\030\t \001(\003\"\214\002\n\027WamEntryPoi" +
      "ntConversion\022$\n\034entry_point_converstion_" +
      "type\030\001 \001(\003\022%\n\035entry_point_conversion_sou" +
      "rce\030\002 \001(\t\022\"\n\032entry_point_conversion_app\030" +
      "\003 \001(\t\022 \n\030first_message_time_stamp\030\004 \001(\003\022" +
      ".\n&entry_point_conversion_external_mediu" +
      "m\030\005 \001(\t\022.\n&entry_point_conversion_extern" +
      "al_source\030\006 \001(\t\"F\n\025WamWefrClientExposure" +
      "\022\024\n\014exposure_key\030\001 \001(\t\022\027\n\017sent_with_dail" +
      "y\030\003 \001(\003B\027\n\tWam.protoB\010WamProtoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Wam_WamRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Wam_WamRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamRecord_descriptor,
        new java.lang.String[] { "Timestamp", "AbKey", "AbKey2", "AppBuild", "AppDistribution", "AppIsBetaRelease", "AppVersion", "CallingTestBucket", "DeviceClassification", "DeviceName", "DeviceVersion", "ExpoKey", "IphoneOsBuildNumber", "IphoneProcess", "IphoneSdkVersion", "IsCompanion", "IsMdOptIn", "Mcc", "MemClass", "Mnc", "MobileBuildNumber", "NetworkIsWifi", "NetworkRadioType", "OcVersion", "OsVersion", "Platform", "Product", "PsCountryCode", "PsId", "ServiceImprovementOptOut", "StreamId", "UserActivityLoggingMethod", "WametaLoggerTestFilter", "WebcPhonePlatform", "TotalMemory", "YearClass2016", "Model", "Manufacturer", "NumberOfInactiveAccounts", "Location", "Device", "ScreenDiagonal", "IsGooglePlayInstall", "Events", });
    internal_static_Wam_WamEventFsMissedUpdates_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Wam_WamEventFsMissedUpdates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventFsMissedUpdates_descriptor,
        new java.lang.String[] { });
    internal_static_Wam_WamEventTsBitArray_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Wam_WamEventTsBitArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventTsBitArray_descriptor,
        new java.lang.String[] { "BitarrayHigh", "BitarrayLength", "BitarrayLow", "CumulativeBits", "RelativeTimestampMs", "SessionSeq", "TsSessionId", "TsTimestampMs", "UnifiedSessionId", });
    internal_static_Wam_WamEventStickerCommonQueryToStaticServer_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Wam_WamEventStickerCommonQueryToStaticServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventStickerCommonQueryToStaticServer_descriptor,
        new java.lang.String[] { "HttpResponseCode", "Params", "QueryLatencyMs", "QueryTypeNumber", });
    internal_static_Wam_WamEventExposuresSend_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Wam_WamEventExposuresSend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventExposuresSend_descriptor,
        new java.lang.String[] { });
    internal_static_Wam_WamEvent_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Wam_WamEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEvent_descriptor,
        new java.lang.String[] { "Timestamp", "WamEventTsNavigation", "WamEventStickerCommonQueryToStaticServer", "WamEventTsBitArray", "WamEventFsMissedUpdates", "WamEventExposuresSend", "WamEventAdvPrimaryIdentityMissing", "WamEventBannerEvent", "WamEventQbmIncomingMessage", "WamAndroidPerfTimer", "WamEventProfilePicDownload", "WamEventPrekeysFetch", "WamEventAdvStoredTimestampExpired", "WamEventMessageReceive", "WamEventE2EMessageRecv", "WamEventWamLogin", "WamEntryPointConversion", "WamWefrClientExposure", });
    internal_static_Wam_WamEventBannerEvent_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Wam_WamEventBannerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventBannerEvent_descriptor,
        new java.lang.String[] { "BannerId", "BannerOperationNumber", "BannerTypeNumber", });
    internal_static_Wam_WamEventTsNavigation_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Wam_WamEventTsNavigation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventTsNavigation_descriptor,
        new java.lang.String[] { "Cid", "EntryPointConversationInitiatedNumber", "GroupSize", "IsCatalogVisible", "IsCloudapi", "IsOnpremises", "IsSmb", "NavigationDestinationNumber", "NavigationSourceNumber", "RelativeTimestampMs", "SmbCatalogBusinessVertical", "SmbCatalogIsCatalogVisible", "ThreadTypeNumber", "TsSessionId", "TypeOfGroupNumber", "EntryPointConversionApp", "EntryPointConversionSource", "ReferrerAction", "TsTimestampMs", "UnifiedSessionId", });
    internal_static_Wam_WamEventAdvPrimaryIdentityMissing_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Wam_WamEventAdvPrimaryIdentityMissing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventAdvPrimaryIdentityMissing_descriptor,
        new java.lang.String[] { "PrimaryIdentityMissingProtoTypeNumber", });
    internal_static_Wam_WamEventQbmIncomingMessage_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Wam_WamEventQbmIncomingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventQbmIncomingMessage_descriptor,
        new java.lang.String[] { "ApiDailyThreadCount7D", "ApiMessageCount1D", "ApiMessageCount7D", "ApiUniqueThreadCount7D", "ChatsFolderTypeNumber", "CompanionDevices", "ContactTypeNumber", "HsmTagStr", "IsFromAdsManagerMm", "IsFromCapi", "IsMuted", "LastOutgoingMessageDeltaTimeReceived", "MessageHasButton", "MessageHasUrl", "MessageIdHmac", "MessageTypeStr", "Muted", "NotificationEnabled", "QbmFlagNumber", "QbmFlagStr", "ReadReceiptsEnabled", "SmbDailyThreadCount7D", "SmbMessageCount1D", "SmbMessageCount7D", "SmbTotalMessageCount", "SmbTotalNewThreadCount", "SmbUniqueThreadCount1D", "SmbUniqueThreadCount7D", "ThreadIdHmac", "KeepChatsArchivedEnabled", "LastOutgoingMessageDeltaTime", "ThreadCreationTime", });
    internal_static_Wam_WamAndroidPerfTimer_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Wam_WamAndroidPerfTimer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamAndroidPerfTimer_descriptor,
        new java.lang.String[] { "AndroidPerfDuration", "AndroidPerfExtraData", "AndroidPerfName", });
    internal_static_Wam_WamEventProfilePicDownload_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Wam_WamEventProfilePicDownload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventProfilePicDownload_descriptor,
        new java.lang.String[] { "ProfilePicDownloadHttpCode", "ProfilePicDownloadResultNumber", "ProfilePicDownloadSize", "ProfilePicDownloadT", "ProfilePicTypeNumber", });
    internal_static_Wam_WamEventPrekeysFetch_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Wam_WamEventPrekeysFetch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventPrekeysFetch_descriptor,
        new java.lang.String[] { "OnIdentityChange", "PrekeysFetchContextNumber", "PrekeysFetchCount", });
    internal_static_Wam_WamEventAdvStoredTimestampExpired_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Wam_WamEventAdvStoredTimestampExpired_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventAdvStoredTimestampExpired_descriptor,
        new java.lang.String[] { "AdvExpireTimeInHours", });
    internal_static_Wam_WamEventMessageReceive_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Wam_WamEventMessageReceive_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventMessageReceive_descriptor,
        new java.lang.String[] { "AgentEngagementTypeNumber", "BotTypeNumber", "DeviceCount", "DeviceSizeBucketNumber", "DisappearingChatInitiatorNumber", "EditTypeNumber", "EphemeralityDuration", "EphemeralityInitiatorNumber", "EphemeralityTriggerActionNumber", "HasUsername", "MessageAddressingModeNumber", "MessageIsInternational", "MessageMediaTypeNumber", "MessageQueueTime", "MessageReceiveT0", "MessageReceiveT1", "MessageTypeNumber", "MutedGroupMessage", "OfflineCount", "PaddingBytesSize", "ParticipantCount", "RevokeTypeNumber", "SenderDefaultDisappearingDuration", "ServerAddressingModeNumber", "StickerIsAi", "StickerIsFromStickerMaker", "StickerMakerSourceTypeNumber", "TypeOfGroupNumber", "IsAComment", "IsAReply", "IsForwardedForward", "IsLid", "IsViewOnce", "LocalAddressingMode", "MessageIsOffline", "ReceiverDefaultDisappearingDuration", });
    internal_static_Wam_WamEventE2eMessageRecv_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Wam_WamEventE2eMessageRecv_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventE2eMessageRecv_descriptor,
        new java.lang.String[] { "AgentEngagementTypeNumber", "BotTypeNumber", "E2ECiphertextTypeNumber", "E2ECiphertextVersion", "E2EDestinationNumber", "E2EFailureReasonNumber", "E2ESenderTypeNumber", "E2ESuccessful", "EditTypeNumber", "IsHostedChat", "IsLid", "LocalAddressingModeNumber", "MessageAddressingModeNumber", "MessageMediaTypeNumber", "Offline", "RetryCount", "RevokeTypeNumber", "ServerAddressingModeNumber", "StanzaTypeNumber", "TypeOfGroupNumber", "MessageDistributionType", });
    internal_static_Wam_WamEventWamLogin_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_Wam_WamEventWamLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEventWamLogin_descriptor,
        new java.lang.String[] { "AndroidKeystoreState", "ConnectionOrigin", "ConnectionT", "LoginDnsResolver", "LoginIpSource", "LoginPort", "LoginResolvedPop", "LoginResult", "LoginT", "LogoutSessionId", "LongConnect", "NoiseProtocolVersion", "Passive", "PendingAcksCount", "RetryCount", "SequenceStep", "ServerErrorCode", });
    internal_static_Wam_WamEntryPointConversion_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Wam_WamEntryPointConversion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamEntryPointConversion_descriptor,
        new java.lang.String[] { "EntryPointConverstionType", "EntryPointConversionSource", "EntryPointConversionApp", "FirstMessageTimeStamp", "EntryPointConversionExternalMedium", "EntryPointConversionExternalSource", });
    internal_static_Wam_WamWefrClientExposure_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Wam_WamWefrClientExposure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wam_WamWefrClientExposure_descriptor,
        new java.lang.String[] { "ExposureKey", "SentWithDaily", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
