// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

public interface WamRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Wam.WamRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unknown field
   * </pre>
   *
   * <code>optional int64 timestamp = 47;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * unknown field
   * </pre>
   *
   * <code>optional int64 timestamp = 47;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string ab_key = 2141;</code>
   * @return Whether the abKey field is set.
   */
  boolean hasAbKey();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string ab_key = 2141;</code>
   * @return The abKey.
   */
  java.lang.String getAbKey();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string ab_key = 2141;</code>
   * @return The bytes for abKey.
   */
  com.google.protobuf.ByteString
      getAbKeyBytes();

  /**
   * <code>optional string ab_key2 = 4473;</code>
   * @return Whether the abKey2 field is set.
   */
  boolean hasAbKey2();
  /**
   * <code>optional string ab_key2 = 4473;</code>
   * @return The abKey2.
   */
  java.lang.String getAbKey2();
  /**
   * <code>optional string ab_key2 = 4473;</code>
   * @return The bytes for abKey2.
   */
  com.google.protobuf.ByteString
      getAbKey2Bytes();

  /**
   * <code>optional int64 app_build = 1657;</code>
   * @return Whether the appBuild field is set.
   */
  boolean hasAppBuild();
  /**
   * <code>optional int64 app_build = 1657;</code>
   * @return The appBuild.
   */
  long getAppBuild();

  /**
   * <code>optional int64 app_distribution = 1659;</code>
   * @return Whether the appDistribution field is set.
   */
  boolean hasAppDistribution();
  /**
   * <code>optional int64 app_distribution = 1659;</code>
   * @return The appDistribution.
   */
  long getAppDistribution();

  /**
   * <code>optional int64 app_is_beta_release = 21;</code>
   * @return Whether the appIsBetaRelease field is set.
   */
  boolean hasAppIsBetaRelease();
  /**
   * <code>optional int64 app_is_beta_release = 21;</code>
   * @return The appIsBetaRelease.
   */
  long getAppIsBetaRelease();

  /**
   * <code>optional string app_version = 17;</code>
   * @return Whether the appVersion field is set.
   */
  boolean hasAppVersion();
  /**
   * <code>optional string app_version = 17;</code>
   * @return The appVersion.
   */
  java.lang.String getAppVersion();
  /**
   * <code>optional string app_version = 17;</code>
   * @return The bytes for appVersion.
   */
  com.google.protobuf.ByteString
      getAppVersionBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string calling_test_bucket = 15953;</code>
   * @return Whether the callingTestBucket field is set.
   */
  boolean hasCallingTestBucket();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string calling_test_bucket = 15953;</code>
   * @return The callingTestBucket.
   */
  java.lang.String getCallingTestBucket();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string calling_test_bucket = 15953;</code>
   * @return The bytes for callingTestBucket.
   */
  com.google.protobuf.ByteString
      getCallingTestBucketBytes();

  /**
   * <code>optional int64 device_classification = 14507;</code>
   * @return Whether the deviceClassification field is set.
   */
  boolean hasDeviceClassification();
  /**
   * <code>optional int64 device_classification = 14507;</code>
   * @return The deviceClassification.
   */
  long getDeviceClassification();

  /**
   * <code>optional string device_name = 13;</code>
   * @return Whether the deviceName field is set.
   */
  boolean hasDeviceName();
  /**
   * <code>optional string device_name = 13;</code>
   * @return The deviceName.
   */
  java.lang.String getDeviceName();
  /**
   * <code>optional string device_name = 13;</code>
   * @return The bytes for deviceName.
   */
  com.google.protobuf.ByteString
      getDeviceNameBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string device_version = 4505;</code>
   * @return Whether the deviceVersion field is set.
   */
  boolean hasDeviceVersion();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string device_version = 4505;</code>
   * @return The deviceVersion.
   */
  java.lang.String getDeviceVersion();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string device_version = 4505;</code>
   * @return The bytes for deviceVersion.
   */
  com.google.protobuf.ByteString
      getDeviceVersionBytes();

  /**
   * <code>optional string expo_key = 5029;</code>
   * @return Whether the expoKey field is set.
   */
  boolean hasExpoKey();
  /**
   * <code>optional string expo_key = 5029;</code>
   * @return The expoKey.
   */
  java.lang.String getExpoKey();
  /**
   * <code>optional string expo_key = 5029;</code>
   * @return The bytes for expoKey.
   */
  com.google.protobuf.ByteString
      getExpoKeyBytes();

  /**
   * <code>optional string iphone_os_build_number = 7825;</code>
   * @return Whether the iphoneOsBuildNumber field is set.
   */
  boolean hasIphoneOsBuildNumber();
  /**
   * <code>optional string iphone_os_build_number = 7825;</code>
   * @return The iphoneOsBuildNumber.
   */
  java.lang.String getIphoneOsBuildNumber();
  /**
   * <code>optional string iphone_os_build_number = 7825;</code>
   * @return The bytes for iphoneOsBuildNumber.
   */
  com.google.protobuf.ByteString
      getIphoneOsBuildNumberBytes();

  /**
   * <code>optional int64 iphone_process = 387;</code>
   * @return Whether the iphoneProcess field is set.
   */
  boolean hasIphoneProcess();
  /**
   * <code>optional int64 iphone_process = 387;</code>
   * @return The iphoneProcess.
   */
  long getIphoneProcess();

  /**
   * <code>optional string iphone_sdk_version = 9337;</code>
   * @return Whether the iphoneSdkVersion field is set.
   */
  boolean hasIphoneSdkVersion();
  /**
   * <code>optional string iphone_sdk_version = 9337;</code>
   * @return The iphoneSdkVersion.
   */
  java.lang.String getIphoneSdkVersion();
  /**
   * <code>optional string iphone_sdk_version = 9337;</code>
   * @return The bytes for iphoneSdkVersion.
   */
  com.google.protobuf.ByteString
      getIphoneSdkVersionBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_companion = 12027;</code>
   * @return Whether the isCompanion field is set.
   */
  boolean hasIsCompanion();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 is_companion = 12027;</code>
   * @return The isCompanion.
   */
  long getIsCompanion();

  /**
   * <code>optional int64 is_md_opt_in = 7335;</code>
   * @return Whether the isMdOptIn field is set.
   */
  boolean hasIsMdOptIn();
  /**
   * <code>optional int64 is_md_opt_in = 7335;</code>
   * @return The isMdOptIn.
   */
  long getIsMdOptIn();

  /**
   * <code>optional int64 mcc = 5;</code>
   * @return Whether the mcc field is set.
   */
  boolean hasMcc();
  /**
   * <code>optional int64 mcc = 5;</code>
   * @return The mcc.
   */
  long getMcc();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 mem_class = 655;</code>
   * @return Whether the memClass field is set.
   */
  boolean hasMemClass();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 mem_class = 655;</code>
   * @return The memClass.
   */
  long getMemClass();

  /**
   * <code>optional int64 mnc = 3;</code>
   * @return Whether the mnc field is set.
   */
  boolean hasMnc();
  /**
   * <code>optional int64 mnc = 3;</code>
   * @return The mnc.
   */
  long getMnc();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string mobile_build_number = 15611;</code>
   * @return Whether the mobileBuildNumber field is set.
   */
  boolean hasMobileBuildNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string mobile_build_number = 15611;</code>
   * @return The mobileBuildNumber.
   */
  java.lang.String getMobileBuildNumber();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string mobile_build_number = 15611;</code>
   * @return The bytes for mobileBuildNumber.
   */
  com.google.protobuf.ByteString
      getMobileBuildNumberBytes();

  /**
   * <code>optional int64 network_is_wifi = 23;</code>
   * @return Whether the networkIsWifi field is set.
   */
  boolean hasNetworkIsWifi();
  /**
   * <code>optional int64 network_is_wifi = 23;</code>
   * @return The networkIsWifi.
   */
  long getNetworkIsWifi();

  /**
   * <code>optional int64 network_radio_type = 105;</code>
   * @return Whether the networkRadioType field is set.
   */
  boolean hasNetworkRadioType();
  /**
   * <code>optional int64 network_radio_type = 105;</code>
   * @return The networkRadioType.
   */
  long getNetworkRadioType();

  /**
   * <code>optional int64 oc_version = 6251;</code>
   * @return Whether the ocVersion field is set.
   */
  boolean hasOcVersion();
  /**
   * <code>optional int64 oc_version = 6251;</code>
   * @return The ocVersion.
   */
  long getOcVersion();

  /**
   * <code>optional string os_version = 15;</code>
   * @return Whether the osVersion field is set.
   */
  boolean hasOsVersion();
  /**
   * <code>optional string os_version = 15;</code>
   * @return The osVersion.
   */
  java.lang.String getOsVersion();
  /**
   * <code>optional string os_version = 15;</code>
   * @return The bytes for osVersion.
   */
  com.google.protobuf.ByteString
      getOsVersionBytes();

  /**
   * <code>optional int64 platform = 11;</code>
   * @return Whether the platform field is set.
   */
  boolean hasPlatform();
  /**
   * <code>optional int64 platform = 11;</code>
   * @return The platform.
   */
  long getPlatform();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string product = 7257;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string product = 7257;</code>
   * @return The product.
   */
  java.lang.String getProduct();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string product = 7257;</code>
   * @return The bytes for product.
   */
  com.google.protobuf.ByteString
      getProductBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string ps_country_code = 6833;</code>
   * @return Whether the psCountryCode field is set.
   */
  boolean hasPsCountryCode();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string ps_country_code = 6833;</code>
   * @return The psCountryCode.
   */
  java.lang.String getPsCountryCode();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string ps_country_code = 6833;</code>
   * @return The bytes for psCountryCode.
   */
  com.google.protobuf.ByteString
      getPsCountryCodeBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string ps_id = 6005;</code>
   * @return Whether the psId field is set.
   */
  boolean hasPsId();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string ps_id = 6005;</code>
   * @return The psId.
   */
  java.lang.String getPsId();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string ps_id = 6005;</code>
   * @return The bytes for psId.
   */
  com.google.protobuf.ByteString
      getPsIdBytes();

  /**
   * <code>optional int64 service_improvement_opt_out = 13293;</code>
   * @return Whether the serviceImprovementOptOut field is set.
   */
  boolean hasServiceImprovementOptOut();
  /**
   * <code>optional int64 service_improvement_opt_out = 13293;</code>
   * @return The serviceImprovementOptOut.
   */
  long getServiceImprovementOptOut();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string stream_id = 3543;</code>
   * @return Whether the streamId field is set.
   */
  boolean hasStreamId();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string stream_id = 3543;</code>
   * @return The streamId.
   */
  java.lang.String getStreamId();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string stream_id = 3543;</code>
   * @return The bytes for streamId.
   */
  com.google.protobuf.ByteString
      getStreamIdBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string user_activity_logging_method = 2087;</code>
   * @return Whether the userActivityLoggingMethod field is set.
   */
  boolean hasUserActivityLoggingMethod();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string user_activity_logging_method = 2087;</code>
   * @return The userActivityLoggingMethod.
   */
  java.lang.String getUserActivityLoggingMethod();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string user_activity_logging_method = 2087;</code>
   * @return The bytes for userActivityLoggingMethod.
   */
  com.google.protobuf.ByteString
      getUserActivityLoggingMethodBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string wameta_logger_test_filter = 15881;</code>
   * @return Whether the wametaLoggerTestFilter field is set.
   */
  boolean hasWametaLoggerTestFilter();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string wameta_logger_test_filter = 15881;</code>
   * @return The wametaLoggerTestFilter.
   */
  java.lang.String getWametaLoggerTestFilter();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string wameta_logger_test_filter = 15881;</code>
   * @return The bytes for wametaLoggerTestFilter.
   */
  com.google.protobuf.ByteString
      getWametaLoggerTestFilterBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string webc_phone_platform = 707;</code>
   * @return Whether the webcPhonePlatform field is set.
   */
  boolean hasWebcPhonePlatform();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string webc_phone_platform = 707;</code>
   * @return The webcPhonePlatform.
   */
  java.lang.String getWebcPhonePlatform();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional string webc_phone_platform = 707;</code>
   * @return The bytes for webcPhonePlatform.
   */
  com.google.protobuf.ByteString
      getWebcPhonePlatformBytes();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 total_memory = 689;</code>
   * @return Whether the totalMemory field is set.
   */
  boolean hasTotalMemory();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 total_memory = 689;</code>
   * @return The totalMemory.
   */
  long getTotalMemory();

  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 year_class_2016 = 2617;</code>
   * @return Whether the yearClass2016 field is set.
   */
  boolean hasYearClass2016();
  /**
   * <pre>
   * unknown type
   * </pre>
   *
   * <code>optional int64 year_class_2016 = 2617;</code>
   * @return The yearClass2016.
   */
  long getYearClass2016();

  /**
   * <code>optional string model = 287;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>optional string model = 287;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 287;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>optional string manufacturer = 289;</code>
   * @return Whether the manufacturer field is set.
   */
  boolean hasManufacturer();
  /**
   * <code>optional string manufacturer = 289;</code>
   * @return The manufacturer.
   */
  java.lang.String getManufacturer();
  /**
   * <code>optional string manufacturer = 289;</code>
   * @return The bytes for manufacturer.
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <code>optional int64 number_of_inactive_accounts = 15265;</code>
   * @return Whether the numberOfInactiveAccounts field is set.
   */
  boolean hasNumberOfInactiveAccounts();
  /**
   * <code>optional int64 number_of_inactive_accounts = 15265;</code>
   * @return The numberOfInactiveAccounts.
   */
  long getNumberOfInactiveAccounts();

  /**
   * <code>optional string location = 2795;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>optional string location = 2795;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>optional string location = 2795;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>optional string device = 495;</code>
   * @return Whether the device field is set.
   */
  boolean hasDevice();
  /**
   * <code>optional string device = 495;</code>
   * @return The device.
   */
  java.lang.String getDevice();
  /**
   * <code>optional string device = 495;</code>
   * @return The bytes for device.
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <code>optional int64 screen_diagonal = 12017;</code>
   * @return Whether the screenDiagonal field is set.
   */
  boolean hasScreenDiagonal();
  /**
   * <code>optional int64 screen_diagonal = 12017;</code>
   * @return The screenDiagonal.
   */
  long getScreenDiagonal();

  /**
   * <code>optional int64 is_google_play_install = 10255;</code>
   * @return Whether the isGooglePlayInstall field is set.
   */
  boolean hasIsGooglePlayInstall();
  /**
   * <code>optional int64 is_google_play_install = 10255;</code>
   * @return The isGooglePlayInstall.
   */
  long getIsGooglePlayInstall();

  /**
   * <pre>
   * unknown field
   * </pre>
   *
   * <code>repeated .Wam.WamEvent events = 65535;</code>
   */
  java.util.List<Wam.proto.WamEvent> 
      getEventsList();
  /**
   * <pre>
   * unknown field
   * </pre>
   *
   * <code>repeated .Wam.WamEvent events = 65535;</code>
   */
  Wam.proto.WamEvent getEvents(int index);
  /**
   * <pre>
   * unknown field
   * </pre>
   *
   * <code>repeated .Wam.WamEvent events = 65535;</code>
   */
  int getEventsCount();
  /**
   * <pre>
   * unknown field
   * </pre>
   *
   * <code>repeated .Wam.WamEvent events = 65535;</code>
   */
  java.util.List<? extends Wam.proto.WamEventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <pre>
   * unknown field
   * </pre>
   *
   * <code>repeated .Wam.WamEvent events = 65535;</code>
   */
  Wam.proto.WamEventOrBuilder getEventsOrBuilder(
      int index);
}
