// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAM.proto

package Wam.proto;

/**
 * Protobuf type {@code Wam.WamWefrClientExposure}
 */
public  final class WamWefrClientExposure extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Wam.WamWefrClientExposure)
    WamWefrClientExposureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WamWefrClientExposure.newBuilder() to construct.
  private WamWefrClientExposure(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WamWefrClientExposure() {
    exposureKey_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WamWefrClientExposure();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WamWefrClientExposure(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            exposureKey_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000002;
            sentWithDaily_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Wam.proto.WamProto.internal_static_Wam_WamWefrClientExposure_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Wam.proto.WamProto.internal_static_Wam_WamWefrClientExposure_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Wam.proto.WamWefrClientExposure.class, Wam.proto.WamWefrClientExposure.Builder.class);
  }

  private int bitField0_;
  public static final int EXPOSURE_KEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object exposureKey_;
  /**
   * <code>optional string exposure_key = 1;</code>
   * @return Whether the exposureKey field is set.
   */
  public boolean hasExposureKey() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string exposure_key = 1;</code>
   * @return The exposureKey.
   */
  public java.lang.String getExposureKey() {
    java.lang.Object ref = exposureKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        exposureKey_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string exposure_key = 1;</code>
   * @return The bytes for exposureKey.
   */
  public com.google.protobuf.ByteString
      getExposureKeyBytes() {
    java.lang.Object ref = exposureKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exposureKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENT_WITH_DAILY_FIELD_NUMBER = 3;
  private long sentWithDaily_;
  /**
   * <code>optional int64 sent_with_daily = 3;</code>
   * @return Whether the sentWithDaily field is set.
   */
  public boolean hasSentWithDaily() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 sent_with_daily = 3;</code>
   * @return The sentWithDaily.
   */
  public long getSentWithDaily() {
    return sentWithDaily_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, exposureKey_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(3, sentWithDaily_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, exposureKey_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, sentWithDaily_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Wam.proto.WamWefrClientExposure)) {
      return super.equals(obj);
    }
    Wam.proto.WamWefrClientExposure other = (Wam.proto.WamWefrClientExposure) obj;

    if (hasExposureKey() != other.hasExposureKey()) return false;
    if (hasExposureKey()) {
      if (!getExposureKey()
          .equals(other.getExposureKey())) return false;
    }
    if (hasSentWithDaily() != other.hasSentWithDaily()) return false;
    if (hasSentWithDaily()) {
      if (getSentWithDaily()
          != other.getSentWithDaily()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasExposureKey()) {
      hash = (37 * hash) + EXPOSURE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getExposureKey().hashCode();
    }
    if (hasSentWithDaily()) {
      hash = (37 * hash) + SENT_WITH_DAILY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSentWithDaily());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Wam.proto.WamWefrClientExposure parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamWefrClientExposure parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamWefrClientExposure parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamWefrClientExposure parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamWefrClientExposure parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Wam.proto.WamWefrClientExposure parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Wam.proto.WamWefrClientExposure parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamWefrClientExposure parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamWefrClientExposure parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Wam.proto.WamWefrClientExposure parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Wam.proto.WamWefrClientExposure parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Wam.proto.WamWefrClientExposure parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Wam.proto.WamWefrClientExposure prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Wam.WamWefrClientExposure}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Wam.WamWefrClientExposure)
      Wam.proto.WamWefrClientExposureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Wam.proto.WamProto.internal_static_Wam_WamWefrClientExposure_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Wam.proto.WamProto.internal_static_Wam_WamWefrClientExposure_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Wam.proto.WamWefrClientExposure.class, Wam.proto.WamWefrClientExposure.Builder.class);
    }

    // Construct using Wam.proto.WamWefrClientExposure.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      exposureKey_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      sentWithDaily_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Wam.proto.WamProto.internal_static_Wam_WamWefrClientExposure_descriptor;
    }

    @java.lang.Override
    public Wam.proto.WamWefrClientExposure getDefaultInstanceForType() {
      return Wam.proto.WamWefrClientExposure.getDefaultInstance();
    }

    @java.lang.Override
    public Wam.proto.WamWefrClientExposure build() {
      Wam.proto.WamWefrClientExposure result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Wam.proto.WamWefrClientExposure buildPartial() {
      Wam.proto.WamWefrClientExposure result = new Wam.proto.WamWefrClientExposure(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.exposureKey_ = exposureKey_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sentWithDaily_ = sentWithDaily_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Wam.proto.WamWefrClientExposure) {
        return mergeFrom((Wam.proto.WamWefrClientExposure)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Wam.proto.WamWefrClientExposure other) {
      if (other == Wam.proto.WamWefrClientExposure.getDefaultInstance()) return this;
      if (other.hasExposureKey()) {
        bitField0_ |= 0x00000001;
        exposureKey_ = other.exposureKey_;
        onChanged();
      }
      if (other.hasSentWithDaily()) {
        setSentWithDaily(other.getSentWithDaily());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Wam.proto.WamWefrClientExposure parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Wam.proto.WamWefrClientExposure) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object exposureKey_ = "";
    /**
     * <code>optional string exposure_key = 1;</code>
     * @return Whether the exposureKey field is set.
     */
    public boolean hasExposureKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string exposure_key = 1;</code>
     * @return The exposureKey.
     */
    public java.lang.String getExposureKey() {
      java.lang.Object ref = exposureKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exposureKey_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string exposure_key = 1;</code>
     * @return The bytes for exposureKey.
     */
    public com.google.protobuf.ByteString
        getExposureKeyBytes() {
      java.lang.Object ref = exposureKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exposureKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string exposure_key = 1;</code>
     * @param value The exposureKey to set.
     * @return This builder for chaining.
     */
    public Builder setExposureKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      exposureKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string exposure_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExposureKey() {
      bitField0_ = (bitField0_ & ~0x00000001);
      exposureKey_ = getDefaultInstance().getExposureKey();
      onChanged();
      return this;
    }
    /**
     * <code>optional string exposure_key = 1;</code>
     * @param value The bytes for exposureKey to set.
     * @return This builder for chaining.
     */
    public Builder setExposureKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      exposureKey_ = value;
      onChanged();
      return this;
    }

    private long sentWithDaily_ ;
    /**
     * <code>optional int64 sent_with_daily = 3;</code>
     * @return Whether the sentWithDaily field is set.
     */
    public boolean hasSentWithDaily() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 sent_with_daily = 3;</code>
     * @return The sentWithDaily.
     */
    public long getSentWithDaily() {
      return sentWithDaily_;
    }
    /**
     * <code>optional int64 sent_with_daily = 3;</code>
     * @param value The sentWithDaily to set.
     * @return This builder for chaining.
     */
    public Builder setSentWithDaily(long value) {
      bitField0_ |= 0x00000002;
      sentWithDaily_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 sent_with_daily = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSentWithDaily() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sentWithDaily_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Wam.WamWefrClientExposure)
  }

  // @@protoc_insertion_point(class_scope:Wam.WamWefrClientExposure)
  private static final Wam.proto.WamWefrClientExposure DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Wam.proto.WamWefrClientExposure();
  }

  public static Wam.proto.WamWefrClientExposure getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<WamWefrClientExposure>
      PARSER = new com.google.protobuf.AbstractParser<WamWefrClientExposure>() {
    @java.lang.Override
    public WamWefrClientExposure parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WamWefrClientExposure(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WamWefrClientExposure> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WamWefrClientExposure> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Wam.proto.WamWefrClientExposure getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

