<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.1.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.whatsapp.android</groupId>
    <artifactId>whatsapp-android</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>whatsapp-android</name>
    <description>Demo project for Spring Boot</description>
    <properties>
        <java.version>1.8</java.version>
        <log4j2.version>2.18.0</log4j2.version>
        <plist.version>1.27</plist.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.projectreactor</groupId>
                <artifactId>reactor-bom</artifactId>
                <version>2020.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty-core</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>reactor-core</artifactId>
                    <groupId>io.projectreactor</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <!--OSS服务-->
        <dependency>
            <groupId>com.aliyun.oss</groupId>
            <artifactId>aliyun-sdk-oss</artifactId>
            <version>3.15.1</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty-http</artifactId>
        </dependency>
        <dependency>
            <groupId>org.whispersystems</groupId>
            <artifactId>curve25519-java</artifactId>
            <version>0.5.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.34.0</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.59.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.1.84.Final</version>
        </dependency>
        <dependency>
            <groupId>org.squirrelframework</groupId>
            <artifactId>squirrel-foundation</artifactId>
            <version>0.3.8</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.4</version>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.5.9</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.83</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.12</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.13</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>4.5.12</version>
        </dependency>
        <dependency>
            <groupId>com.qcloud</groupId>
            <artifactId>cos_api</artifactId>
            <version>5.6.8</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.java-websocket</groupId>
            <artifactId>Java-WebSocket</artifactId>
            <version>1.5.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>5.2.2</version>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.10.3</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.10.3</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.60</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.68</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.plist</groupId>
            <artifactId>dd-plist</artifactId>
            <version>${plist.version}</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.libphonenumber</groupId>
            <artifactId>libphonenumber</artifactId>
            <version>8.13.53</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                    <layout>ZIP</layout>
                    <includes>
                        <include>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter</artifactId>
                        </include>
                        <include>
                            <groupId>io.projectreactor.netty</groupId>
                            <artifactId>reactor-netty-core</artifactId>
                        </include>
                        <include>
                            <groupId>io.projectreactor.netty</groupId>
                            <artifactId>reactor-netty-http</artifactId>
                        </include>
                        <include>
                            <groupId>io.projectreactor</groupId>
                            <artifactId>reactor-core</artifactId>
                        </include>
                        <include>
                            <groupId>io.netty</groupId>
                            <artifactId>netty-codec-dns</artifactId>
                        </include>
                        <include>
                            <groupId>io.netty</groupId>
                            <artifactId>netty-codec-http</artifactId>
                        </include>
                        <include>
                            <groupId>io.netty</groupId>
                            <artifactId>netty-codec-http2</artifactId>
                        </include>
                        <include>
                            <groupId>io.netty</groupId>
                            <artifactId>netty-codec-socks</artifactId>
                        </include>
                        <include>
                            <groupId>io.netty</groupId>
                            <artifactId>netty-handler-proxy</artifactId>
                        </include>
                        <include>
                            <groupId>io.netty</groupId>
                            <artifactId>netty-resolver-dns</artifactId>
                        </include>
                        <include>
                            <groupId>io.netty</groupId>
                            <artifactId>netty-transport-native-epoll</artifactId>
                        </include>
                        <include>
                            <groupId>io.netty</groupId>
                            <artifactId>netty-transport-native-unix-common</artifactId>
                        </include>
                        <include>
                            <groupId>org.bouncycastle</groupId>
                            <artifactId>bcpkix-jdk15on</artifactId>
                        </include>
                        <include>
                            <groupId>com.aliyun.oss</groupId>
                            <artifactId>aliyun-sdk-oss</artifactId>
                        </include>
                        <include>
                            <groupId>org.jdom</groupId>
                            <artifactId>jdom2</artifactId>
                        </include>
                        <include>
                            <groupId>org.bouncycastle</groupId>
                            <artifactId>bcprov-jdk15on</artifactId>
                        </include>
                        <include>
                            <groupId>com.googlecode.plist</groupId>
                            <artifactId>dd-plist</artifactId>
                        </include>
                        <include>
                            <groupId>org.hdrhistogram</groupId>
                            <artifactId>HdrHistogram</artifactId>
                        </include>
                        <include>
                            <groupId>org.latencyutils</groupId>
                            <artifactId>LatencyUtils</artifactId>
                        </include>
                        <include>
                            <groupId>io.micrometer</groupId>
                            <artifactId>micrometer-core</artifactId>
                        </include>
                        <include>
                            <groupId>io.micrometer</groupId>
                            <artifactId>micrometer-registry-prometheus</artifactId>
                        </include>
                        <include>
                            <groupId>io.prometheus</groupId>
                            <artifactId>simpleclient_common</artifactId>
                        </include>
                        <include>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-actuator</artifactId>
                        </include>
                        <include>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-actuator-autoconfigure</artifactId>
                        </include>
                        <include>
                            <groupId>com.aliyun</groupId>
                            <artifactId>aliyun-java-sdk-core</artifactId>
                        </include>
                        <include>
                            <groupId>com.aliyun</groupId>
                            <artifactId>aliyun-java-sdk-kms</artifactId>
                        </include>
                        <include>
                            <groupId>com.aliyun</groupId>
                            <artifactId>aliyun-java-sdk-ram</artifactId>
                        </include>
                        <include>
                            <groupId>com.google.code.gson</groupId>
                            <artifactId>gson</artifactId>
                        </include>
                        <include>
                            <groupId>commons-logging</groupId>
                            <artifactId>commons-logging</artifactId>
                        </include>
                        <include>
                            <groupId>org.ini4j</groupId>
                            <artifactId>ini4j</artifactId>
                        </include>
                        <include>
                            <groupId>javax.activation</groupId>
                            <artifactId>javax.activation-api</artifactId>
                        </include>
                        <include>
                            <groupId>javax.xml.bind</groupId>
                            <artifactId>jaxb-api</artifactId>
                        </include>
                        <include>
                            <groupId>org.codehaus.jettison</groupId>
                            <artifactId>jettison</artifactId>
                        </include>
                        <include>
                            <groupId>io.opentracing</groupId>
                            <artifactId>opentracing-api</artifactId>
                        </include>
                        <include>
                            <groupId>io.opentracing</groupId>
                            <artifactId>opentracing-noop</artifactId>
                        </include>
                        <include>
                            <groupId>io.opentracing</groupId>
                            <artifactId>opentracing-util</artifactId>
                        </include>
                        <include>
                            <groupId>org.jacoco</groupId>
                            <artifactId>org.jacoco.agent</artifactId>
                        </include>
                        <include>
                            <groupId>stax</groupId>
                            <artifactId>stax-api</artifactId>
                        </include>
                        <include>
                            <groupId>io.prometheus</groupId>
                            <artifactId>simpleclient</artifactId>
                        </include>
                        <include>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-actuator</artifactId>
                        </include>
                        <include>
                            <groupId>com.googlecode.libphonenumber</groupId>
                            <artifactId>libphonenumber</artifactId>
                        </include>
                        <dependency>
                            <groupId>io.netty</groupId>
                            <artifactId>netty-handler</artifactId>
                        </dependency>
                    </includes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
